const { google } = require('googleapis');
const path = require('path');
const fs = require('fs');

async function saveReport() {
  const auth = new google.auth.GoogleAuth({
    keyFile: path.join(__dirname, 'google-credentials.json'),
    scopes: ['https://www.googleapis.com/auth/drive.file', 'https://www.googleapis.com/auth/drive.metadata.readonly'],
  });

  const drive = google.drive({ version: 'v3', auth });

  console.log('--- Google Drive Report Service (Shared Drive Enabled) ---');
  
  const reportContent = `業務日報 - 2026/03/11
================================

【業務内容】
YouTubeランキング更新システムの不具合調査および修正・最適化

【プロジェクト】
HEAT (Top-Song-Cambodia)

【対応詳細】
1. タイムアウト不具合の解消
   - 発生事象：3月10日のデイリー更新がAI分析フェーズで停止。
   - 原因調査：SNAPSHOTシート（約8,200行）の走査時に、ループ内でGoogleの時刻変換サービスを多用しており、読み込みだけで約280秒を消費していたため。
   - 対策実施：日付処理を純粋なJavaScript計算に置き換え、外部サービス呼び出しを排除。
   - 結果：読み込み時間が「280秒」→「1秒未満」へ激的に改善。

2. 30曲体制の維持とAI分析最適化
   - ユーザー要望に基づき、分析対象30曲を維持。
   - コメント取得数を100件から50件に制限し、1曲あたりのAPIコストと待機時間を削減。
   - チャンクサイズを調整し、GASの6分制限内に余裕を持って完結する構成に変更。

3. システムの復旧とスケール対応
   - 欠落していた実行トリガーを再設定。
   - 将来的なデータ増（数万行レベル）にも耐えられる高速スキャンロジックを導入。
   - 本日の手動更新（snapshotStats / autoGenerateDailyRanking）が正常完了することを確認。

【YouTube用スクリプト・教訓】
- 「GASの6分制限」という物理的な壁に当たった際の切り分け。
- ループ内の Service Call (Utilities.formatDate等) が蓄積するオーバーヘッドの大きさ。
- メモリ上でデータを一括処理し、文字列操作だけで比較を行うことによる100倍以上の高速化実例。
`;

  try {
    // 1. Search for "HEAT" folder
    // Added supportsAllDrives: true
    let heatFolderId = await findFolder(drive, "HEAT");
    if (!heatFolderId) {
        console.error('❌ ERROR: "HEAT" folder not found.');
        const creds = JSON.parse(fs.readFileSync(path.join(__dirname, 'google-credentials.json')));
        console.log(`Please ensure the "HEAT" folder is shared with: ${creds.client_email}`);
        return;
    }
    console.log(`✅ Found "HEAT" folder: ${heatFolderId}`);

    // 2. Search for "日報" folder inside "HEAT"
    let dailyReportFolderId = await findFolder(drive, "日報", heatFolderId);
    if (!dailyReportFolderId) {
        console.log('Creating "日報" folder inside "HEAT"...');
        try {
            const res = await drive.files.create({
                resource: {
                    name: '日報',
                    mimeType: 'application/vnd.google-apps.folder',
                    parents: [heatFolderId]
                },
                fields: 'id',
                supportsAllDrives: true, // IMPORTANT FOR SHARED DRIVES
            });
            dailyReportFolderId = res.data.id;
            console.log(`✅ Created "日報" folder: ${dailyReportFolderId}`);
        } catch (e) {
            console.error('❌ FAILED to create "日報" folder:', e.message);
            console.log('Falling back to "HEAT" folder...');
            dailyReportFolderId = heatFolderId;
        }
    } else {
        console.log(`✅ Found "日報" folder: ${dailyReportFolderId}`);
    }

    // 3. Create the .txt file
    const fileName = `日報_20260311_ランキング更新改善.txt`;
    console.log(`Uploading file: ${fileName}...`);
    const fileMetadata = {
      name: fileName,
      parents: [dailyReportFolderId],
    };
    const media = {
      mimeType: 'text/plain',
      body: reportContent,
    };
    
    // Attempt creation with supportsAllDrives
    const file = await drive.files.create({
      resource: fileMetadata,
      media: media,
      fields: 'id, name',
      supportsAllDrives: true, // IMPORTANT FOR SHARED DRIVES
    });

    console.log('🎉 SUCCESS! File created/uploaded.');
    console.log('File Name:', file.data.name);
    console.log('File ID:', file.data.id);

  } catch (err) {
    console.error('Unexpected error:', err.message);
    if (err.message.includes('quota')) {
        console.log('--- QUOTA ERROR DETECTED ---');
        console.log('This often means the Service Account is out of storage.');
        console.log('Solution: Enable Shared Drive or ensure the Service Account is using the parent folder owner quota.');
    }
  }
}

async function findFolder(drive, name, parentId = null) {
  let query = `name = '${name}' and mimeType = 'application/vnd.google-apps.folder' and trashed = false`;
  if (parentId) {
    query += ` and '${parentId}' in parents`;
  }
  try {
    const res = await drive.files.list({
      q: query,
      fields: 'files(id, name)',
      spaces: 'drive',
      supportsAllDrives: true, // Search in all drives
      includeItemsFromAllDrives: true,
    });
    return res.data.files.length > 0 ? res.data.files[0].id : null;
  } catch (e) {
    return null;
  }
}

saveReport();
