/***************
 * Main.gs
 * 役割:
 *  - onOpen(): メニュー追加
 *  - setDailyTriggers(): 毎日自動実行トリガー設定 (Snapshot, UpdateSongs)
 *  - setFridayTrigger(): 金曜朝の自動ランキング設定
 *  - autoGenerateFridayRanking(): 金曜朝の全自動処理（ランキング作成 + 通知）
 ***************/

function onOpen() {
    const ui = SpreadsheetApp.getUi();
    ui.createMenu('🎬 ランキング管理')
        .addItem('1. 統計を記録 (snapshotStats)', 'snapshotStats')
        .addItem('2. 新曲を探索 (updateSongs)', 'updateSongs')
        .addItem('   └ VannDaのみ再探査', 'updateVannDaOnly')
        .addItem('   └ SONGSシートを新着順にソート', 'manualSortSongs')
        .addSeparator()
        .addItem('3. Dailyランキング作成', 'autoGenerateDailyRanking')
        .addItem('4. Weeklyランキング作成', 'autoGenerateWeeklyRanking')
        .addItem('5. 脚本生成 (buildMcScript)', 'buildMcScript')
        .addSeparator()
        .addItem('⏰ タイマー(トリガー)をすべて初期化', 'refreshAllTriggers')
        .addSeparator()
        .addItem('🔍 Geminiモデル診断', 'debugGeminiModels')
        .addSeparator()
        .addSubMenu(ui.createMenu('管理/バックアップ')
            .addItem('ランキングをアーカイブ', 'archiveRankings')
            .addItem('脚本をアーカイブ', 'archiveMcScript')
            .addItem('SNAPSHOTをアーカイブ', 'archiveSnapshot')
            .addSeparator()
            .addItem('SNAPSHOTの重複を清掃', 'cleanupSnapshotDuplicates')
            .addItem('SONGSの重複を清掃', 'cleanupDuplicateSongs')
            .addItem('アーティスト・曲名のクリーンアップ', 'cleanupNaming')
            .addItem('AI命名正規化テストを実行', 'testNamingNormalizationOnSheet')
            .addItem('Gemini API 診断を実行', 'debugGeminiModels')
            .addSeparator()
            .addItem('アーティストURLの有効性を確認', 'checkArtistUrls')
            .addItem('URLからChannel IDを同期/修正', 'syncChannelIds')
        )
        .addToUi();
}

/**
 * 毎日自動実行するためのトリガーを設定
 */
function setDailyTriggers() {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const triggers = ScriptApp.getProjectTriggers();

    // 既存のすべてのトリガーを削除して重複を防ぐ（完全にクリーンにする）
    triggers.forEach(t => {
        ScriptApp.deleteTrigger(t);
    });

    // 毎日 新曲を探索 (18時台のリリースを捕捉)
    ScriptApp.newTrigger('updateSongs')
        .timeBased().atHour(18).nearMinute(30).everyDays(1).create();

    // 毎日 統計を取得 (反映直前の最新数値を確保)
    ScriptApp.newTrigger('snapshotStats')
        .timeBased().atHour(19).nearMinute(15).everyDays(1).create();

    // 毎日 デイリーランキングを生成 (20時)
    // ※ この中で autoPostToFacebook が呼び出されます
    ScriptApp.newTrigger('autoGenerateDailyRanking')
        .timeBased().atHour(20).everyDays(1).create();

    // 金曜日 朝7時にウィークリーランキング生成
    ScriptApp.newTrigger('autoGenerateWeeklyRanking')
        .timeBased()
        .onWeekDay(ScriptApp.WeekDay.FRIDAY)
        .atHour(7)
        .create();

    // 毎週土曜日にアーカイブを実行
    ScriptApp.newTrigger('archiveRankings')
        .timeBased().onWeekDay(ScriptApp.WeekDay.SATURDAY).atHour(5).create();

    ScriptApp.newTrigger('archiveMcScript')
        .timeBased().onWeekDay(ScriptApp.WeekDay.SATURDAY).atHour(5).create();

    ScriptApp.newTrigger('archiveSnapshot')
        .timeBased().onWeekDay(ScriptApp.WeekDay.SATURDAY).atHour(6).create();

    // 編集時トリガー（Artistsシートの自動入力）
    ScriptApp.newTrigger('onEditHandler')
        .forSpreadsheet(ss)
        .onEdit()
        .create();

    try {
        SpreadsheetApp.getUi().alert('設定完了: デイリー処理、金曜ランキング、および「Artistsシートの自動入力」をセットアップしました。');
    } catch (e) {
        Logger.log('設定完了: デイリー処理、金曜ランキング、および「Artistsシートの自動入力」をセットアップしました。 (UIが利用できないためログのみ記録)');
    }
}

/**
 * 編集時イベントハンドラ (Installable Trigger)
 */
function onEditHandler(e) {
    if (!e) return;
    const range = e.range;
    const sheet = range.getSheet();

    // ArtistsシートかつB列(YouTube URL)が編集された場合
    if (sheet.getName() !== CFG.SHEET_ARTISTS) return;
    if (range.getColumn() !== 2 || range.getRow() <= 1) return;

    const url = range.getValue().toString().trim();
    if (!url) return;

    try {
        let channelId = "";
        let handle = "";

        if (url.includes("/channel/")) {
            channelId = url.split("/channel/")[1].split("/")[0].split("?")[0];
        } else if (url.includes("/@")) {
            handle = url.split("/@")[1].split("/")[0].split("?")[0];
        } else if (url.includes("/c/")) {
            handle = url.split("/c/")[1].split("/")[0].split("?")[0];
        }

        const params = {};
        if (channelId) {
            params.id = channelId;
        } else if (handle) {
            params.forHandle = handle;
        } else {
            return;
        }

        const res = YouTube.Channels.list('snippet,statistics', params);
        if (!res.items || res.items.length === 0) return;
        const item = res.items[0];

        const row = range.getRow();
        const realId = item.id;

        // 重複チェック (C列: Channel ID)
        const allIds = sheet.getRange(1, 3, sheet.getLastRow(), 1).getValues().map(r => r[0].toString().trim());
        const duplicateRowIndex = allIds.findIndex((id, idx) => id === realId && (idx + 1) !== row);

        if (duplicateRowIndex !== -1) {
            const duplicateRow = duplicateRowIndex + 1;
            const duplicateName = sheet.getRange(duplicateRow, 1).getValue();
            SpreadsheetApp.getUi().alert(`⚠️ 重複登録エラー\n\nこのチャンネルは既に登録されています。\nアーティスト: ${duplicateName}\n(行番号: ${duplicateRow})\n\n入力した行を削除します。`);
            sheet.deleteRow(row);
            return;
        }

        const name = cleanArtistName(item.snippet.title);
        const subs = item.statistics.subscriberCount;
        const desc = item.snippet.description || "";

        // A: Name(1), C: ID(3), D: Subs(4)
        sheet.getRange(row, 1).setValue(name);
        sheet.getRange(row, 3).setValue(realId);
        sheet.getRange(row, 4).setValue(subs);

        // Facebookリンクの自動取得を試行 [NEW]
        let fbUrl = getFacebookFromSnippet_(desc);
        if (!fbUrl) {
            fbUrl = getFacebookFromHtml_(realId);
        }
        if (fbUrl) {
            sheet.getRange(row, 5).setValue(fbUrl);
        }

    } catch (err) {
        console.error("onEditHandler Error: " + err);
    }
}

/**
 * 説明欄からFacebookリンクを抽出
 */
function getFacebookFromSnippet_(desc) {
    return extractFacebookFromText_(desc);
}

/**
 * チャンネルページHTMLからFacebookリンクを抽出 (ベストエフォート)
 */
function getFacebookFromHtml_(channelId) {
    const urls = [
        `https://www.youtube.com/channel/${channelId}`,
        `https://www.youtube.com/channel/${channelId}/about`
    ];

    for (const url of urls) {
        try {
            const html = UrlFetchApp.fetch(url, { muteHttpExceptions: true }).getContentText();
            const fbUrl = extractFacebookFromText_(html);
            if (fbUrl) {
                console.log(`Found Facebook link at: ${url}`);
                return fbUrl;
            }
        } catch (e) {
            console.error(`Error fetching ${url}: ${e}`);
        }
    }
    return null;
}

/**
 * テキスト中からFacebookリンクを抽出してデコードする (超強力版)
 */
function extractFacebookFromText_(text) {
    if (!text) return null;

    // 1. 全文から facebook.com という文字列をすべて探す
    const target = "facebook.com";
    let index = text.indexOf(target);
    const foundUrls = new Set();

    while (index !== -1) {
        // 前後150文字程度をバッファとして取得
        const start = Math.max(0, index - 150);
        const end = Math.min(text.length, index + 150);
        let snippet = text.substring(start, end);

        // YouTubeのJSONエスケープ (\/, \n, \", \u0026, x3d ...) を徹底的に解除
        snippet = snippet
            .replace(/\\r|\\n/g, ' ')
            .replace(/\\\\/g, '\\')      // \\ -> \
            .replace(/\\\//g, '/')       // \/ -> /
            .replace(/\\"/g, '"')        // \" -> "
            .replace(/x22/g, '"')        // x22 -> "
            .replace(/u0022/g, '"')
            .replace(/x3d/g, '=')        // x3d -> =
            .replace(/u003d/g, '=')
            .replace(/u0026/g, '&')
            .replace(/x26/g, '&');

        // デコードを試みる (2回繰り返して多重エンコードに対応)
        try { snippet = decodeURIComponent(snippet); } catch (e) { }
        try { snippet = decodeURIComponent(snippet); } catch (e) { }

        // 改めて Facebook のフルURLを正規表現で探す
        const finalMatch = snippet.match(/https?:\/\/(?:www\.|web\.|m\.)?facebook\.com\/[^ \t\n\r"','\\<>{}|\[\]?#]+/);
        if (finalMatch) {
            const url = cleanFacebookUrl_(finalMatch[0]);
            if (url && !url.includes('facebook.com/tr') && !url.includes('facebook.com/sharer')) {
                foundUrls.add(url);
            }
        }

        index = text.indexOf(target, index + 1);
    }

    // 見つかった中から最もそれらしいものを返す
    const results = Array.from(foundUrls);
    if (results.length === 0) return null;

    // profile.php ではないリンクがあればそれを優先（より具体的である可能性が高いため）
    const specific = results.find(u => !u.includes('profile.php'));
    return specific || results[0];
}

/**
 * Facebook URLを整形（profile.php?id= 対応）
 */
function cleanFacebookUrl_(url) {
    if (!url) return null;

    // profile.php 形式の場合
    if (url.includes('profile.php')) {
        const idMatch = url.match(/[?&]id=([^&"'\s\n\r#]+)/);
        if (idMatch) {
            return `https://www.facebook.com/profile.php?id=${idMatch[1]}`;
        }
    }

    // 通常のバニティURL形式
    return url.split(/[?#]/)[0].replace(/\/$/, '');
}

/**
 * 既存のArtistsシートをスキャンし、Facebookリンクが空の箇所を補完する
 */
function backfillFacebookLinks() {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(CFG.SHEET_ARTISTS);
    if (!sheet) return;

    const data = sheet.getDataRange().getValues();
    let count = 0;

    for (let i = 1; i < data.length; i++) {
        const row = i + 1;
        const channelId = data[i][2]; // C列
        const existingFb = data[i][4]; // E列

        if (channelId && !existingFb) {
            try {
                // Snippet (説明欄) から取得
                const res = YouTube.Channels.list('snippet', { id: channelId });
                let fbUrl = null;

                if (res.items && res.items.length > 0) {
                    fbUrl = getFacebookFromSnippet_(res.items[0].snippet.description);
                }

                // なければHTMLから取得
                if (!fbUrl) {
                    fbUrl = getFacebookFromHtml_(channelId);
                }

                if (fbUrl) {
                    sheet.getRange(row, 5).setValue(fbUrl);
                    count++;
                }
            } catch (e) {
                console.error(`Error backfilling ${channelId}: ${e}`);
            }
            Utilities.sleep(200); // 連続リクエストを少し控える
        }
    }

    SpreadsheetApp.getUi().alert(`完了: ${count} 件のアーティストにFacebookリンクを補完しました。`);
}

/**
 * Telegram通知の設定
 */
const TG_CONFIG = {
    BOT_TOKEN: '8582165720:AAG2bwkQ0GKC_ke3Po_ReR1KwuupZe1iOH8',
    CHAT_ID: '7506480434'
};

/**
 * テスト用: Telegram通知を今すぐテスト
 */
function testTelegramNotification() {
    sendTelegramNotification_('🏐 【テスト】YouTubeランキング通知テスト\n\nこのメッセージが届けば設定は完璧です！');
}

/**
 * 金曜朝に自動実行される一括処理
 */
function autoGenerateFridayRanking() {
    try {
        // 1. 週間ランキング作成 (7日間差分)
        autoGenerateWeeklyRanking();

        // 2. 通知 (Telegram)
        sendTelegramNotification_('✅ 【完了】今週のランキング(候補)が生成されました\n\n' +
            '今週のランキング候補（Top 15）の自動生成が完了しました。\n' +
            'スプレッドシートを開いて確認し、Top 10を確定させた後、脚本生成を実行してください。');

        Logger.log('Friday Auto Ranking Done.');
    } catch (e) {
        sendTelegramNotification_('⚠️ 【エラー】YouTubeランキング自動作成中\n\nエラー内容:\n' + e.toString());
    }
}

/**
 * Telegramにメッセージを送信
 */
function sendTelegramNotification_(text) {
    if (TG_CONFIG.BOT_TOKEN === 'YOUR_BOT_TOKEN') {
        Logger.log('Telegram Token not set. Notification skipped.');
        return;
    }

    try {
        logToSheet_(text); // 画面との連携用にシートへも記録
    } catch (e) {
        console.error("Failed to log to sheet:", e);
    }

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const url = `https://api.telegram.org/bot${TG_CONFIG.BOT_TOKEN}/sendMessage`;
    const fullText = text + `\n\n▼ スプレッドシート\n${ss.getUrl()}`;

    const payload = {
        method: 'post',
        contentType: 'application/json',
        payload: JSON.stringify({
            chat_id: TG_CONFIG.CHAT_ID,
            text: fullText
        })
    };

    UrlFetchApp.fetch(url, payload);
}

/**
 * Facebook への自動投稿を一括実行
 */
function autoPostToFacebook() {
    logToSheet_('【実行】autoPostToFacebook 開始');
    const PAGE_ID = '971418716059046';
    const props = PropertiesService.getScriptProperties();
    const token = props.getProperty('FB_ACCESS_TOKEN');

    if (!token) {
        sendTelegramNotification_('❌ 【エラー】FB投稿失敗: アクセストークンが未設定です。');
        return;
    }

    try {
        const data = getRankingData_();
        if (!data || !data.ranking || data.ranking.length === 0) {
            throw new Error('Ranking data is empty');
        }
        logToSheet_(`Ranking data loaded: ${data.ranking.length} items`);

        const ranking = data.ranking;
        const photoIds = [];
        const baseUrl = 'https://heat-kh.vercel.app/api/og/ranking';
        const dateStr = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy.MM.dd');

        // 1. 画像のアップロード (4枚)
        // 1.1 Rank 1
        const r1 = ranking[0];
        const r1ChangeStr = r1.rankChange === 'NEW' ? 'NEW' : (r1.rankChange > 0 ? '+' + r1.rankChange : r1.rankChange.toString());
        const r1Url = [
            `${baseUrl}?template=rank1`,
            `rank=1`,
            `artist=${encodeURIComponent(r1.artist)}`,
            `title=${encodeURIComponent(r1.title)}`,
            `heatPoint=${Math.round(r1.heatScore)}`,
            `growth=${r1.growth}`,
            `views=${r1.views}`,
            `change=${r1.rankChange}`,
            `engagement=${r1.engagement}`,
            `insight=${encodeURIComponent(r1.shortInsight || '')}`,
            `date=${encodeURIComponent(dateStr)}`
        ].join('&');
        logToSheet_('Uploading Rank 1 photo...');
        photoIds.push(uploadPhotoToFb_(r1Url, PAGE_ID, token));

        // 1.2 Multi images (2-4, 5-7, 8-10)
        for (let i = 0; i < 3; i++) {
            const start = 1 + (i * 3);
            const items = ranking.slice(start, start + 3).map(x => ({
                rank: x.rank,
                artist: x.artist,
                title: x.title,
                change: x.rankChange === 'NEW' ? 'NEW' : (x.rankChange > 0 ? '+' + x.rankChange : x.rankChange.toString())
            }));
            if (items.length > 0) {
                const multiUrl = `${baseUrl}?template=multi&items=${encodeURIComponent(JSON.stringify(items))}&date=${encodeURIComponent(dateStr)}`;
                logToSheet_(`Uploading Multi photo ${i + 1}/3...`);
                photoIds.push(uploadPhotoToFb_(multiUrl, PAGE_ID, token));
            }
        }

        // 2. フィード投稿の作成
        const r1MessageChange = r1.rankChange === 'NEW' ? 'NEW ENTRY' : (r1.rankChange > 0 ? '+' + r1.rankChange : (r1.rankChange === 0 ? 'STAY' : r1.rankChange));

        // 英語のAIインサイトを組み込む
        let insightText = '';
        if (r1.aiInsight && r1.aiInsight !== '-') {
            insightText = `\n\n🤖 HEAT AI Insight:\n${r1.aiInsight}`;
        }

        const message = `HEAT (BETA) - Cambodia Daily Ranking\n${dateStr}\n\n👑 #1 ${r1.artist} – ${r1.title}\n🔥 ${Math.round(r1.heatScore)} HEAT POINT (${r1MessageChange})${insightText}\n\n👉 Full Top 20 ranking in the first comment 👇`;

        const feedUrl = `https://graph.facebook.com/v19.0/${PAGE_ID}/feed`;
        const payload = {
            message: message,
            access_token: token
        };

        // 画像の並び順を逆にする（1位から表示されるように調整）
        photoIds.reverse().forEach((id, i) => {
            payload[`attached_media[${i}]`] = JSON.stringify({ media_fbid: id });
        });

        logToSheet_('Sending feed post request...');
        const res = UrlFetchApp.fetch(feedUrl, {
            method: 'post',
            payload: payload,
            muteHttpExceptions: true
        });
        logToSheet_(`Feed post result: ${res.getResponseCode()} - ${res.getContentText().substring(0, 100)}`);

        const postCode = res.getResponseCode();
        const postBody = res.getContentText();
        if (postCode !== 200) {
            console.error(`FB Post Error (${postCode}): ${postBody}`);
            throw new Error(`Facebook Post Error (${postCode}): ${postBody}`);
        }

        const postResult = JSON.parse(postBody);
        const rawPostId = postResult.id;
        console.log(`FB Post Success. rawPostId: ${rawPostId}`);

        // New Page Experience では PAGEID_POSTID の形式が必要な場合がある
        let finalPostId = rawPostId;
        if (!finalPostId.includes('_')) {
            finalPostId = `${PAGE_ID}_${rawPostId}`;
            console.log(`Post ID formatted with Page ID prefix: ${finalPostId}`);
        }

        // 3. トップコメントの追加
        const commentUrl = `https://graph.facebook.com/v19.0/${finalPostId}/comments`;
        const commentPayload = {
            message: 'Full Top 20:\nhttps://heat-kh.vercel.app/\nUpdated daily.',
            access_token: token
        };

        try {
            let commentRes = UrlFetchApp.fetch(commentUrl, {
                method: 'post',
                payload: commentPayload,
                muteHttpExceptions: true
            });

            let commentCode = commentRes.getResponseCode();
            let commentBody = commentRes.getContentText();

            // もし ID プレフィックス付きで失敗し、かつ元の ID と異なる場合は、元の ID でリトライ
            if (commentCode !== 200 && finalPostId !== rawPostId) {
                console.warn(`Comment failed with formatted ID (${commentCode}). Retrying with rawPostId: ${rawPostId}`);
                const retryUrl = `https://graph.facebook.com/v19.0/${rawPostId}/comments`;
                commentRes = UrlFetchApp.fetch(retryUrl, {
                    method: 'post',
                    payload: commentPayload,
                    muteHttpExceptions: true
                });
                commentCode = commentRes.getResponseCode();
                commentBody = commentRes.getContentText();
            }

            if (commentCode !== 200) {
                console.error(`FB Comment Error (${commentCode}): ${commentBody}`);
                console.log(`Debug Info - PAGE_ID: ${PAGE_ID}, Token start: ${token.substring(0, 10)}...`);
                throw new Error(`Facebook Comment Error (${commentCode}): ${commentBody}`);
            }

            Logger.log(`FB Comment Success: ${commentBody}`);
        } catch (e) {
            console.error('Comment Step Exception:', e);
            throw e;
        }

        // 4. Telegram 通知
        sendTelegramNotification_(`✅ 【成功】Facebookへの自動投稿が完了しました！\n日付: ${dateStr}\n#1: ${r1.artist}`);

    } catch (e) {
        console.error(e);
        let errorMsg = e.message;
        if (e.message.includes('code 403')) {
            errorMsg = "Facebook permission error (403). The token might be missing 'pages_manage_posts' or 'pages_read_engagement' scopes.";
        }
        sendTelegramNotification_(`❌ 【エラー】Facebook自動投稿に失敗しました。\nエラー: ${errorMsg}`);
    }
}

/**
 * Facebook アクセストークンをスクリプトプロパティに設定する（一度だけ実行してください）
 */
function setupFbToken(token) {
    if (!token) {
        console.error('エラー: トークンを指定してください。');
        return;
    }
    PropertiesService.getScriptProperties().setProperty('FB_ACCESS_TOKEN', token);

    try {
        SpreadsheetApp.getUi().alert('Facebookトークンの設定が完了しました。');
    } catch (e) {
        Logger.log('Facebookトークンの設定が完了しました。 (UIが利用できないためログのみ記録)');
    }
}

/**
 * FBへ写真をアップロード（未公開状態）
 */
function uploadPhotoToFb_(imgUrl, pageId, token) {
    const imgBlob = UrlFetchApp.fetch(imgUrl).getBlob();
    const url = `https://graph.facebook.com/v19.0/${pageId}/photos`;
    const payload = {
        source: imgBlob,
        published: 'false',
        access_token: token
    };

    const res = UrlFetchApp.fetch(url, {
        method: 'post',
        payload: payload
    });

    return JSON.parse(res.getContentText()).id;
}


function doGet(e) {
    try {
        const action = e && e.parameter && e.parameter.action;
        if (action === 'logs') {
            const ss = SpreadsheetApp.getActiveSpreadsheet();
            const shLog = ss.getSheetByName('DEBUG_LOG');
            let logs = [];
            if (shLog) {
                logs = shLog.getDataRange().getValues();
            }
            return ContentService.createTextOutput(JSON.stringify({ logs }))
                .setMimeType(ContentService.MimeType.JSON);
        }

        const data = getRankingData_();
        const output = JSON.stringify(data);
        return ContentService.createTextOutput(output)
            .setMimeType(ContentService.MimeType.JSON);
    } catch (err) {
        return ContentService.createTextOutput(JSON.stringify({ error: err.toString() }))
            .setMimeType(ContentService.MimeType.JSON);
    }
}

/**
 * RANKINGシートからデータを抽出してオブジェクト形式で返す
 */
function getRankingData_() {
    const ss = SpreadsheetApp.getActiveSpreadsheet();

    // --- 統計情報の算出 [NEW] ---
    const stats = {
        totalArtists: 0,
        totalProductions: 0,
        totalSongs: 0
    };

    const shArt = ss.getSheetByName('Artists');
    if (shArt) {
        const artValues = shArt.getDataRange().getValues();
        for (let i = 1; i < artValues.length; i++) {
            const name = String(artValues[i][0] || '').trim();
            if (!name) continue;

            const role = String(artValues[i][5] || '').trim().toUpperCase();
            if (role === 'P') {
                stats.totalProductions++;
            } else {
                stats.totalArtists++;
            }
        }
    }

    const shSongs = ss.getSheetByName('SONGS');
    if (shSongs) {
        stats.totalSongs = Math.max(0, shSongs.getLastRow() - 1);
    }
    // -------------------------

    const sh = ss.getSheetByName('RANKING_DAILY');
    if (!sh) throw new Error('RANKING_DAILY sheet not found');

    const values = sh.getDataRange().getValues();
    if (values.length < 2) return { updatedAt: new Date().toISOString(), stats, ranking: [] };

    const headers = values[0];
    const data = [];

    // ヘッダーのインデックスを特定するためのヘルパー（表記の揺れ・空白・言語に対応）
    const findHeader = (names) => {
        for (let name of names) {
            const i = headers.findIndex(h => String(h || '').trim().toLowerCase() === name.toLowerCase());
            if (i !== -1) return i;
        }
        return -1;
    };

    const idx = {
        rank: findHeader(['順位', 'Rank', '順位(1d)', '順位(7d)']),
        artist: findHeader(['アーティスト', 'Artist', '歌手']),
        title: findHeader(['曲名', 'Title', 'タイトル']),
        views: findHeader(['現在再生数', 'Total Views', 'Views', '再生数']),
        growth: findHeader(['成長率(%)', 'Growth %', 'Growth', '増加率']),
        heatScore: findHeader(['Heatスコア', 'Heat Score', 'Heat', '熱量']),
        engagement: findHeader(['反応率', 'Engagement %', 'Engagement']),
        videoId: findHeader(['videoId', 'Video ID', 'ID']),
        history: findHeader(['historyRaw', 'History', 'History Raw', '履歴データ']),
        note: findHeader(['備考', 'Note']),
        fb: findHeader(['Facebook', 'FB']),
        publishedAt: findHeader(['公開日', 'Published At', 'Published']),
        aiScore: findHeader(['AIスコア', 'AI Score', 'AI熱量']),
        aiInsight: findHeader(['AIインサイト', 'AI Insight', 'AI分析']),
        shortInsight: findHeader(['shortInsight', 'Short Insight']),
        genre: findHeader(['Genre', 'ジャンル']),
        visualConcept: findHeader(['Visual Concept', 'ビジュアル']),
        base: findHeader(['1日前', '7日前', 'Base Views']),
        prevRank: findHeader(['PrevRank', 'Previous Rank', '前回の順位'])
    };


    for (let i = 1; i < values.length; i++) {
        const row = values[i];
        if (!row[idx.rank]) continue;

        const videoId = String(row[idx.videoId] || '').trim();
        if (!videoId) continue;

        // パーセント文字列のパース (例: "12.5%" -> 12.5)
        const parsePct = (v) => {
            if (typeof v === 'number') return v;
            return parseFloat(String(v || '0').replace('%', '')) || 0;
        };

        const historyStr = String(row[idx.history] || '');
        let historyArr = historyStr ? historyStr.split(';').map(v => parseInt(v) || 0) : [];

        // 【補完】RANKINGシートに列がない場合でもSONGSシートから直接日付を取得
        let publishedAt = (idx.publishedAt !== -1 && row[idx.publishedAt]) ? row[idx.publishedAt] : "";
        if (!publishedAt && videoId) {
            const songsSh = ss.getSheetByName('SONGS');
            if (songsSh) {
                // 初回のみマップを作成（重いため）
                if (!this.songsMap) {
                    const sValues = songsSh.getDataRange().getValues();
                    this.songsMap = new Map();
                    for (let j = 1; j < sValues.length; j++) {
                        this.songsMap.set(String(sValues[j][0]).trim(), sValues[j][3]); // A:ID, D:Published
                    }
                }
                publishedAt = this.songsMap.get(videoId) || "";
            }
        }

        // 日付オブジェクトなら ISO 形式に変換
        if (publishedAt instanceof Date) {
            publishedAt = publishedAt.toISOString();
        }

        // 履歴が不足(1点以下)している場合、「7日前」の値を先頭に注入してラインを形成
        const baseV = parseInt(row[idx.base]) || 0;
        const currentV = parseInt(row[idx.views]) || 0;
        if (historyArr.length <= 1 && baseV !== currentV) {
            historyArr = [baseV, currentV];
        }

        // 順位変動の計算
        let rankChange = 0;
        if (idx.prevRank !== -1) {
            const pVal = String(row[idx.prevRank]).trim();
            const c = parseInt(row[idx.rank]) || i;
            if (pVal === '-' || pVal === '' || pVal === '100') {
                rankChange = 'NEW';
            } else {
                let p = parseInt(pVal);
                if (isNaN(p) || p === 100) {
                    rankChange = 'NEW';
                } else {
                    rankChange = p - c; // 正なら上昇、負なら下降
                }
            }
        }

        data.push({
            rank: parseInt(row[idx.rank]) || (i),
            rankChange: rankChange,
            artist: row[idx.artist] || "",
            title: row[idx.title] || "",
            views: parseInt(row[idx.views]) || 0,
            growth: parsePct(row[idx.growth]),
            heatScore: parseFloat(row[idx.heatScore]) || 0,
            engagement: parsePct(row[idx.engagement]),
            dailyViews: Math.round((historyArr.length > 1 ? (historyArr[historyArr.length - 1] - historyArr[0]) : 0)),
            note: row[idx.note] || "",
            facebook: row[idx.fb] || "",
            publishedAt: publishedAt,
            aiScore: parseInt(row[idx.aiScore]) || 0,
            aiInsight: row[idx.aiInsight] || "",
            shortInsight: (idx.shortInsight !== -1 && row[idx.shortInsight]) ? String(row[idx.shortInsight]) : "",
            genre: row[idx.genre] || "",
            visualConcept: row[idx.visualConcept] || "",
            videoId: videoId,
            thumbnail: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
            url: `https://www.youtube.com/watch?v=${videoId}`,
            history: historyArr
        });
    }

    return {
        updatedAt: new Date().toISOString(),
        stats: stats,
        ranking: data
    };
}

/**
 * クォータを消費せずにYouTube URLの有効性をチェック
 */
function checkArtistUrls() {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(CFG.SHEET_ARTISTS);
    if (!sheet) {
        SpreadsheetApp.getUi().alert('エラー: Artists シートが見つかりません。');
        return;
    }

    const lastRow = sheet.getLastRow();
    if (lastRow <= 1) {
        SpreadsheetApp.getUi().alert('チェック対象のアーティストがいません。');
        return;
    }

    const data = sheet.getRange(2, 1, lastRow - 1, 3).getValues(); // A:Name, B:URL, C:ID
    const results = [];

    // UI進捗表示用のトースト
    ss.toast('URLチェックを開始します（約' + data.length + '件）...', 'チェック中', -1);

    for (let i = 0; i < data.length; i++) {
        const name = data[i][0] || 'Unknown';
        const url = data[i][1];
        const channelId = data[i][2];
        const row = i + 2;

        if (!url && !channelId) {
            results.push(`行 ${row}: ${name} - URLとIDの両方が空です`);
            continue;
        }

        const targetUrl = url || `https://www.youtube.com/channel/${channelId}`;

        try {
            // クォータを使わない HTTP HEAD/GET リクエスト
            const response = UrlFetchApp.fetch(targetUrl, {
                muteHttpExceptions: true,
                followRedirects: true,
                headers: { "Accept-Language": "ja,en-US;q=0.9,en;q=0.8" }
            });
            const code = response.getResponseCode();

            // YouTubeの場合、チャンネルが存在しないと404を返す
            if (code === 404) {
                results.push(`行 ${row}: ${name} - リンク切れ (404)`);
            } else if (code !== 200) {
                results.push(`行 ${row}: ${name} - 異常応答 (${code})`);
            }
        } catch (e) {
            results.push(`行 ${row}: ${name} - 接続失敗: ${e.message}`);
        }

        // 10件ごとに通知
        if ((i + 1) % 10 === 0) {
            ss.toast(`${i + 1} / ${data.length} 件完了...`, 'チェック中');
        }
        Utilities.sleep(100); // サーバー負荷軽減のため僅かに待機
    }

    ss.toast('チェックが完了しました。', '完了', 3);

    if (results.length === 0) {
        SpreadsheetApp.getUi().alert('【合格】すべて有効\n\n全アーティストのURLが正常に応答しました。取りこぼしの原因はURL自体ではなく、IDの未記入か同期の問題である可能性が高いです。');
    } else {
        const msg = '以下のアーティスト（' + results.length + '件）に問題が見つかりました:\n' +
            '------------------------------------------\n' +
            results.join('\n') +
            '\n------------------------------------------\n' +
            'これらはYouTubeから情報を取得できないため、反映されません。リンクを更新してください。';
        console.log(msg);

        // メッセージが長すぎる場合の考慮
        if (msg.length > 1500) {
            SpreadsheetApp.getUi().alert('多数の問題（' + results.length + '件）が見つかりました。詳細は「表示 > ログ」を確認してください。');
        } else {
            SpreadsheetApp.getUi().alert(msg);
        }
    }
}

/**
 * URLをもとにChannel ID (C列) が正しいか確認し、
 * 空欄または間違いがあればYouTubeから取得して補完・修正する
 */
function syncChannelIds() {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(CFG.SHEET_ARTISTS);
    if (!sheet) return;

    const data = sheet.getDataRange().getValues();
    const ui = SpreadsheetApp.getUi();
    const response = ui.alert('Channel ID同期', '全アーティストのURLを確認し、Channel IDを最新の状態に更新します。実行しますか？\n(1件につき1ユニットのクォータを消費します)', ui.ButtonSet.YES_NO);

    if (response !== ui.Button.YES) return;

    ss.toast('同期処理を開始します...', '実行中');
    let fixCount = 0;
    let skipCount = 0;

    for (let i = 1; i < data.length; i++) {
        const row = i + 1;
        const url = String(data[i][1] || '').trim();
        const currentId = String(data[i][2] || '').trim();

        if (!url) {
            skipCount++;
            continue;
        }

        try {
            let channelId = "";
            let handle = "";

            // URL解析
            if (url.includes("/channel/")) {
                channelId = url.split("/channel/")[1].split("/")[0].split("?")[0];
            } else if (url.includes("/@")) {
                handle = url.split("/@")[1].split("/")[0].split("?")[0];
            } else if (url.includes("/c/")) {
                handle = url.split("/c/")[1].split("/")[0].split("?")[0];
            }

            const params = {};
            if (channelId) {
                params.id = channelId;
            } else if (handle) {
                params.forHandle = handle;
            } else {
                skipCount++;
                continue; // 解析不能なURL
            }

            const res = YouTube.Channels.list('snippet,statistics', params);
            if (res.items && res.items.length > 0) {
                const item = res.items[0];
                const realId = item.id;
                const name = item.snippet.title;
                const subs = item.statistics.subscriberCount;

                // 現在のIDと異なる、または空の場合は修正
                if (realId !== currentId) {
                    sheet.getRange(row, 1).setValue(name);      // 名前も最新に
                    sheet.getRange(row, 3).setValue(realId);    // 正しいID
                    sheet.getRange(row, 4).setValue(subs);      // 登録者数
                    fixCount++;
                    console.log(`Fixed Row ${row}: ${name} (${realId})`);
                }
            } else {
                console.warn(`Row ${row}: Channel not found for URL ${url}`);
            }
        } catch (e) {
            console.error(`Row ${row} Error: ${e.message}`);
        }

        if (i % 10 === 0) {
            ss.toast(`${i} / ${data.length - 1} 件完了...`, '同期中');
        }
        Utilities.sleep(100); // 連続リクエストを控える
    }

    ss.toast('同期が完了しました。', '完了');
    ui.alert(`同期完了\n\n修正・補完: ${fixCount} 件\nスキップ/正常: ${data.length - 1 - fixCount} 件\n\nこれでChannel IDが最新のURLに基づいた正しいものになりました。`);
}

/**
 * 【設定用】新しいFacebookトークンを登録する（一度だけ実行）
 */
function updateTokenOnce() {
    const newToken = 'EAAViKaZBkCW8BQ2wfTXfLUjjh65xtdIZCxpbSbShrEDfau8peK2e2dXu3vD2fmIjcdGTZBNv3XzFgL8PLS5H8lZALrAoPQC66D91PEDCeu1FnZBxksYNUQpsZBnBVEJgpXX7DZCOXzKOgDUKnkJWwdAPYpPnvhrnJMqZBMdKZCUi4JMfl0C7Evzud52dWrpfhl02NvWPZChH1GsQdVTqaab88WVoe9';
    setupFbToken(newToken);
}

/**
 * 【設定用】タイマー（トリガー）を最新の順番に再設定する（一度だけ実行）
 */
function refreshAllTriggers() {
    setDailyTriggers();
}

/**
 * DEBUG: Fetch latest 3 posts from Facebook
 */
function debugFetchLatestFbPosts() {
    const PAGE_ID = '971418716059046';
    const props = PropertiesService.getScriptProperties();
    const token = props.getProperty('FB_ACCESS_TOKEN');

    if (!token) return console.log('No token');

    const url = `https://graph.facebook.com/v19.0/${PAGE_ID}/posts?fields=created_time,message,id&limit=3&access_token=${token}`;
    const res = UrlFetchApp.fetch(url, { muteHttpExceptions: true });
    console.log(res.getContentText());
}

/**
 * DEBUG: List all active triggers
 */
function debugListTriggers() {
    const triggers = ScriptApp.getProjectTriggers();
    const list = triggers.map(t => ({
        handler: t.getHandlerFunction(),
        eventType: t.getEventType().toString(),
        id: t.getUniqueId()
    }));
    console.log(JSON.stringify(list, null, 2));
}
// force push
