/***************
 * Main.gs
 * 役割:
 *  - onOpen(): メニュー追加
 *  - setDailyTriggers(): 毎日自動実行トリガー設定 (Snapshot, UpdateSongs)
 *  - setFridayTrigger(): 金曜朝の自動ランキング設定
 *  - autoGenerateFridayRanking(): 金曜朝の全自動処理（ランキング作成 + 通知）
 ***************/

function onOpen() {
    const ui = SpreadsheetApp.getUi();
    ui.createMenu('🎬 ランキング管理')
        .addItem('1. 統計を記録 (snapshotStats)', 'snapshotStats')
        .addItem('2. 新曲を探索 (updateSongs)', 'updateSongs')
        .addItem('   └ VannDaのみ再探査', 'updateVannDaOnly')
        .addItem('   └ SONGSシートを新着順にソート', 'manualSortSongs')
        .addSeparator()
        .addItem('3. Dailyランキング作成', 'autoGenerateDailyRanking')
        .addItem('   └ Facebookへ投稿', 'autoPostDailyRankingToFacebook')
        .addItem('4. Weeklyランキング作成', 'autoGenerateWeeklyRanking')
        .addItem('5. 脚本生成 (buildMcScript)', 'buildMcScript')
        .addItem('6. 日報をDriveに保存', 'generateAndSaveDailyReport')
        .addSeparator()
        .addItem('A1. AIインサイトのみ補完 (修復)', 'repairDailyAiInsights')
        .addSeparator()
        .addItem('⏰ タイマー(トリガー)をすべて初期化', 'refreshAllTriggers')
        .addItem('⚙️ API使用量を手動リセット', 'resetApiUsage')
        .addSeparator()
        .addItem('🔍 Geminiモデル診断', 'debugGeminiModels')
        .addSeparator()
        .addSubMenu(ui.createMenu('管理/バックアップ')
            .addItem('ランキングをアーカイブ', 'archiveRankings')
            .addItem('脚本をアーカイブ', 'archiveMcScript')
            .addItem('SNAPSHOTをアーカイブ', 'archiveSnapshot')
            .addSeparator()
            .addItem('SNAPSHOTの重複を清掃', 'cleanupSnapshotDuplicates')
            .addItem('SONGSの重複を清掃', 'cleanupDuplicateSongs')
            .addItem('アーティスト・曲名のクリーンアップ', 'cleanupNaming')
            .addItem('AI命名正規化テストを実行', 'testNamingNormalizationOnSheet')
            .addItem('Gemini API 診断を実行', 'debugGeminiModels')
            .addSeparator()
            .addItem('アーティストURLの有効性を確認', 'checkArtistUrls')
            .addItem('URLからChannel IDを同期/修正', 'syncChannelIds')
        )
        .addToUi();
}

/**
 * 毎日自動実行するためのトリガーを設定
 */
function setDailyTriggers() {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const triggers = ScriptApp.getProjectTriggers();

    // 既存のすべてのトリガーを削除して重複を防ぐ（完全にクリーンにする）
    triggers.forEach(t => {
        ScriptApp.deleteTrigger(t);
    });

    // 毎日 深夜0時にAPI使用量をリセット (→ 最初の使用時リセットに変更)
    // ScriptApp.newTrigger('resetApiUsage')
    //    .timeBased().atHour(0).nearMinute(1).everyDays(1).create();

    // 毎日 新曲を探索 (18時台のリリースを捕捉)
    ScriptApp.newTrigger('updateSongs')
        .timeBased().atHour(18).nearMinute(30).everyDays(1).create();

    // 毎日 統計を取得 (反映直前の最新数値を確保)
    ScriptApp.newTrigger('snapshotStats')
        .timeBased().atHour(19).nearMinute(15).everyDays(1).create();

    // 毎日 デイリーランキングを生成 (20時)
    ScriptApp.newTrigger('autoGenerateDailyRanking')
        .timeBased().atHour(20).everyDays(1).create();

    // 毎日 Facebookへの自動投稿 (20時30分)
    // ※ ランキング生成の30分後に独立して実行し、タイムアウトを防ぎます
    ScriptApp.newTrigger('autoPostDailyRankingToFacebook')
        .timeBased().atHour(20).nearMinute(30).everyDays(1).create();

    // 金曜日 朝7時にウィークリーランキング生成
    ScriptApp.newTrigger('autoGenerateWeeklyRanking')
        .timeBased()
        .onWeekDay(ScriptApp.WeekDay.FRIDAY)
        .atHour(7)
        .create();

    // 毎週土曜日にアーカイブを実行
    ScriptApp.newTrigger('archiveRankings')
        .timeBased().onWeekDay(ScriptApp.WeekDay.SATURDAY).atHour(5).create();

    ScriptApp.newTrigger('archiveMcScript')
        .timeBased().onWeekDay(ScriptApp.WeekDay.SATURDAY).atHour(5).create();

    ScriptApp.newTrigger('archiveSnapshot')
        .timeBased().onWeekDay(ScriptApp.WeekDay.SATURDAY).atHour(6).create();

    // 編集時トリガー（Artistsシートの自動入力）
    ScriptApp.newTrigger('onEditHandler')
        .forSpreadsheet(ss)
        .onEdit()
        .create();

    try {
        SpreadsheetApp.getUi().alert('設定完了: デイリー処理、金曜ランキング、および「Artistsシートの自動入力」をセットアップしました。');
    } catch (e) {
        Logger.log('設定完了: デイリー処理、金曜ランキング、および「Artistsシートの自動入力」をセットアップしました。 (UIが利用できないためログのみ記録)');
    }
}

/**
 * 編集時イベントハンドラ (Installable Trigger)
 */
function onEditHandler(e) {
    if (!e) return;
    const range = e.range;
    const sheet = range.getSheet();

    // ArtistsシートかつB列(YouTube URL)が編集された場合
    if (sheet.getName() !== CFG.SHEET_ARTISTS) return;
    if (range.getColumn() !== 2 || range.getRow() <= 1) return;

    const url = range.getValue().toString().trim();
    if (!url) return;

    try {
        let channelId = "";
        let handle = "";

        if (url.includes("/channel/")) {
            channelId = url.split("/channel/")[1].split("/")[0].split("?")[0];
        } else if (url.includes("/@")) {
            handle = url.split("/@")[1].split("/")[0].split("?")[0];
        } else if (url.includes("/c/")) {
            handle = url.split("/c/")[1].split("/")[0].split("?")[0];
        }

        const params = {};
        if (channelId) {
            params.id = channelId;
        } else if (handle) {
            params.forHandle = handle;
        } else {
            return;
        }

        const res = YouTube.Channels.list('snippet,statistics', params);
        updateApiUsage_('YouTube', 1); // 1 unit
        if (!res.items || res.items.length === 0) return;
        const item = res.items[0];

        const row = range.getRow();
        const realId = item.id;

        // 重複チェック (C列: Channel ID)
        const allIds = sheet.getRange(1, 3, sheet.getLastRow(), 1).getValues().map(r => r[0].toString().trim());
        const duplicateRowIndex = allIds.findIndex((id, idx) => id === realId && (idx + 1) !== row);

        if (duplicateRowIndex !== -1) {
            const duplicateRow = duplicateRowIndex + 1;
            const duplicateName = sheet.getRange(duplicateRow, 1).getValue();
            SpreadsheetApp.getUi().alert(`⚠️ 重複登録エラー\n\nこのチャンネルは既に登録されています。\nアーティスト: ${duplicateName}\n(行番号: ${duplicateRow})\n\n入力した行を削除します。`);
            sheet.deleteRow(row);
            return;
        }

        const name = cleanArtistName(item.snippet.title);
        const subs = item.statistics.subscriberCount;
        const desc = item.snippet.description || "";

        // A: Name(1), C: ID(3), D: Subs(4)
        sheet.getRange(row, 1).setValue(name);
        sheet.getRange(row, 3).setValue(realId);
        sheet.getRange(row, 4).setValue(subs);

        // Facebookリンクの自動取得を試行 [NEW]
        let fbUrl = getFacebookFromSnippet_(desc);
        if (!fbUrl) {
            fbUrl = getFacebookFromHtml_(realId);
        }
        if (fbUrl) {
            sheet.getRange(row, 5).setValue(fbUrl);
        }

    } catch (err) {
        console.error("onEditHandler Error: " + err);
    }
}

/**
 * 説明欄からFacebookリンクを抽出
 */
function getFacebookFromSnippet_(desc) {
    return extractFacebookFromText_(desc);
}

/**
 * チャンネルページHTMLからFacebookリンクを抽出 (ベストエフォート)
 */
function getFacebookFromHtml_(channelId) {
    const urls = [
        `https://www.youtube.com/channel/${channelId}`,
        `https://www.youtube.com/channel/${channelId}/about`
    ];

    for (const url of urls) {
        try {
            const html = UrlFetchApp.fetch(url, { muteHttpExceptions: true }).getContentText();
            const fbUrl = extractFacebookFromText_(html);
            if (fbUrl) {
                console.log(`Found Facebook link at: ${url}`);
                return fbUrl;
            }
        } catch (e) {
            console.error(`Error fetching ${url}: ${e}`);
        }
    }
    return null;
}

/**
 * テキスト中からFacebookリンクを抽出してデコードする (超強力版)
 */
function extractFacebookFromText_(text) {
    if (!text) return null;

    // 1. 全文から facebook.com という文字列をすべて探す
    const target = "facebook.com";
    let index = text.indexOf(target);
    const foundUrls = new Set();

    while (index !== -1) {
        // 前後150文字程度をバッファとして取得
        const start = Math.max(0, index - 150);
        const end = Math.min(text.length, index + 150);
        let snippet = text.substring(start, end);

        // YouTubeのJSONエスケープ (\/, \n, \", \u0026, x3d ...) を徹底的に解除
        snippet = snippet
            .replace(/\\r|\\n/g, ' ')
            .replace(/\\\\/g, '\\')      // \\ -> \
            .replace(/\\\//g, '/')       // \/ -> /
            .replace(/\\"/g, '"')        // \" -> "
            .replace(/x22/g, '"')        // x22 -> "
            .replace(/u0022/g, '"')
            .replace(/x3d/g, '=')        // x3d -> =
            .replace(/u003d/g, '=')
            .replace(/u0026/g, '&')
            .replace(/x26/g, '&');

        // デコードを試みる (2回繰り返して多重エンコードに対応)
        try { snippet = decodeURIComponent(snippet); } catch (e) { }
        try { snippet = decodeURIComponent(snippet); } catch (e) { }

        // 改めて Facebook のフルURLを正規表現で探す
        const finalMatch = snippet.match(/https?:\/\/(?:www\.|web\.|m\.)?facebook\.com\/[^ \t\n\r"','\\<>{}|\[\]?#]+/);
        if (finalMatch) {
            const url = cleanFacebookUrl_(finalMatch[0]);
            if (url && !url.includes('facebook.com/tr') && !url.includes('facebook.com/sharer')) {
                foundUrls.add(url);
            }
        }

        index = text.indexOf(target, index + 1);
    }

    // 見つかった中から最もそれらしいものを返す
    const results = Array.from(foundUrls);
    if (results.length === 0) return null;

    // profile.php ではないリンクがあればそれを優先（より具体的である可能性が高いため）
    const specific = results.find(u => !u.includes('profile.php'));
    return specific || results[0];
}

/**
 * Facebook URLを整形（profile.php?id= 対応）
 */
function cleanFacebookUrl_(url) {
    if (!url) return null;

    // profile.php 形式の場合
    if (url.includes('profile.php')) {
        const idMatch = url.match(/[?&]id=([^&"'\s\n\r#]+)/);
        if (idMatch) {
            return `https://www.facebook.com/profile.php?id=${idMatch[1]}`;
        }
    }

    // 通常のバニティURL形式
    return url.split(/[?#]/)[0].replace(/\/$/, '');
}

/**
 * 既存のArtistsシートをスキャンし、Facebookリンクが空の箇所を補完する
 */
function backfillFacebookLinks() {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(CFG.SHEET_ARTISTS);
    if (!sheet) return;

    const data = sheet.getDataRange().getValues();
    let count = 0;

    for (let i = 1; i < data.length; i++) {
        const row = i + 1;
        const channelId = data[i][2]; // C列
        const existingFb = data[i][4]; // E列

        if (channelId && !existingFb) {
            try {
                // Snippet (説明欄) から取得
                const res = YouTube.Channels.list('snippet', { id: channelId });
                let fbUrl = null;

                if (res.items && res.items.length > 0) {
                    fbUrl = getFacebookFromSnippet_(res.items[0].snippet.description);
                }

                // なければHTMLから取得
                if (!fbUrl) {
                    fbUrl = getFacebookFromHtml_(channelId);
                }

                if (fbUrl) {
                    sheet.getRange(row, 5).setValue(fbUrl);
                    count++;
                }
            } catch (e) {
                console.error(`Error backfilling ${channelId}: ${e}`);
            }
            Utilities.sleep(200); // 連続リクエストを少し控える
        }
    }

    SpreadsheetApp.getUi().alert(`完了: ${count} 件のアーティストにFacebookリンクを補完しました。`);
}

/**
 * Telegram通知の設定
 */
const TG_CONFIG = {
    BOT_TOKEN: '8582165720:AAG2bwkQ0GKC_ke3Po_ReR1KwuupZe1iOH8',
    CHAT_ID: '7506480434'
};

/**
 * テスト用: Telegram通知を今すぐテスト
 */
function testTelegramNotification() {
    sendTelegramNotification_('テスト: YouTubeランキング通知テスト\n\nこのメッセージが届けば設定は完璧です！');
}

/**
 * 金曜朝に自動実行される一括処理
 */
function autoGenerateFridayRanking() {
    try {
        // 1. 週間ランキング作成 (7日間差分)
        autoGenerateWeeklyRanking();

        // 2. 通知 (Telegram)
        sendTelegramNotification_('完了: 今週のランキング(候補)が生成されました\n\n' +
            '今週のランキング候補（Top 15）の自動生成が完了しました。\n' +
            'スプレッドシートを開いて確認し、Top 10を確定させた後、脚本生成を実行してください。');

        Logger.log('Friday Auto Ranking Done.');
    } catch (e) {
        sendTelegramNotification_('エラー: YouTubeランキング自動作成中\n\nエラー内容:\n' + e.toString());
    }
}

/**
 * Telegramにメッセージを送信
 */
function sendTelegramNotification_(text) {
    if (TG_CONFIG.BOT_TOKEN === 'YOUR_BOT_TOKEN') {
        Logger.log('Telegram Token not set. Notification skipped.');
        return;
    }

    try {
        logToSheet_(text); // 画面との連携用にシートへも記録
    } catch (e) {
        console.error("Failed to log to sheet:", e);
    }

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const url = `https://api.telegram.org/bot${TG_CONFIG.BOT_TOKEN}/sendMessage`;
    const fullText = text + `\n\n▼ スプレッドシート\n${ss.getUrl()}`;

    const payload = {
        method: 'post',
        contentType: 'application/json',
        payload: JSON.stringify({
            chat_id: TG_CONFIG.CHAT_ID,
            text: fullText
        })
    };

    UrlFetchApp.fetch(url, payload);
}

/**
 * Facebook への自動投稿を一括実行 (Parallelized for GAS 6-min limit)
 */
function autoPostToFacebook() {
    sendTelegramNotification_('【実行】Facebook自動投稿を開始します (並列処理版)');
    const PAGE_ID = '971418716059046';
    const props = PropertiesService.getScriptProperties();
    const token = props.getProperty('FB_ACCESS_TOKEN');

    if (!token) {
        logToSheet_('FB_POST: エラー - アクセストークンが未設定です');
        sendTelegramNotification_('エラー: FB投稿失敗: アクセストークンが未設定です。');
        return;
    }

    // 重複投稿防止ロック (10分間)
    const lockKey = 'FB_POST_LOCK';
    const now = new Date().getTime();
    const lastRun = Number(props.getProperty(lockKey) || 0);
    if (now - lastRun < 10 * 60 * 1000) {
        logToSheet_('FB_POST: 10分以内に実行済みのためスキップします (Lock active)');
        return;
    }
    props.setProperty(lockKey, String(now));

    try {
        const data = getRankingData_();
        if (!data || !data.ranking || data.ranking.length === 0) {
            throw new Error('Ranking data is empty');
        }
        logToSheet_(`Ranking data loaded: ${data.ranking.length} items`);

        const ranking = data.ranking;
        const baseUrl = 'https://heat-kh.vercel.app/api/og/ranking';
        const dateStr = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy.MM.dd');

        // 1. OG画像URLの生成 (4枚分)
        const ogUrls = [];
        
        // 1.1 Rank 1
        const r1 = ranking[0];
        const r1Url = [
            `${baseUrl}?template=rank1`,
            `rank=1`,
            `artist=${encodeURIComponent(r1.artist)}`,
            `title=${encodeURIComponent(r1.title)}`,
            `heatPoint=${Math.round(r1.heatScore)}`,
            `growth=${r1.growth}`,
            `views=${r1.views}`,
            `change=${r1.rankChange}`,
            `engagement=${r1.engagement}`,
            `insight=${encodeURIComponent(r1.shortInsight || '')}`,
            `date=${encodeURIComponent(dateStr)}`
        ].join('&');
        ogUrls.push(r1Url);

        // 1.2 Multi images (2-4, 5-7, 8-10)
        for (let i = 0; i < 3; i++) {
            const start = 1 + (i * 3);
            const items = ranking.slice(start, start + 3).map(x => ({
                rank: x.rank,
                artist: x.artist,
                title: x.title,
                change: x.rankChange === 'NEW' ? 'NEW' : (x.rankChange > 0 ? '+' + x.rankChange : x.rankChange.toString())
            }));
            if (items.length > 0) {
                const multiUrl = `${baseUrl}?template=multi&items=${encodeURIComponent(JSON.stringify(items))}&date=${encodeURIComponent(dateStr)}`;
                ogUrls.push(multiUrl);
            }
        }

        // 2. 画像の並列取得 (Vercel)
        logToSheet_(`FB_POST: OG画像生成(Vercel) ${ogUrls.length}枚を並列リクエスト中...`);
        const ogRequests = ogUrls.map(url => ({ url: url, muteHttpExceptions: true }));
        const ogResponses = UrlFetchApp.fetchAll(ogRequests);
        
        const blobs = [];
        ogResponses.forEach((res, i) => {
            if (res.getResponseCode() !== 200) {
                throw new Error(`OG Image Generation Failed (${res.getResponseCode()}): ${res.getContentText().substring(0, 100)}`);
            }
            blobs.push(res.getBlob());
        });
        logToSheet_('FB_POST: OG画像生成完了');

        // 3. Facebook への並列アップロード (未公開設定)
        logToSheet_('FB_POST: Facebookへの画像アップロードを並列実行中...');
        const fbPhotoUrl = `https://graph.facebook.com/v19.0/${PAGE_ID}/photos`;
        const uploadRequests = blobs.map(blob => ({
            url: fbPhotoUrl,
            method: 'post',
            payload: {
                source: blob,
                published: 'false',
                access_token: token
            },
            muteHttpExceptions: true
        }));
        
        const uploadResponses = UrlFetchApp.fetchAll(uploadRequests);
        const photoIds = [];
        uploadResponses.forEach((res, i) => {
            const content = res.getContentText();
            if (res.getResponseCode() !== 200) {
                throw new Error(`FB Photo Upload Failed (${res.getResponseCode()}): ${content}`);
            }
            photoIds.push(JSON.parse(content).id);
        });
        logToSheet_(`FB_POST: 画像アップロード完了 (${photoIds.length}枚)`);

        // 4. フィード投稿の作成
        const r1MessageChange = r1.rankChange === 'NEW' ? 'NEW ENTRY' : (r1.rankChange > 0 ? '+' + r1.rankChange : (r1.rankChange === 0 ? 'STAY' : r1.rankChange));
        let insightText = '';
        if (r1.aiInsight && r1.aiInsight !== '-') {
            insightText = `\n\nHEAT AI Insight:\n${r1.aiInsight}`;
        }

        const message = `HEAT (BETA) - Cambodia Daily Ranking\n${dateStr}\n\n#1 ${r1.artist} – ${r1.title}\n${Math.round(r1.heatScore)} HEAT POINT (${r1MessageChange})${insightText}\n\nFull Top 20 ranking in the first comment`;

        const feedUrl = `https://graph.facebook.com/v19.0/${PAGE_ID}/feed`;
        const feedPayload = {
            message: message,
            access_token: token
        };

        // 画像の並び順を逆にする（1位から表示されるように調整）
        const reversedPhotoIds = [...photoIds].reverse();
        reversedPhotoIds.forEach((id, i) => {
            feedPayload[`attached_media[${i}]`] = JSON.stringify({ media_fbid: id });
        });

        logToSheet_('FB_POST: フィード投稿を送信中...');
        const feedRes = UrlFetchApp.fetch(feedUrl, {
            method: 'post',
            payload: feedPayload,
            muteHttpExceptions: true
        });
        
        if (feedRes.getResponseCode() !== 200) {
            throw new Error(`Facebook Feed Post Error (${feedRes.getResponseCode()}): ${feedRes.getContentText()}`);
        }

        logToSheet_(`FB_POST: フィード投稿成功!`);
        const postResult = JSON.parse(feedRes.getContentText());
        const rawPostId = postResult.id;
        
        // New Page Experience では PAGEID_POSTID の形式が必要な場合がある
        let finalPostId = rawPostId;
        if (!finalPostId.includes('_')) {
            finalPostId = `${PAGE_ID}_${rawPostId}`;
        }

        // 5. トップコメントの追加
        const commentUrl = `https://graph.facebook.com/v19.0/${finalPostId}/comments`;
        const commentPayload = {
            message: 'Full Top 20:\nhttps://heat-kh.vercel.app/\nUpdated daily.',
            access_token: token
        };

        let commentRes = UrlFetchApp.fetch(commentUrl, {
            method: 'post',
            payload: commentPayload,
            muteHttpExceptions: true
        });

        if (commentRes.getResponseCode() !== 200 && finalPostId !== rawPostId) {
            const retryUrl = `https://graph.facebook.com/v19.0/${rawPostId}/comments`;
            commentRes = UrlFetchApp.fetch(retryUrl, {
                method: 'post',
                payload: commentPayload,
                muteHttpExceptions: true
            });
        }

        if (commentRes.getResponseCode() !== 200) {
            throw new Error(`Facebook Comment Error (${commentRes.getResponseCode()}): ${commentRes.getContentText()}`);
        }

        logToSheet_(`FB_POST: 全工程完了`);
        sendTelegramNotification_(`【成功】Facebook自動投稿完了(高速版)\n日付: ${dateStr}\n#1: ${r1.artist}`);

        // 今後は手動（AI）による詳細な日報へ移行するため、ここでの自動生成は停止します


    } catch (e) {
        console.error(e);
        let errorMsg = e.message;
        if (e.message && e.message.includes('code 403')) {
            errorMsg = "Facebook permission error (403). The token might be missing scopes.";
        }
        sendTelegramNotification_(`【エラー】Facebook自動投稿に失敗しました。\nエラー: ${errorMsg}`);
    }
}

/**
 * Facebook アクセストークンをスクリプトプロパティに設定する（一度だけ実行してください）
 */
function setupFbToken(token) {
    if (!token) {
        console.error('エラー: トークンを指定してください。');
        return;
    }
    PropertiesService.getScriptProperties().setProperty('FB_ACCESS_TOKEN', token);

    try {
        SpreadsheetApp.getUi().alert('Facebookトークンの設定が完了しました。');
    } catch (e) {
        Logger.log('Facebookトークンの設定が完了しました。 (UIが利用できないためログのみ記録)');
    }
}

/**
 * FBへ写真をアップロード（未公開状態）
 */
function uploadPhotoToFb_(imgUrl, pageId, token) {
    const imgBlob = UrlFetchApp.fetch(imgUrl).getBlob();
    const url = `https://graph.facebook.com/v19.0/${pageId}/photos`;
    const payload = {
        source: imgBlob,
        published: 'false',
        access_token: token
    };

    const res = UrlFetchApp.fetch(url, {
        method: 'post',
        payload: payload
    });

    return JSON.parse(res.getContentText()).id;
}


function doPost(e) {
    return doGet(e);
}

function doGet(e) {
    try {
        let action = e && e.parameter && e.parameter.action;
        if (action) action = action.toString().trim().toLowerCase();
        let content = e && e.parameter && e.parameter.content;

        // POST data support
        if (!action && e && e.postData && e.postData.contents) {
            try {
                const postData = JSON.parse(e.postData.contents);
                action = postData.action;
                content = postData.content;
            } catch (err) {
                // Fallback or ignore
            }
        }

        if (action === 'stats') {
            const stats = getStatsData_();
            return ContentService.createTextOutput(JSON.stringify({ stats }))
                .setMimeType(ContentService.MimeType.JSON);
        }

        if (action === 'refresh_triggers') {
            setDailyTriggers();
            return ContentService.createTextOutput(JSON.stringify({ success: true, message: 'Triggers refreshed.' }))
                .setMimeType(ContentService.MimeType.JSON);
        }

        if (action === 'logs') {
            const ss = SpreadsheetApp.getActiveSpreadsheet();
            const shLog = ss.getSheetByName('DEBUG_LOG');
            let logs = [];
            if (shLog) {
                logs = shLog.getDataRange().getValues();
            }
            return ContentService.createTextOutput(JSON.stringify({ logs }))
                .setMimeType(ContentService.MimeType.JSON);
        }

        if (action === 'usage' || action === 'sys_usage' || action === 'sys_usage_stats') {
            const ss = SpreadsheetApp.getActiveSpreadsheet();
            const shUsage = ss.getSheetByName('SYS_USAGE');
            const usage = [];
            if (shUsage) {
                const data = shUsage.getDataRange().getValues();
                // Skip header and convert to objects
                for (let i = 1; i < data.length; i++) {
                    usage.push({
                        service: data[i][0],
                        current: data[i][1],
                        max: data[i][2],
                        tokenCount: data[i][3],
                        lastReset: data[i][4]
                    });
                }
            }
            return ContentService.createTextOutput(JSON.stringify({ usage }))
                .setMimeType(ContentService.MimeType.JSON);
        }

        if (action === 'save_report') {
            const content = e && e.parameter && e.parameter.content;
            const result = generateAndSaveDailyReport(content);
            return ContentService.createTextOutput(JSON.stringify({ 
                success: true, 
                url: result.url,
                fileName: result.fileName 
            }))
            .setMimeType(ContentService.MimeType.JSON);
        }

        if (action === 'post_fb') {
            try {
                autoPostToFacebook();
                return ContentService.createTextOutput(JSON.stringify({ success: true, message: 'FB post triggered.' }))
                    .setMimeType(ContentService.MimeType.JSON);
            } catch (fbErr) {
                return ContentService.createTextOutput(JSON.stringify({ success: false, error: fbErr.toString() }))
                    .setMimeType(ContentService.MimeType.JSON);
            }
        }

        const data = getRankingData_();
        const output = JSON.stringify(data);
        return ContentService.createTextOutput(output)
            .setMimeType(ContentService.MimeType.JSON);
    } catch (err) {
        return ContentService.createTextOutput(JSON.stringify({ error: err.toString() }))
            .setMimeType(ContentService.MimeType.JSON);
    }
}

/**
 * 統計情報のみを算出する関数
 */
function getStatsData_() {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const stats = {
        totalArtists: 0,
        totalProductions: 0,
        totalSongs: 0,
        newSongs: 0,
        heatGrowth: 0,
        heatTrend: []
    };

    const shArt = ss.getSheetByName('Artists');
    if (shArt) {
        const artValues = shArt.getDataRange().getValues();
        for (let i = 1; i < artValues.length; i++) {
            const name = String(artValues[i][0] || '').trim();
            if (!name) continue;

            const role = String(artValues[i][5] || '').trim().toUpperCase();
            if (role === 'P') {
                stats.totalProductions++;
            } else {
                stats.totalArtists++;
            }
        }
    }

    const shSongs = ss.getSheetByName('SONGS');
    const shSongsLong = ss.getSheetByName('SONGS_LONG');
    
    if (shSongs) {
        const songValues = shSongs.getDataRange().getValues();
        stats.totalSongs += Math.max(0, songValues.length - 1);
        
        const now = new Date();
        const oneDayAgo = now.getTime() - (24 * 60 * 60 * 1000);
        
        for (let i = 1; i < songValues.length; i++) {
            const pubDate = new Date(songValues[i][3]); 
            if (!isNaN(pubDate.getTime()) && pubDate.getTime() > oneDayAgo) {
                stats.newSongs++;
            }
        }
    }

    if (shSongsLong) {
        const songLongValues = shSongsLong.getDataRange().getValues();
        stats.totalSongs += Math.max(0, songLongValues.length - 1);
    }

    // HEAT Metrics calculation from SNAPSHOT
    try {
        const shSnap = ss.getSheetByName('SNAPSHOT');
        if (shSnap) {
            const snapData = shSnap.getDataRange().getValues();
            const tz = Session.getScriptTimeZone();
            
            // date -> totalViews
            const dateMap = {};
            for (let i = 1; i < snapData.length; i++) {
                const row = snapData[i];
                if (!row[0] || !row[2]) continue;
                // toDateKey_ は Snapshot.gs に定義されています
                const dateKey = toDateKey_(row[0], tz);
                const views = Number(row[2] || 0);
                dateMap[dateKey] = (dateMap[dateKey] || 0) + views;
            }

            const sortedDates = Object.keys(dateMap).sort();
            if (sortedDates.length >= 2) {
                const minD = new Date(sortedDates[0]);
                const maxD = new Date(sortedDates[sortedDates.length - 1]);
                
                // 1. Create a continuous daily views array (filling gaps)
                const fullDailyViews = [];
                let lastKnownV = 0;
                const current = new Date(minD);
                while (current <= maxD) {
                    const key = toDateKey_(current, tz);
                    if (dateMap[key] !== undefined) {
                        lastKnownV = dateMap[key];
                    }
                    fullDailyViews.push(lastKnownV);
                    current.setDate(current.getDate() + 1);
                }

                // 2. Calculate daily deltas
                const allDailyDeltas = [];
                for (let i = 1; i < fullDailyViews.length; i++) {
                    allDailyDeltas.push(Math.max(0, fullDailyViews[i] - fullDailyViews[i-1]));
                }

                if (allDailyDeltas.length >= 7) {
                    // 3. Aggregate into weekly buckets (8 weeks for "2 months")
                    const weeklyTrend = [];
                    for (let i = allDailyDeltas.length; i >= 7; i -= 7) {
                        const weekSum = allDailyDeltas.slice(i - 7, i).reduce((a, b) => a + b, 0);
                        weeklyTrend.unshift(weekSum);
                        if (weeklyTrend.length >= 8) break; 
                    }
                    stats.heatTrend = weeklyTrend;

                    // 4. Growth calculation (Current week vs Previous 7 days)
                    const thisWeek = allDailyDeltas.slice(-7).reduce((a, b) => a + b, 0);
                    const lastWeek = allDailyDeltas.slice(-14, -7).reduce((a, b) => a + b, 0);
                    if (lastWeek > 0) {
                        stats.heatGrowth = Number(((thisWeek - lastWeek) / lastWeek * 100).toFixed(1));
                    }
                }
            }
        }
    } catch (e) {
        console.error("Error calculating heat statistics:", e);
    }

    return stats;
}

/**
 * RANKINGシートからデータを抽出してオブジェクト形式で返す
 */
function getRankingData_() {
    const ss = SpreadsheetApp.getActiveSpreadsheet();

    // --- 統計情報の算出 ---
    const stats = getStatsData_();
    // -------------------------

    const shDaily = ss.getSheetByName('RANKING_DAILY');
    const shLong = ss.getSheetByName('RANKING_LONG');
    
    const tz = Session.getScriptTimeZone();
    const last7Dates = [];
    for (let i = 6; i >= 0; i--) {
        const d = new Date();
        d.setDate(d.getDate() - i);
        last7Dates.push(toDateKey_(d, tz));
    }
    const rankHistoryMap = getRankHistoryMap_(ss, last7Dates, tz);

    const ranking = shDaily ? parseRankingSheet_(shDaily, rankHistoryMap, last7Dates) : [];
    const rankingLong = shLong ? parseRankingSheet_(shLong, rankHistoryMap, last7Dates) : [];

    return {
        updatedAt: new Date().toISOString(),
        stats,
        ranking,
        rankingLong
    };
}

/**
 * 指定したランキングシートをパースしてオブジェクトの配列で返す
 */
/**
 * 指定したランキングシートをパースしてオブジェクトの配列で返す
 */
function parseRankingSheet_(sh, rankHistoryMap, last7Dates) {
    const values = sh.getDataRange().getValues();
    if (values.length < 2) return [];

    const headers = values[0];
    const data = [];

    // ヘッダーのインデックスを特定するためのヘルパー
    const findHeader = (names) => {
        for (let name of names) {
            const i = headers.findIndex(h => String(h || '').trim().toLowerCase() === name.toLowerCase());
            if (i !== -1) return i;
        }
        return -1;
    };

    const idx = {
        rank: findHeader(['順位', 'Rank', '順位(1d)', '順位(7d)']),
        prevRank: findHeader(['PrevRank', '1日前', '7日前']),
        artist: findHeader(['アーティスト', 'Artist']),
        title: findHeader(['曲名', 'Title']),
        publishedAt: findHeader(['公開日', 'Published']),
        heatScore: findHeader(['Heatスコア', 'HeatScore', 'Score']),
        aiScore: findHeader(['AIスコア', 'AIScore']),
        aiInsight: findHeader(['AIインサイト', 'AIInsight', 'Insight']),
        shortInsight: findHeader(['shortInsight', 'ShortInsight']),
        growth: findHeader(['成長率(%)', 'Growth']),
        engagement: findHeader(['反応率', 'Engagement']),
        views: findHeader(['増加数(1d)', '増加数(7d)', 'Views', 'Views(1d)']),
        totalViews: findHeader(['現在再生数', 'TotalViews']),
        videoId: findHeader(['videoId', 'VideoID', 'YouTube', 'URL', '動画']),
        history: findHeader(['historyRaw', 'History', '履歴']),
        rankChange: -1 // 後で計算
    };

    for (let i = 1; i < values.length; i++) {
        const row = values[i];
        const videoIdValue = (() => {
            let v = String(row[idx.videoId] || '').trim();
            if (!v) return '';
            if (v.includes('youtu.be/')) v = v.split('youtu.be/')[1].split('?')[0];
            if (v.includes('watch?v=')) v = v.split('watch?v=')[1].split('&')[0];
            return v;
        })();

        const item = {
            rank: parseInt(row[idx.rank]) || i,
            prevRank: row[idx.prevRank] === '-' ? 100 : (parseInt(row[idx.prevRank]) || 100),
            artist: String(row[idx.artist] || ''),
            title: String(row[idx.title] || ''),
            publishedAt: row[idx.publishedAt],
            heatScore: parseFloat(row[idx.heatScore]) || 0,
            aiScore: row[idx.aiScore] === '-' ? 0 : (parseFloat(row[idx.aiScore]) || 0),
            aiInsight: String(row[idx.aiInsight] || '-'),
            shortInsight: String(row[idx.shortInsight] || '-'),
            growth: row[idx.growth],
            engagement: row[idx.engagement],
            views: row[idx.views],
            totalViews: row[idx.totalViews],
            videoId: videoIdValue,
            history: (() => {
                // historyRaw の再生数推移ではなく、順位推移を優先
                if (rankHistoryMap && last7Dates) {
                    return last7Dates.map(date => rankHistoryMap[date] ? (rankHistoryMap[date][videoIdValue] || 100) : 100);
                }

                const raw = String(row[idx.history] || '');
                if (!raw) return [];
                // '123;456;789' または '123,456,789' の形式を想定
                return raw.split(/[;,]/).map(v => parseInt(v.trim())).filter(v => !isNaN(v));
            })()
        };

        // rankChange の計算
        if (item.prevRank === 100) {
            item.rankChange = 'NEW';
        } else {
            item.rankChange = item.prevRank - item.rank;
        }

        data.push(item);
    }
    return data;
}

/**
 * クォータを消費せずにYouTube URLの有効性をチェック
 */
function checkArtistUrls() {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(CFG.SHEET_ARTISTS);
    if (!sheet) {
        SpreadsheetApp.getUi().alert('エラー: Artists シートが見つかりません。');
        return;
    }

    const lastRow = sheet.getLastRow();
    if (lastRow <= 1) {
        SpreadsheetApp.getUi().alert('チェック対象のアーティストがいません。');
        return;
    }

    const data = sheet.getRange(2, 1, lastRow - 1, 3).getValues(); // A:Name, B:URL, C:ID
    const results = [];

    // UI進捗表示用のトースト
    ss.toast('URLチェックを開始します（約' + data.length + '件）...', 'チェック中', -1);

    for (let i = 0; i < data.length; i++) {
        const name = data[i][0] || 'Unknown';
        const url = data[i][1];
        const channelId = data[i][2];
        const row = i + 2;

        if (!url && !channelId) {
            results.push(`行 ${row}: ${name} - URLとIDの両方が空です`);
            continue;
        }

        const targetUrl = url || `https://www.youtube.com/channel/${channelId}`;

        try {
            // クォータを使わない HTTP HEAD/GET リクエスト
            const response = UrlFetchApp.fetch(targetUrl, {
                muteHttpExceptions: true,
                followRedirects: true,
                headers: { "Accept-Language": "ja,en-US;q=0.9,en;q=0.8" }
            });
            const code = response.getResponseCode();

            // YouTubeの場合、チャンネルが存在しないと404を返す
            if (code === 404) {
                results.push(`行 ${row}: ${name} - リンク切れ (404)`);
            } else if (code !== 200) {
                results.push(`行 ${row}: ${name} - 異常応答 (${code})`);
            }
        } catch (e) {
            results.push(`行 ${row}: ${name} - 接続失敗: ${e.message}`);
        }

        // 10件ごとに通知
        if ((i + 1) % 10 === 0) {
            ss.toast(`${i + 1} / ${data.length} 件完了...`, 'チェック中');
        }
        Utilities.sleep(100); // サーバー負荷軽減のため僅かに待機
    }

    ss.toast('チェックが完了しました。', '完了', 3);

    if (results.length === 0) {
        SpreadsheetApp.getUi().alert('【合格】すべて有効\n\n全アーティストのURLが正常に応答しました。取りこぼしの原因はURL自体ではなく、IDの未記入か同期の問題である可能性が高いです。');
    } else {
        const msg = '以下のアーティスト（' + results.length + '件）に問題が見つかりました:\n' +
            '------------------------------------------\n' +
            results.join('\n') +
            '\n------------------------------------------\n' +
            'これらはYouTubeから情報を取得できないため、反映されません。リンクを更新してください。';
        console.log(msg);

        // メッセージが長すぎる場合の考慮
        if (msg.length > 1500) {
            SpreadsheetApp.getUi().alert('多数の問題（' + results.length + '件）が見つかりました。詳細は「表示 > ログ」を確認してください。');
        } else {
            SpreadsheetApp.getUi().alert(msg);
        }
    }
}

/**
 * URLをもとにChannel ID (C列) が正しいか確認し、
 * 空欄または間違いがあればYouTubeから取得して補完・修正する
 */
function syncChannelIds() {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(CFG.SHEET_ARTISTS);
    if (!sheet) return;

    const data = sheet.getDataRange().getValues();
    const ui = SpreadsheetApp.getUi();
    const response = ui.alert('Channel ID同期', '全アーティストのURLを確認し、Channel IDを最新の状態に更新します。実行しますか？\n(1件につき1ユニットのクォータを消費します)', ui.ButtonSet.YES_NO);

    if (response !== ui.Button.YES) return;

    ss.toast('同期処理を開始します...', '実行中');
    let fixCount = 0;
    let skipCount = 0;

    for (let i = 1; i < data.length; i++) {
        const row = i + 1;
        const url = String(data[i][1] || '').trim();
        const currentId = String(data[i][2] || '').trim();

        if (!url) {
            skipCount++;
            continue;
        }

        try {
            let channelId = "";
            let handle = "";

            // URL解析
            if (url.includes("/channel/")) {
                channelId = url.split("/channel/")[1].split("/")[0].split("?")[0];
            } else if (url.includes("/@")) {
                handle = url.split("/@")[1].split("/")[0].split("?")[0];
            } else if (url.includes("/c/")) {
                handle = url.split("/c/")[1].split("/")[0].split("?")[0];
            }

            const params = {};
            if (channelId) {
                params.id = channelId;
            } else if (handle) {
                params.forHandle = handle;
            } else {
                skipCount++;
                continue; // 解析不能なURL
            }

            const res = YouTube.Channels.list('snippet,statistics', params);
            if (res.items && res.items.length > 0) {
                const item = res.items[0];
                const realId = item.id;
                const name = item.snippet.title;
                const subs = item.statistics.subscriberCount;

                // 現在のIDと異なる、または空の場合は修正
                if (realId !== currentId) {
                    sheet.getRange(row, 1).setValue(name);      // 名前も最新に
                    sheet.getRange(row, 3).setValue(realId);    // 正しいID
                    sheet.getRange(row, 4).setValue(subs);      // 登録者数
                    fixCount++;
                    console.log(`Fixed Row ${row}: ${name} (${realId})`);
                }
            } else {
                console.warn(`Row ${row}: Channel not found for URL ${url}`);
            }
        } catch (e) {
            console.error(`Row ${row} Error: ${e.message}`);
        }

        if (i % 10 === 0) {
            ss.toast(`${i} / ${data.length - 1} 件完了...`, '同期中');
        }
        Utilities.sleep(100); // 連続リクエストを控える
    }

    ss.toast('同期が完了しました。', '完了');
    ui.alert(`同期完了\n\n修正・補完: ${fixCount} 件\nスキップ/正常: ${data.length - 1 - fixCount} 件\n\nこれでChannel IDが最新のURLに基づいた正しいものになりました。`);
}

/**
 * 【設定用】新しいFacebookトークンを登録する（一度だけ実行）
 */
function updateTokenOnce() {
    // ユーザーから提供された最新のトークン、または既存の有効なトークンをセット
    const newToken = 'EAAViKaZBkCW8BQ2wfTXfLUjjh65xtdIZCxpbSbShrEDfau8peK2e2dXu3vD2fmIjcdGTZBNv3XzFgL8PLS5H8lZALrAoPQC66D91PEDCeu1FnZBxksYNUQpsZBnBVEJgpXX7DZCOXzKOgDUKnkJWwdAPYpPnvhrnJMqZBMdKZCUi4JMfl0C7Evzud52dWrpfhl02NvWPZChH1GsQdVTqaab88WVoe9';
    setupFbToken(newToken);
}

/**
 * 【設定用】タイマー（トリガー）を最新の順番に再設定する（一度だけ実行）
 */
function refreshAllTriggers() {
    setDailyTriggers();
}

/**
 * DEBUG: Fetch latest 3 posts from Facebook
 */
function debugFetchLatestFbPosts() {
    const PAGE_ID = '971418716059046';
    const props = PropertiesService.getScriptProperties();
    const token = props.getProperty('FB_ACCESS_TOKEN');

    if (!token) return console.log('No token');

    const url = `https://graph.facebook.com/v19.0/${PAGE_ID}/posts?fields=created_time,message,id&limit=3&access_token=${token}`;
    const res = UrlFetchApp.fetch(url, { muteHttpExceptions: true });
    console.log(res.getContentText());
}

/**
 * API使用量をリセットする (毎日深夜に実行、または手動)
 */
function resetApiUsage() {
    try {
        const ss = SpreadsheetApp.getActiveSpreadsheet();
        const sh = ss.getSheetByName('SYS_USAGE');
        if (!sh) return;
        
        const data = sh.getDataRange().getValues();
        const todayStr = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy/MM/dd');

        // 2行目(YouTube)と3行目(Gemini)のCurrentとTokenCountを0にリセット
        for (let i = 1; i < data.length; i++) {
            sh.getRange(i + 1, 2).setValue(0); // Current
            if (sh.getLastColumn() >= 4) {
                sh.getRange(i + 1, 4).setValue(0); // TokenCount
            }
            // Reset Date (E列)
            sh.getRange(i + 1, 5).setValue(todayStr);
        }
        logToSheet_('SYSTEM: API使用量をリセットしました');
    } catch (e) {
        console.error("Failed to reset API usage: " + e.message);
    }
}

/**
 * API使用量を記録するシステム（メモリ内キャッシュ版）
 */
let GLOBAL_USAGE = {
  'YouTube': { current: 0, tokens: 0 },
  'Gemini': { current: 0, tokens: 0 }
};

/**
 * API使用量をメモリに蓄積する（高速版）
 * @param {string} service "YouTube" | "Gemini"
 * @param {number} usedAmount 
 */
function updateApiUsage_(service, usedAmount) {
  if (GLOBAL_USAGE[service]) {
    if (service === 'YouTube') {
      GLOBAL_USAGE[service].current += usedAmount;
      // 通知ロック (1回の実行で1回のみ)
      if (GLOBAL_USAGE[service].current > 5000 && !GLOBAL_USAGE[service]._notified) {
        GLOBAL_USAGE[service]._notified = true;
        sendTelegramNotification_('【警告】YouTube APIのクォータ使用量が5000ユニットを超えました。');
      }
    } else {
      GLOBAL_USAGE[service].current += 1;
      GLOBAL_USAGE[service].tokens += usedAmount;
    }
  }
}

/**
 * 蓄積したAPI使用量をスプレッドシートに一括反映する
 */
function flushApiUsage_() {
  try {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    let sh = ss.getSheetByName('SYS_USAGE');
    const tz = Session.getScriptTimeZone();
    const todayStr = Utilities.formatDate(new Date(), tz, 'yyyy/MM/dd');

    if (!sh) {
      sh = ss.insertSheet('SYS_USAGE');
      sh.appendRow(['Service', 'Current', 'Max', 'TokenCount', 'LastReset']);
      sh.appendRow(['YouTube', 0, 10000, 0, todayStr]);
      sh.appendRow(['Gemini', 0, 1500, 0, todayStr]);
    }

    const range = sh.getDataRange();
    const data = range.getValues();
    const headers = data[0];
    const newValues = data.slice(1);

    let needsResetLog = false;

    for (let i = 0; i < newValues.length; i++) {
      const service = newValues[i][0];
      if (!GLOBAL_USAGE[service]) continue;

      // E列: LastReset 正規化比較
      let lastResetDate = "";
      if (newValues[i][4] instanceof Date) {
        lastResetDate = Utilities.formatDate(newValues[i][4], tz, 'yyyy/MM/dd');
      } else {
        lastResetDate = String(newValues[i][4] || '').trim();
      }

      if (lastResetDate !== todayStr) {
        newValues[i][1] = 0; // Current reset
        newValues[i][3] = 0; // TokenCount reset
        newValues[i][4] = todayStr; // Update date
        needsResetLog = true;
      }

      // 蓄積分を加算
      newValues[i][1] = (Number(newValues[i][1]) || 0) + GLOBAL_USAGE[service].current;
      newValues[i][3] = (Number(newValues[i][3]) || 0) + GLOBAL_USAGE[service].tokens;
      
      // 次回のためにメモリをクリア
      GLOBAL_USAGE[service].current = 0;
      GLOBAL_USAGE[service].tokens = 0;
    }

    if (needsResetLog) logToSheet_("SYSTEM: API使用量をリセットしました (Batch Reset)");
    sh.getRange(2, 1, newValues.length, headers.length).setValues(newValues);
    
  } catch (e) {
    console.error("Failed to flush API usage: " + e.message);
  }
}

/**
 * スナップショットから直近7日間の全曲の順位マップを作成する
 */
function getRankHistoryMap_(ss, last7Dates, tz) {
    try {
        const shSnap = ss.getSheetByName('SNAPSHOT');
        if (!shSnap) return {};
        const snapData = shSnap.getDataRange().getValues();
        
        // date -> [ {key, views}, ... ]
        const dateToSongs = {};
        last7Dates.forEach(d => dateToSongs[d] = []);
        
        for (let i = 1; i < snapData.length; i++) {
            const row = snapData[i];
            if (!row[0] || !row[1]) continue;
            const dateKey = toDateKey_(row[0], tz);
            if (dateToSongs[dateKey]) {
                dateToSongs[dateKey].push({
                    key: String(row[1]), // videoId
                    views: Number(row[2] || 0)
                });
            }
        }
        
        // date -> songKey -> rank
        const historyMap = {};
        Object.keys(dateToSongs).forEach(date => {
            const songs = dateToSongs[date];
            if (songs.length === 0) return;
            
            songs.sort((a, b) => b.views - a.views);
            const ranks = {};
            songs.forEach((s, idx) => {
                ranks[s.key] = idx + 1;
            });
            historyMap[date] = ranks;
        });
        
        return historyMap;
    } catch (e) {
        console.error("Error generating rank history map:", e);
        return {};
    }
}
