/***************
 * PickSongs.gs
 * 役割:
 *  - updateSongs(): Artists から各チャンネルの直近60日動画を探索 → 条件合格のみ SONGS に追加
 *  - generateRanking(): SNAPSHOT の差分でランキングを出力（汎用化）
 *  - autoGenerateDailyRanking(): 1日差分で RANKING_DAILY を生成
 *  - autoGenerateWeeklyRanking(): 7日差分で RANKING_WEEKLY を生成
 *
 * 前提:
 *  - Advanced Google services: YouTube Data API を ON
 ***************/

const CFG = {
  SHEET_ARTISTS: 'Artists',
  SHEET_SONGS: 'SONGS',
  SHEET_SNAPSHOT: 'SNAPSHOT',
  SHEET_RANKING_DAILY: 'RANKING_DAILY',
  SHEET_RANKING_WEEKLY: 'RANKING_WEEKLY',
  SHEET_RANKING_LONG: 'RANKING_LONG',
  SHEET_SONGS_LONG: 'SONGS_LONG', // 長期ヒット曲

  // SONGS列: A videoId / B artist / C title / D publishedAt
  SONGS_COLS: { videoId: 0, artist: 1, title: 2, publishedAt: 3 },

  // Artists列（あなたのシートに合わせる）
  // A:Artist Name / B:YouTube URL / C:Channel ID / D:Subscribers / E:Facebook / F:Role (P for Production)
  ART_COLS: { name: 0, youtubeUrl: 1, channelId: 2, subscribers: 3, facebook: 4, role: 5 },

  LOOKBACK_DAYS_SONGS: 60,   // 新曲収集の対象期間
  LOOKBACK_DAYS_RANK: 7,     // ランキング差分期間
  MIN_VIEWS: 0,              // 再生数制限を解除（新着を即座に拾う）
  MIN_AGE_DAYS: 0,           // 公開直後から対象
  MIN_DURATION_SEC: 61,      // Shorts除外（<=60秒を除外）

  // タイトル除外（必要なら追加）
  NG_WORDS: [
    'teaser', 'trailer', 'preview', 'behind', 'making',
    'version', 'ver.', 'live', 'performance',
    'dance practice', 'karaoke', 'remix'
  ],

  // 取得上限（チャンネル1つあたり）
  MAX_SEARCH_RESULTS_PER_CHANNEL: 25, // 直近から最大25本チェック（十分）
};

/**
 * アーティスト全員の新曲探索（超高速・クォータ最適化版）
 * 120名以上のアーティストを数分ではなく数十秒で処理します。
 */
function updateSongs() {
  logToSheet_('【実行】updateSongs 開始 (超高速バッチ版)');
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const shA = ss.getSheetByName(CFG.SHEET_ARTISTS);
  const shS = ss.getSheetByName(CFG.SHEET_SONGS);
  if (!shA || !shS) throw new Error('Required sheets not found');

  ensureSongsHeader_(shS);
  const initialRowCount = shS.getLastRow();

  // 1. 既存 videoId セットの構築
  const songData = shS.getDataRange().getValues();
  const shSongsLong = ss.getSheetByName(CFG.SHEET_SONGS_LONG);
  const songsLongData = shSongsLong ? shSongsLong.getDataRange().getValues() : [];
  
  const existing = new Set();
  for (let i = 1; i < songData.length; i++) {
    const id = String(songData[i][CFG.SONGS_COLS.videoId] || '').trim();
    if (id) existing.add(id);
  }
  for (let i = 1; i < songsLongData.length; i++) {
    const id = String(songsLongData[i][0] || '').trim();
    if (id) existing.add(id);
  }

  // 2. アーティストリストの読み込み
  const artists = shA.getDataRange().getValues();
  const targets = [];
  for (let i = 1; i < artists.length; i++) {
    const name = String(artists[i][CFG.ART_COLS.name] || '').trim();
    const channelId = String(artists[i][CFG.ART_COLS.channelId] || '').trim();
    if (name && channelId) {
      targets.push({ name, channelId });
    }
  }

  Logger.log(`Processing ${targets.length} artists in batches.`);
  const allVideoIdsToFetch = new Map(); // videoId -> artistInfo

  // 3. 【最適化】Channel ID から Uploads Playlist ID を一括取得 (50件ずつ)
  const channelToPlaylist = new Map();
  const targetIds = targets.map(t => t.channelId);
  
  for (const chunk of chunk_(targetIds, 50)) {
    try {
      const res = YouTube.Channels.list('contentDetails', { id: chunk.join(',') });
      updateApiUsage_('YouTube', 1);
      if (res && res.items) {
        res.items.forEach(item => {
          const pid = item.contentDetails.relatedPlaylists.uploads;
          if (pid) channelToPlaylist.set(item.id, pid);
        });
      }
    } catch (e) {
      Logger.log(`Batch Channels.list error: ${e.message}`);
    }
  }

  // 4. 各アーティストの最新動画 ID を収集 (PlaylistItems)
  const failures = [];
  let successCount = 0;

  for (const t of targets) {
    const playlistId = channelToPlaylist.get(t.channelId);
    let playlistVideoIds = [];

    if (playlistId) {
      try {
        const plist = YouTube.PlaylistItems.list('contentDetails', {
          playlistId: playlistId,
          maxResults: 20 // 最新20件で十分
        });
        updateApiUsage_('YouTube', 1);
        if (plist && plist.items) {
          plist.items.forEach(it => playlistVideoIds.push(it.contentDetails.videoId));
        }
        successCount++;
      } catch (e) {
        Logger.log(`Playlist error for ${t.name}: ${e.message}`);
        failures.push(`${t.name} (Playlist Error)`);
      }
    } else {
       failures.push(`${t.name} (No Uploads Playlist)`);
    }

    // 重複を弾いて「詳細取得待ち」に送る
    playlistVideoIds.forEach(vid => {
      if (!existing.has(vid)) {
        allVideoIdsToFetch.set(vid, { name: t.name, channelId: t.channelId });
      }
    });
  }

  // 5. 【最適化】全アーティストの未登録動画の詳細を一括取得 (50件ずつ)
  const masterToAppend = [];
  const videoIdsArray = Array.from(allVideoIdsToFetch.keys());
  Logger.log(`Fetching details for ${videoIdsArray.length} potential new songs...`);

  for (const chunk of chunk_(videoIdsArray, 50)) {
    try {
      const vids = YouTube.Videos.list('snippet,contentDetails,statistics', {
        id: chunk.join(','),
        maxResults: chunk.length
      });
      updateApiUsage_('YouTube', 1);

      if (vids && vids.items) {
        vids.items.forEach(v => {
          const artistInfo = allVideoIdsToFetch.get(v.id);
          const row = validateAndCreateSongRow_(v, artistInfo);
          if (row) {
            masterToAppend.push(row);
            existing.add(v.id); // 即座に既存セットに加えて同一実行内重複を防止
          }
        });
      }
    } catch (e) {
      Logger.log(`Batch Videos.list error: ${e.message}`);
    }
  }

  // 6. 新曲を一括書き込み
  if (masterToAppend.length > 0) {
    shS.getRange(shS.getLastRow() + 1, 1, masterToAppend.length, 4).setValues(masterToAppend);
  }

  // 7. 期限切れ削除処理
  const deletedCount = pruneSongs60d_(shS, CFG.LOOKBACK_DAYS_SONGS);

  // 8. 最終集計と通知
  const addedCount = masterToAppend.length;
  let msg = `【報告】YouTubeデータ更新完了 (高速版)\n\n`;
  msg += `新規追加: ${addedCount} 曲\n`;
  msg += `期限切れ削除: ${deletedCount} 曲\n\n`;
  msg += `対象: ${targets.length} 名中 ${successCount} 名成功\n`;
  if (failures.length > 0) msg += `失敗: ${failures.length} 名 (詳細はログを確認)\n`;

  logToSheet_(`SYNC: Update cycle completed. Added: ${addedCount}, Deleted: ${deletedCount}`);
  sendTelegramNotification_(msg);

  // 9. 使用状況の反映とソート
  flushApiUsage_();
  sortSongsSheet_(shS);
  
  Logger.log(`Finished. Added: ${addedCount}, Success: ${successCount}/${targets.length}`);
}

/**
 * デバッグ用: Artistsシートの一番上の行（VannDa想定）のみを対象に、
 * Search API を使って詳細ログを出しながら動画取得を試みる
 */
function updateVannDaOnly() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const shA = ss.getSheetByName(CFG.SHEET_ARTISTS);
  const shS = ss.getSheetByName(CFG.SHEET_SONGS);

  // 1行目 (データとしてはrow 2) を取得
  const name = String(shA.getRange(2, 1).getValue() || '').trim();
  const channelId = String(shA.getRange(2, 3).getValue() || '').trim();

  if (!channelId) {
    throw new Error('C列（Channel ID）が空です。同期機能を先に実行してください。');
  }

  Logger.log(`--- VannDa Target Debug Trace ---`);
  Logger.log(`Target: ${name} (ID: ${channelId})`);

  // 1. まず Search API で検索（最新動画を直接叩く）
  try {
    Logger.log(`Applying Search API strategy...`);
    const searchRes = YouTube.Search.list('snippet', {
      channelId: channelId,
      maxResults: 10,
      order: 'date',
      type: 'video'
    });

    const ids = (searchRes.items || []).map(it => it.id.videoId);
    Logger.log(`Search found ${ids.length} videos: ${ids.join(', ')}`);

    if (ids.length > 0) {
      // 1行目デバッグ時はフィルタを無視して取得を試みる (force=true)
      processVideoIds_(ids, { name, channelId }, shS, null, true);
    }
  } catch (e) {
    Logger.log(`Search API Error: ${e.message}`);
  }

  Logger.log(`--- End Trace ---`);

  // 自動ソート
  sortSongsSheet_(shS);

  SpreadsheetApp.getUi().alert('VannDaの再探査とソートが完了しました。ログ（表示 > 実行ログ）を確認し、SONGSシートの最上部に曲が追加されたか見てください。');
}

/**
 * IDリストから詳細情報を取得し、条件に合えばSONGSに追加する（内部共通関数）
 */
function processVideoIds_(ids, artistInfo, shS, existingSet, forceIgnoreFilters = false) {
  const now = new Date();

  // [最適化] 引数に Set があればそれを使う。なければ取得（後方互換性）
  let existing = existingSet;
  if (!existing) {
    const songs = shS.getDataRange().getValues();
    existing = new Set();
    for (let i = 1; i < songs.length; i++) {
      const id = String(songs[i][CFG.SONGS_COLS.videoId] || '').trim();
      if (id) existing.add(id);
    }
  }

  const vids = YouTube.Videos.list('snippet,contentDetails,statistics', {
    id: ids.join(','),
    maxResults: ids.length
  });
  updateApiUsage_('YouTube', 1); // 1 unit

  const toAppend = [];
  const vitems = (vids && vids.items) ? vids.items : [];

  for (const v of vitems) {
    if (existing.has(v.id)) {
      Logger.log(`[${v.snippet.title}] Already exists in SONGS. Skip.`);
      continue;
    }

    const title = String(v.snippet.title || '').trim();
    const publishedAt = v.snippet.publishedAt || '';
    const categoryId = String(v.snippet.categoryId || '');
    const viewCount = Number(v.statistics.viewCount || 0);
    const durSec = iso8601DurationToSeconds_(v.contentDetails.duration || 'PT0S');

    if (!forceIgnoreFilters) {
      // フィルタリング（デバッグ用に詳細ログ出し）
      if (viewCount < CFG.MIN_VIEWS) {
        Logger.log(`Skipped [${title}]: Low views (${viewCount})`);
        continue;
      }

      if (categoryId !== '10' && categoryId !== '24' && categoryId !== '22') {
        Logger.log(`Skipped [${title}]: Category ${categoryId} (Not Music/Ent/Blog)`);
        continue;
      }

      if (durSec < CFG.MIN_DURATION_SEC) {
        Logger.log(`Skipped [${title}]: Is Short (${durSec}s)`);
        continue;
      }

      const pub = new Date(publishedAt);
      const ageDays = (now - pub) / (1000 * 60 * 60 * 24);
      if (ageDays > CFG.LOOKBACK_DAYS_SONGS) {
        Logger.log(`Skipped [${title}]: Too old (${ageDays.toFixed(1)} days)`);
        continue;
      }
    } else {
      Logger.log(`Force matching [${title}] (Debugging mode)`);
    }

    // 合格（原本データ保護のため、SONGSシートにはクリーンアップせずそのまま保存）
    // 曲名にYouTubeへのハイパーリンクを付与 (スプレッドシート上)
    const videoUrl = "https://www.youtube.com/watch?v=" + v.id;
    const linkedTitle = '=HYPERLINK("' + videoUrl + '", "' + title.replace(/"/g, '""') + '")';
    toAppend.push([v.id, artistInfo.name, linkedTitle, publishedAt]);
    Logger.log(`✅ MATCHED: [${title}]`);
  }

  if (toAppend.length) {
    shS.getRange(shS.getLastRow() + 1, 1, toAppend.length, 4).setValues(toAppend);

    // [重要] 1回の実行中に複数アーティストが同じ動画 ID を持っていた場合の重複を防ぐため
    // メモリ上の existing セットにも即座に追加
    if (existing) {
      toAppend.forEach(row => existing.add(row[0]));
    }

    Logger.log(`Added ${toAppend.length} songs to SONGS sheet (and updated memory set).`);
  }
}

/**
 * 毎日自動的に実行されるデイリーランキング生成 + Facebook投稿
 * ※ トリガー消失に備え、ランキング生成後に直接FB投稿も呼び出す設計。
 */
function autoGenerateDailyRanking() {
  sendTelegramNotification_('【実行】Dailyランキング作成開始');
  try {
    generateRanking(1, CFG.SHEET_RANKING_DAILY);
    logToSheet_('【完了】autoGenerateDailyRanking');
  } catch (e) {
    Logger.log('Error in autoGenerateDailyRanking: ' + e.message);
    if (typeof sendTelegramNotification_ === 'function') {
      sendTelegramNotification_('⚠️ 【エラー】デイリーランキング自動作成に失敗しました。\nエラー内容:\n' + e.toString());
    }
    return; // ランキング生成に失敗した場合はFB投稿もスキップ
  }

  // ロングヒットランキングも併せて生成
  try {
    generateRanking(1, CFG.SHEET_RANKING_LONG);
  } catch (e) {
    Logger.log('Error in generateRanking(LONG): ' + e.message);
  }

  // ランキング生成成功後、直接FB投稿を実行（トリガー消失の保険）
  logToSheet_('【実行】autoGenerateDailyRanking → FB投稿フォールバック実行');
  try {
    if (typeof autoPostToFacebook === 'function') {
      autoPostToFacebook();
    }
  } catch (e) {
    logToSheet_('FB投稿フォールバックエラー: ' + e.message);
    if (typeof sendTelegramNotification_ === 'function') {
      sendTelegramNotification_('⚠️ 【エラー】FB投稿フォールバックに失敗しました。\nエラー内容:\n' + e.toString());
    }
  }
}

/**
 * デイリーランキングをFacebookに投稿するトリガー用関数
 * ※ autoGenerateDailyRanking 内でのフォールバック投稿が失敗した場合の
 *    バックアップとして機能します。本日すでに投稿済みの場合はスキップします。
 */
function autoPostDailyRankingToFacebook() {
  logToSheet_('【実行】autoPostDailyRankingToFacebook 開始');

  // 本日すでに投稿済みか確認（二重投稿防止）
  try {
    const tz = Session.getScriptTimeZone();
    const todayStr = Utilities.formatDate(new Date(), tz, 'yyyy.MM.dd');
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const logSheet = ss.getSheetByName('DEBUG_LOG');
    if (logSheet) {
      const lastRow = logSheet.getLastRow();
      const checkRows = Math.min(50, lastRow - 1);
      if (checkRows > 0) {
        const recentLogs = logSheet.getRange(lastRow - checkRows + 1, 2, checkRows, 1).getValues();
        const alreadyPosted = recentLogs.some(row => 
          String(row[0]).includes('【成功】Facebook自動投稿完了') && String(row[0]).includes(todayStr)
        );
        if (alreadyPosted) {
          logToSheet_('autoPostDailyRankingToFacebook: 本日(' + todayStr + ')はすでに投稿済みのためスキップします。');
          return;
        }
      }
    }
  } catch (checkErr) {
    logToSheet_('二重投稿チェックエラー (続行します): ' + checkErr.message);
  }

  try {
    if (typeof autoPostToFacebook === 'function') {
      autoPostToFacebook();
    } else {
      throw new Error('autoPostToFacebook function not found');
    }
  } catch (e) {
    logToSheet_('Error in autoPostDailyRankingToFacebook: ' + e.message);
    if (typeof sendTelegramNotification_ === 'function') {
      sendTelegramNotification_('⚠️ 【エラー】Facebook自動投稿プロセス中にエラーが発生しました。\nエラー内容:\n' + e.toString());
    }
  }
}

/**
 * 手動で本番のデイリーランキングを安全に更新する関数（Facebookへの自動投稿は行わない）
 */
function updateLiveRankingNoFb() {
  Logger.log('--- 手動更新スタート (Facebook投稿なし) ---');
  generateRanking(1, CFG.SHEET_RANKING_DAILY);
  Logger.log('--- 手動更新完了 ---');
}
/**
 * 毎週自動的に実行されるウィークリーランキング生成
 */
function autoGenerateWeeklyRanking() {
  logToSheet_('【実行】autoGenerateWeeklyRanking 開始');
  generateRanking(7, CFG.SHEET_RANKING_WEEKLY);
  // Weekly のタイミングでも LongRanking を更新（差分は1日分でOKな場合が多いが、整合性のため）
  generateRanking(1, CFG.SHEET_RANKING_LONG);
}

/**
 * 汎用ランキング生成エンジン
 * @param {number} lookbackDays 遡る日数 (1 = Daily, 7 = Weekly)
 * @param {string} targetSheetName 出力先シート名
 */
function generateRanking(lookbackDays, targetSheetName) {
  const TOP_N = 20;
  const LOOKBACK_DAYS = lookbackDays || CFG.LOOKBACK_DAYS_RANK;

  const ss = SpreadsheetApp.getActiveSpreadsheet();
  logToSheet_(`【開始】generateRanking (${targetSheetName}, lookback: ${LOOKBACK_DAYS}日)`);

  const shArtists = ss.getSheetByName(CFG.SHEET_ARTISTS);
  const shSongs = ss.getSheetByName(CFG.SHEET_SONGS);
  const shSongsLong = ss.getSheetByName(CFG.SHEET_SONGS_LONG) || ss.insertSheet(CFG.SHEET_SONGS_LONG);
  const shSnap = ss.getSheetByName(CFG.SHEET_SNAPSHOT);
  const shRank = ss.getSheetByName(targetSheetName) || ss.insertSheet(targetSheetName);

  // SONGS_LONG のヘッダー確認
  ensureSongsHeader_(shSongsLong);

  // 【視認性改善】列構造を強制更新（Genre/Visual Conceptなどの不足をチェック）
  const currentHeaders = shRank.getLastRow() > 0 ? shRank.getRange(1, 1, 1, Math.max(shRank.getLastColumn(), 1)).getValues()[0].map(h => String(h).trim()) : [];
  const hasGenre = currentHeaders.includes('Genre');
  const hasVisual = currentHeaders.includes('Visual Concept');
  const hasShortInsight = currentHeaders.includes('shortInsight');

  if (!hasGenre || !hasVisual || !hasShortInsight || currentHeaders.length < 24) {
    // 列が不足している場合のみ、ヘッダーを上書き（内容のクリアは行わない）
    const colName = lookbackDays === 1 ? 'トレンド(1d)' : 'トレンド(7d)';
    const diffColName = lookbackDays === 1 ? '増加数(1d)' : '増加数(7d)';
    const prevColName = lookbackDays === 1 ? '1日前' : '7日前';

    const newHeaders = [
      '日付', '順位', 'PrevRank', 'アーティスト', '曲名', '公開日', colName,
      'AIスコア', 'AIインサイト', 'shortInsight', 'Genre', 'Visual Concept',
      'Heatスコア', 'コメ品質', '成長率(%)', '反応率', diffColName, '現在再生数', prevColName,
      'YouTube', 'Facebook', '備考', 'videoId', 'historyRaw'
    ];
    shRank.getRange(1, 1, 1, newHeaders.length).setValues([newHeaders]);
    Logger.log(`RANKING sheet header updated safely.`);
  }

  const tz = Session.getScriptTimeZone();

  const toDateKey = (v) => toDateKey_(v, tz);
  const toId = (v) => String(v || '').trim();

  // Artists A:Name / E:Facebook URL / F:Role
  const artists = shArtists.getDataRange().getValues();
  const metaByArtist = new Map();
  for (let i = 1; i < artists.length; i++) {
    const name = String(artists[i][CFG.ART_COLS.name] || '').trim();
    const fb = String(artists[i][CFG.ART_COLS.facebook] || '').trim();
    const role = String(artists[i][CFG.ART_COLS.role] || '').trim().toUpperCase();
    if (name) metaByArtist.set(name, { fb, role });
  }

  // SONGS: videoId -> meta
  const songs = shSongs.getDataRange().getValues();
  const songById = new Map();
  for (let i = 1; i < songs.length; i++) {
    const videoId = toId(songs[i][CFG.SONGS_COLS.videoId]);
    if (!videoId) continue;
    songById.set(videoId, {
      artist: String(songs[i][CFG.SONGS_COLS.artist] || '').trim(),
      title: String(songs[i][CFG.SONGS_COLS.title] || '').trim(),
      publishedAt: songs[i][CFG.SONGS_COLS.publishedAt],
      isLongTerm: false
    });
  }
  // SONGS_LONG も追加
  const songsLong = shSongsLong.getDataRange().getValues();
  for (let i = 1; i < songsLong.length; i++) {
    const videoId = toId(songsLong[i][CFG.SONGS_COLS.videoId]);
    if (!videoId) continue;
    songById.set(videoId, {
      artist: String(songsLong[i][CFG.SONGS_COLS.artist] || '').trim(),
      title: String(songsLong[i][CFG.SONGS_COLS.title] || '').trim(),
      publishedAt: songsLong[i][CFG.SONGS_COLS.publishedAt],
      isLongTerm: true
    });
  }

  // SNAPSHOT日付集合
  const snap = shSnap.getDataRange().getValues();
  if (snap.length < 2) throw new Error('SNAPSHOT empty');

  const dateSet = new Set();
  for (let i = 1; i < snap.length; i++) {
    const dk = toDateKey(snap[i][0]);
    if (dk) dateSet.add(dk);
  }
  const dates = Array.from(dateSet).sort();
  if (dates.length < 2) throw new Error('Need at least 2 snapshot dates');

  const latestDate = dates[dates.length - 1];
  const latestObj = new Date(latestDate + 'T00:00:00');

  // 目標：latest - 7日
  const target = new Date(latestObj);
  target.setDate(target.getDate() - LOOKBACK_DAYS);
  const targetKey = Utilities.formatDate(target, tz, 'yyyy-MM-dd');

  // targetKey以下で最大（=7日前に最も近い過去日）
  let baseDate = '';
  for (let i = dates.length - 1; i >= 0; i--) {
    if (dates[i] <= targetKey) { baseDate = dates[i]; break; }
  }
  if (!baseDate) baseDate = dates[0];

  // 7日間の履歴（スパークライン用）と最新・ベースの取得
  const latest = new Map();
  const base = new Map();
  const history = new Map(); // videoId -> Map(dateKey -> views)

  const last14Dates = dates.slice(-14);
  const relevantDates = new Set([latestDate, baseDate, ...last14Dates]);

  logToSheet_(`SNAPSHOT読込開始: ${snap.length} 行中、関連 ${relevantDates.size} 日分を抽出します...`);

  // 高速化のための事前変換：Service Callをループ外に出す
  const formattedRelevantDates = new Set();
  relevantDates.forEach(d => formattedRelevantDates.add(String(d)));

  // Optimized scan of SNAPSHOT (Avoid calling toDateKey_ inside loop)
  for (let i = snap.length - 1; i >= 1; i--) {
    const rawDate = snap[i][0];
    if (!rawDate) continue;

    // Date objectを高速に文字列変換 (Utilities.formatDateを使わない)
    let d;
    if (rawDate instanceof Date) {
      const year = rawDate.getFullYear();
      const month = ('0' + (rawDate.getMonth() + 1)).slice(-2);
      const day = ('0' + rawDate.getDate()).slice(-2);
      d = `${year}-${month}-${day}`;
    } else {
      d = String(rawDate).split(' ')[0]; // String date handling
    }

    if (!formattedRelevantDates.has(d)) continue;

    const id = toId(snap[i][1]);
    if (!songById.has(id)) continue;

    const v = +snap[i][2] || 0;
    const l = +snap[i][3] || 0;
    const c = +snap[i][4] || 0;
    const row = { v, l, c };

    if (d === latestDate) latest.set(id, row);
    if (d === baseDate) base.set(id, row);

    // History for sparklines (By Date mapping)
    if (!history.has(id)) history.set(id, new Map());
    history.get(id).set(d, v);
  }

  logToSheet_(`データ抽出完了: latestDate=${latestDate}, baseDate=${baseDate}, latestCount=${latest.size}, baseCount=${base.size}`);

  const now = new Date();
  const list = [];
  const isLongTermTarget = (targetSheetName === CFG.SHEET_RANKING_LONG);

  for (const [id, L] of latest.entries()) {
    let B = base.get(id);
    const meta = songById.get(id);
    if (!meta) continue;

    // ターゲットシートに応じてフィルタリング
    if (isLongTermTarget) {
      if (!meta.isLongTerm) continue; // LONGシート生成時は SONGS_LONG の曲のみ
    } else {
      if (meta.isLongTerm) continue; // メインランキング（Daily/Weekly）からは除外
    }

    const pub = (meta.publishedAt && !isNaN(new Date(meta.publishedAt).getTime())) ? new Date(meta.publishedAt) : null;

    // 【変更】0日から表示させるためのロジック緩和
    if (!B) {
      const isVeryNew = pub && (now - pub) / (1000 * 60 * 60 * 24) <= 3;
      if (isVeryNew) {
        B = { v: 0, l: 0, c: 0 };
        Logger.log(`[${meta.title}] Day-0/New: Using 0-baseline`);
      } else {
        const baseObj = new Date(baseDate + 'T00:00:00');
        if (pub && pub >= baseObj) {
          B = { v: 0, l: 0, c: 0 };
          Logger.log(`[${meta.title}] Catching New release: Using 0-baseline`);
        } else {
          continue; // 古い曲なのにベースがない場合はスキップ
        }
      }
    }

    if (pub && !meta.isLongTerm) {
      const daysSince = (now - pub) / (1000 * 60 * 60 * 24);
      if (daysSince < CFG.MIN_AGE_DAYS) continue;
      if (daysSince > CFG.LOOKBACK_DAYS_SONGS) continue;
    }

    // diffs（7日差分）
    const dvRaw = L.v - B.v;
    const dlRaw = L.l - B.l;
    const dcRaw = L.c - B.c;

    const dv = Math.max(0, dvRaw);
    const dl = Math.max(0, dlRaw);
    const dc = Math.max(0, dcRaw);

    // バランス型スコア: 今日の再生数(dv)と熱量(dl, dc)を強く評価する
    // scale (累積の強さ) の影響力を大幅に弱め、微細な「実績ボーナス（最大1.6倍程度）」に変更
    const scale = 1 + (Math.log10(L.v + 1) / 10);
    let heat =
      (5 * Math.log(dv + 1) * scale) +
      (3 * Math.log(dl + 1)) +
      (5 * Math.log(dc + 1));

    // 追加指標の計算
    // [修正] ベースが0の場合のゼロ除算回避
    const growthRate = (B.v > 0) ? (dvRaw / B.v) : (dvRaw > 0 ? 1.0 : 0);
    const engagement = L.v > 0 ? (L.l + L.c) / L.v : 0;

    // 履歴Mapから配列を作成
    const vMap = history.get(id) || new Map();
    const vHistory = last14Dates.map(d => vMap.get(d)).filter(v => v !== undefined);

    // 日次増加幅の解析 (Momentum Drop検知用)
    let peakDailyDelta = 0;
    let latestDailyDelta = 0;
    if (vHistory.length >= 2) {
      const dailyDeltas = [];
      for (let i = 1; i < vHistory.length; i++) {
        dailyDeltas.push(Math.max(0, vHistory[i] - vHistory[i - 1]));
      }
      peakDailyDelta = Math.max(...dailyDeltas);
      latestDailyDelta = dailyDeltas[dailyDeltas.length - 1];
    }

    // スパークライン用の式 (直近最大7点)
    let sparkArr = vHistory.slice(-14);
    if (sparkArr.length <= 1 && B.v !== L.v) {
      sparkArr = [B.v || 0, L.v];
    }
    const sparkValues = sparkArr.join(',');
    const sparkFormula = sparkArr.length > 1 ? `=SPARKLINE({${sparkValues}}, {"charttype","line";"linewidth",2;"color","#1a73e8"})` : '-';

    // ⚠ 異常数値の検知ロジック (数値ベースのみ)
    let alert = '';
    let reason = '';

    if (dvRaw < 0) {
      alert = '⚠';
      reason = 'Abnormal view drop (Audit)';
    } else {
      if (growthRate > 3.0 && dvRaw > 50000) {
        alert = '⚡';
        reason = 'Abnormal view surge';
      }
      if (peakDailyDelta > 20000 && latestDailyDelta < peakDailyDelta * 0.2) {
        alert = (alert === '⚡' ? '⚡📉' : '📉');
        reason = (reason ? reason + ', ' : '') + 'Growth momentum drop';
      }
      if (dvRaw > 10000 && (dlRaw + dcRaw) / dvRaw < 0.001) {
        alert = (alert.includes('⚠') ? alert : alert + '⚠');
        reason = (reason ? reason + ', ' : '') + 'Low engagement for growth';
      }
    }

    const artistMeta = metaByArtist.get(meta.artist) || { fb: '', role: '' };
    const fbUrl = artistMeta.fb;

    list.push({
      id,
      artist: meta.artist, // 仮（後でAIパース）
      title: meta.title,   // 仮（後でAIパース）
      role: artistMeta.role,
      heat,
      dv: dvRaw,
      currentV: L.v,
      baseV: B.v,
      growth: growthRate,
      eng: engagement,
      commUnique: 1.0, // コメント監査廃止につき固定
      spark: sparkFormula,
      alert,
      reason,
      fbUrl,
      publishedAt: meta.publishedAt,
      isLongTerm: meta.isLongTerm,
      history: vHistory
    });
  }

  logToSheet_(`候補リスト作成完了: ${list.length} 件`);

  // スコア順にソートしてTop Nを確定
  list.sort((a, b) => b.heat - a.heat);
  const TOP_AI = 30; // AI分析の対象曲数 (30位まで監査を維持)
  const candidatesForAi = list.slice(0, TOP_AI);

  // --- Gemini AIによる深層分析 ---
  const typeLabel = lookbackDays === 1 ? 'Daily' : 'Weekly';

  // 精度向上のため、上位20曲のメタデータ（概要欄・タグ・サムネイル）を個別に取得
  const topIds = candidatesForAi.map(c => c.id);
  try {
    const videoRes = YouTube.Videos.list('snippet', { id: topIds.join(',') });
    const videoMetaMap = new Map();
    if (videoRes && videoRes.items) {
      videoRes.items.forEach(v => {
        videoMetaMap.set(v.id, {
          description: v.snippet.description,
          tags: v.snippet.tags || [],
          thumbnail: v.snippet.thumbnails?.high?.url || v.snippet.thumbnails?.default?.url
        });
      });
    }

    // 候補に詳細メタデータを紐付け
    candidatesForAi.forEach(c => {
      const vMeta = videoMetaMap.get(c.id);
      if (vMeta) {
        c.description = vMeta.description;
        c.tags = vMeta.tags;
        c.thumbnail = vMeta.thumbnail;
      }
    });
  } catch (e) {
    logToSheet_('Extra Video Meta Fetch Error: ' + e.message);
  }

  // 前回の順位を記憶 (videoId -> rank) - AI分析のコンテキストとして使用するため先に取得
  const prevRankMap = new Map();
  if (shRank.getLastRow() > 1) {
    const prevData = shRank.getDataRange().getValues();
    const headers = prevData[0].map(h => String(h || '').trim());
    const vIdIdx = headers.indexOf('videoId');
    const rankIdx = headers.indexOf('順位');
    const prevRankIdx = headers.indexOf('PrevRank');
    const dateIdx = headers.indexOf('日付');

    for (let i = 1; i < prevData.length; i++) {
      const vid = String(prevData[i][vIdIdx]).trim();
      const rowDate = toDateKey(prevData[i][dateIdx]);

      let historicalRank = NaN;
      if (rowDate === latestDate && prevRankIdx !== -1) {
        historicalRank = parseInt(prevData[i][prevRankIdx]);
      } else {
        historicalRank = parseInt(prevData[i][rankIdx]);
      }

      if (vid && !isNaN(historicalRank) && historicalRank !== 100 && historicalRank !== 0) {
        prevRankMap.set(vid, historicalRank);
      }
    }
  }

  // 候補に前回順位を紐付け
  candidatesForAi.forEach(c => {
    c.prevRank = prevRankMap.get(c.id) || 100;
  });

  logToSheet_('Gemini AI分析を開始します...');

  const aiResults = analyzeRankingWithAi(candidatesForAi, typeLabel);

  if (aiResults) {
    const aiArray = Array.from(aiResults.values());
    candidatesForAi.forEach((c, index) => {
      let aiData = aiResults.get(String(c.id)) || aiResults.get(`${c.artist} - ${c.title}`);

      // Sequential fallback if exact ID matching fails
      if (!aiData && aiArray.length >= candidatesForAi.length) {
        aiData = aiArray[index];
      }

      if (aiData) {
        // AIによる正規化表記を適用し、さらにプログラムでサフィックスを強制除去
        if (aiData.artist) {
          let art = aiData.artist;
          // Pロール以外、または AIが抽出した個別アーティスト名に対してクリーンアップ
          c.artist = cleanArtistName(art);
        }
        if (aiData.title) c.title = aiData.title;

        c.aiScore = aiData.aiScore || aiData.aiscore;
        c.aiInsight = aiData.insight || aiData.aiInsight || aiData.aiinsight;
        c.shortInsight = aiData.shortInsight || aiData.shortinsight;
        c.genre = aiData.genre || aiData.Genre;
        c.visualConcept = aiData.visualConcept || aiData.visual_concept || aiData.visualconcept || aiData.VisualConcept;

        // コメント品質スコアの適用とスコア再計算
        const qScore = Number(aiData.commentQualityScore || aiData.commentqualityscore || 1.0);
        c.commUnique = qScore;
        // 品質スコアに基づき最終Heatを調整 (0.0なら半分に減点、1.0なら等倍)
        c.heat = c.heat * ((qScore + 1.0) / 2.0);
      }
    });
    // AI分析の結果（品質減点など）を反映して再ソート
    candidatesForAi.sort((a, b) => b.heat - a.heat);
    logToSheet_('Gemini AI分析と再ランキングが完了しました。');
  } else {
    logToSheet_('⚠ Gemini AI分析がスキップされたか、失敗しました。');
  }
  // ------------------------------------

  // 最終的なランキングTop 20を確定
  const top = candidatesForAi.slice(0, 20);

  // 決定したTop Nを書き込み（ヘッダーは冒頭で作成済みのためクリアせず追加）
  // 以前のデータ行のみを削除して書き込み

  if (top.length > 0) {
    // 過去のランキングデータをクリア（書き込み直前に行う）
    if (shRank.getLastRow() > 1) {
      shRank.getRange(2, 1, shRank.getLastRow() - 1, shRank.getLastColumn()).clearContent();
    }
  } else {
    logToSheet_(`WARNING: Ranking generation produced 0 items. Keeping previous data to avoid empty sheet.`);
    return; // 0件なら何もしない（前日のデータを守る）
  }

  const out = top.map((x, i) => [
    latestDate,
    i + 1,
    x.prevRank || '-', // PrevRank
    x.artist,
    x.title,
    (() => {
      try {
        if (!x.publishedAt) return '';
        const d = new Date(x.publishedAt);
        if (isNaN(d.getTime())) return '';
        return d.toISOString();
      } catch (e) { return ''; }
    })(),
    x.spark,
    (x.aiScore !== undefined && x.aiScore !== null) ? x.aiScore : '-',
    x.aiInsight || '-',
    x.shortInsight || '-', // NEW FIELD FOR OG IMAGE
    x.genre || '-',
    x.visualConcept || '-',
    Math.round(x.heat * 100) / 100,
    Math.round(x.commUnique * 100) + '%',
    Math.round(x.growth * 10000) / 100 + '%',
    Math.round(x.eng * 10000) / 100 + '%',
    x.dv,
    x.currentV,
    x.baseV,
    `https://youtu.be/${x.id}`,
    x.fbUrl ? `=HYPERLINK("${x.fbUrl}","Facebook")` : '',
    x.alert + x.reason,
    x.id,
    "'" + x.history.slice(-14).join(';'),
    x.isLongTerm ? 'TRUE' : '' // LongTermFlag for internal use
  ]);

  logToSheet_(`シート書込開始: ${out.length} 行...`);
  if (out.length) {
    const range = shRank.getRange(2, 1, out.length, out[0].length);
    range.setValues(out);
    shRank.getRange(2, 2, out.length, 1).setNumberFormat('0');
  }
  logToSheet_(`【完了】generateRanking (${targetSheetName}) 全工程終了`);
}

/* ---------------- helpers ---------------- */

function ensureSongsHeader_(sh) {
  if (sh.getLastRow() === 0) {
    sh.appendRow(['videoId', 'artist', 'title', 'publishedAt']);
    return;
  }
  const h = sh.getRange(1, 1, 1, 4).getValues()[0];
  if (String(h[0]) !== 'videoId') {
    sh.insertRowBefore(1);
    sh.getRange(1, 1, 1, 4).setValues([['videoId', 'artist', 'title', 'publishedAt']]);
  }
}

function pruneSongs60d_(shSongs, keepDays) {
  const now = new Date();
  const cutoff = new Date(now);
  cutoff.setDate(cutoff.getDate() - keepDays);

  const values = shSongs.getDataRange().getValues();
  if (values.length < 2) return 0;

  const keep = [values[0]]; // header
  const movedToLong = [];

  // 現在のランキングに入っている曲を取得 (videoId のリスト)
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const shRank = ss.getSheetByName(CFG.SHEET_RANKING_DAILY);
  const currentHitIds = new Set();
  if (shRank) {
    const rankData = shRank.getDataRange().getValues();
    if (rankData.length > 1) {
      // RANKING_DAILY の w:videoId (23列目、0-indexed: 23)
      for (let i = 1; i < rankData.length; i++) {
        const vid = String(rankData[i][23] || '').trim();
        if (vid) currentHitIds.add(vid);
      }
    }
  }

  for (let i = 1; i < values.length; i++) {
    const videoId = values[i][CFG.SONGS_COLS.videoId];
    const publishedAt = values[i][CFG.SONGS_COLS.publishedAt];
    const d = new Date(publishedAt || '');
    if (!d || isNaN(d.getTime())) continue;

    if (d >= cutoff) {
      keep.push(values[i]);
    } else if (currentHitIds.has(videoId)) {
      // 60日経過しているが、現在ランキング入りしている場合は SONGS_LONG へ
      movedToLong.push(values[i]);
      Logger.log(`Song [${videoId}] moved to SONGS_LONG (Hit survived > 60 days)`);
    }
  }

  // SONGS_LONG への書き込み
  if (movedToLong.length > 0) {
    const shLong = ss.getSheetByName(CFG.SHEET_SONGS_LONG) || ss.insertSheet(CFG.SHEET_SONGS_LONG);
    ensureSongsHeader_(shLong);
    
    // 重複チェック
    const longData = shLong.getDataRange().getValues();
    const existingLongIds = new Set(longData.map(r => String(r[0]).trim()));
    const finalToMove = movedToLong.filter(row => !existingLongIds.has(String(row[0]).trim()));
    
    if (finalToMove.length > 0) {
      shLong.getRange(shLong.getLastRow() + 1, 1, finalToMove.length, finalToMove[0].length).setValues(finalToMove);
    }
  }

  if (keep.length !== values.length) {
    const deleted = values.length - keep.length;
    // [安全対策] clear() してから setValues() だと、途中でエラー時に全ロスするリスクがあるため
    // 安全に「新しい内容で上書き」を行う
    if (shSongs.getLastRow() > 0) {
      shSongs.getRange(1, 1, shSongs.getLastRow(), values[0].length).clearContent();
    }
    shSongs.getRange(1, 1, keep.length, keep[0].length).setValues(keep);
    Logger.log(`SONGS pruned: ${values.length - 1} -> ${keep.length - 1} (Deleted: ${deleted})`);
    return deleted;
  }
  return 0;
}

/**
 * SONGSシートを公開日(D列)の新しい順にソートする
 */
function sortSongsSheet_(sh) {
  const lastRow = sh.getLastRow();
  if (lastRow < 2) return;

  // A:videoId, B:artist, C:title, D:publishedAt
  // D列(4列目)を降順(false)でソート
  sh.getRange(2, 1, lastRow - 1, 4).sort({ column: 4, ascending: false });
  Logger.log('SONGS sheet sorted by publishedAt (Descending).');
}

/**
 * メニューから手動でSONGSシートのソートを実行する
 */
function manualSortSongs() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sh = ss.getSheetByName(CFG.SHEET_SONGS);
  if (!sh) {
    SpreadsheetApp.getUi().alert('SONGSシートが見つかりません。');
    return;
  }
  sortSongsSheet_(sh);
  SpreadsheetApp.getUi().alert('SONGSシートを公開日の新しい順にソートしました。');
}

/**
 * SONGSシートの重複（videoId重複）を掃除する管理ツール
 */
function cleanupDuplicateSongs() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const shS = ss.getSheetByName(CFG.SHEET_SONGS);
  if (!shS) return;

  const data = shS.getDataRange().getValues();
  if (data.length < 2) return;

  const header = data[0];
  const uniqueRows = [header];
  const seen = new Set();
  let count = 0;

  for (let i = 1; i < data.length; i++) {
    const videoId = String(data[i][CFG.SONGS_COLS.videoId] || '').trim();
    if (!videoId) continue;

    if (seen.has(videoId)) {
      count++;
    } else {
      seen.add(videoId);
      uniqueRows.push(data[i]);
    }
  }

  if (count > 0) {
    shS.clear(); // シート全体（内容と書式）をクリア
    shS.getRange(1, 1, uniqueRows.length, uniqueRows[0].length).setValues(uniqueRows);
    SpreadsheetApp.getUi().alert(`清掃完了: ${count} 件の重複曲を削除しました。`);
  } else {
    SpreadsheetApp.getUi().alert('重複曲は見つかりませんでした。');
  }
}

/**
 * 汎用的な日付キーへの変換 (yyyy-MM-dd)
 */
function toDateKey_(v, tz) {
  if (!v) return '';
  if (Object.prototype.toString.call(v) === '[object Date]') {
    return Utilities.formatDate(v, tz || Session.getScriptTimeZone(), 'yyyy-MM-dd');
  }
  const s = String(v).trim();
  const d = new Date(s);
  if (!isNaN(d.getTime())) {
    return Utilities.formatDate(d, tz || Session.getScriptTimeZone(), 'yyyy-MM-dd');
  }
  return s;
}

/**
 * 動画が条件に合致するか判定し、SONGS用行データを生成する
 */
function validateAndCreateSongRow_(v, artistInfo) {
  const title = String(v.snippet.title || '').trim();
  const publishedAt = v.snippet.publishedAt || '';
  const categoryId = String(v.snippet.categoryId || '');
  const viewCount = Number(v.statistics.viewCount || 0);
  const durSec = iso8601DurationToSeconds_(v.contentDetails.duration || 'PT0S');
  const now = new Date();

  // 音楽・エンタメ・ブログ以外を除外
  if (categoryId !== '10' && categoryId !== '24' && categoryId !== '22') return null;
  // Shorts を除外
  if (durSec < CFG.MIN_DURATION_SEC) return null;
  // 古すぎる動画を除外
  const pub = new Date(publishedAt);
  const ageDays = (now - pub) / (1000 * 60 * 60 * 24);
  if (ageDays > CFG.LOOKBACK_DAYS_SONGS) return null;

  // リンク付きタイトル
  const videoUrl = "https://www.youtube.com/watch?v=" + v.id;
  const linkedTitle = '=HYPERLINK("' + videoUrl + '", "' + title.replace(/"/g, '""') + '")';
  
  return [v.id, artistInfo.name, linkedTitle, publishedAt];
}

/**
 * 配列を指定サイズごとに分割するヘルパー
 */
function chunk_(arr, size) {
  const out = [];
  if (!arr) return out;
  for (let i = 0; i < arr.length; i += size) {
    out.push(arr.slice(i, i + size));
  }
  return out;
}

/**
 * ISO 8601 形式の期間（PT1M30Sなど）を秒数に変換する
 */
function iso8601DurationToSeconds_(dur) {
  const m = String(dur || '').match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!m) return 0;
  const h = parseInt(m[1] || '0', 10);
  const min = parseInt(m[2] || '0', 10);
  const s = parseInt(m[3] || '0', 10);
  return h * 3600 + min * 60 + s;
}



/* -------------------------------------------------------------------------- */
/*                                Vertex AI Logic                               */
/* -------------------------------------------------------------------------- */

const GEMINI_CONFIG = {
  // スクリプトプロパティ 'GEMINI_API_KEY'
  API_KEY: PropertiesService.getScriptProperties().getProperty('GEMINI_API_KEY'),
  MODEL_NAME: 'gemini-2.5-flash',
};

/**
 * デバッグログをスプレッドシートに記録する
 * @param {string} msg 記録するメッセージ
 */
function logToSheet_(msg) {
  try {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    let sh = ss.getSheetByName('DEBUG_LOG');
    if (!sh) sh = ss.insertSheet('DEBUG_LOG');
    sh.appendRow([new Date(), String(msg)]);
  } catch (e) { }
}

/**
 * AIシステムが利用可能かチェックする
 * @returns {boolean} AIシステムが利用可能であればtrue
 */
function isAiSystemReady_() {
  if (!GEMINI_CONFIG.API_KEY) {
    logToSheet_('【システム通知】GEMINI_API_KEY がスクリプトプロパティに設定されていません。スプレッドシートの「設定」などを確認してください。');
    return false;
  }
  return true;
}

/**
 * Gemini（Vertex AI 互換）を通じてランキング分析を実行
 * @param {Array} contextData 現在の計算式で出された上位曲リスト
 * @param {string} typeLabel 'Daily' or 'Weekly'
 */
function analyzeRankingWithAi(contextData, typeLabel) {
  if (!isAiSystemReady_()) {
    logToSheet_('AI System is not ready or keys are missing. Skipping analysis.');
    return null;
  }

  try {
    const totalSongs = contextData.length;
    const chunkSize = 6; // 1回あたり6曲ずつ解析 (30曲を5回で処理)
    const allResultsMap = new Map();

    SpreadsheetApp.getActiveSpreadsheet().toast(`AI分析を開始します (全${totalSongs}曲 / ${chunkSize}曲ずつ分割実行)...`, 'Gemini AI', 5);
    logToSheet_(`Starting Chunked Gemini Analysis for ${typeLabel} (Total: ${totalSongs}, Chunk: ${chunkSize})`);

    for (let i = 0; i < totalSongs; i += chunkSize) {
      const chunkData = contextData.slice(i, i + chunkSize);
      const simplifiedData = chunkData.map(c => ({
        id: c.id,
        rank: c.rank,
        prevRank: c.prevRank,
        change: c.rankChange,
        artist: c.artist,
        title: c.title,
        role: c.role,
        views: c.views,
        growth: c.growth,
        heat: c.heat,
        comments_sample: fetchComments_(c.id)
      }));

      const prompt = `
Generate localized insights and normalize naming for these ${simplifiedData.length} Cambodian songs.
【Data】
${JSON.stringify(simplifiedData)}

【Strict Instructions for artist & title】
- Support both Khmer and English scripts. DO NOT remove Khmer script if it's the primary name.
- Identify the ACTUAL performing artist(s).
- For cleaning: Remove suffixes like "Official", "Official Channel", "Production", etc.
- title: Remove artist names and label names. Show ONLY the pure song title.

【Insight Tasks】
1. insight (English): Narrative based on DATA TRENDS (Momentum, Stability, Debut).
2. shortInsight (English): 8-10 words summarizing the chart performance factor.
3. aiScore: 0-100 score reflecting growth momentum.
4. commentQualityScore: Rate authenticity (0.0 to 1.0). 1.0=Natural, <0.7=Repetitive/Bot-like, <0.5=Spam.
5. genre: e.g., Khmer Pop, Hip Hop.
6. visualConcept: 1-2 words.

【Format】 JSON Array of objects with keys: id, artist, title, aiScore, commentQualityScore, insight, shortInsight, genre, visualConcept.
`;

      logToSheet_(`Batch ${Math.floor(i / chunkSize) + 1} call...`);
      const response = callGeminiApi_(prompt);
      if (!response) {
        logToSheet_(`Batch ${Math.floor(i / chunkSize) + 1} returned null. Skipping.`);
        continue;
      }

      // JSON抽出
      let jsonStr = response.trim();
      if (jsonStr.startsWith('```json')) jsonStr = jsonStr.substring(7);
      else if (jsonStr.startsWith('```')) jsonStr = jsonStr.substring(3);
      if (jsonStr.endsWith('```')) jsonStr = jsonStr.substring(0, jsonStr.length - 3);
      jsonStr = jsonStr.trim();

      try {
        const result = JSON.parse(jsonStr);
        const results = Array.isArray(result) ? result : (result.results || []);
        results.forEach(item => {
          if (item.id) allResultsMap.set(String(item.id), item);
          else allResultsMap.set(`${item.artist} - ${item.title}`, item);
        });
      } catch (parseError) {
        logToSheet_(`Batch Batch ${Math.floor(i / chunkSize) + 1} JSON Parse Error: ${parseError.message}. Snippet: ${jsonStr.slice(0, 50)}...`);
      }
    }

    logToSheet_(`Total results collected: ${allResultsMap.size}`);
    return allResultsMap.size > 0 ? allResultsMap : null;

  } catch (e) {
    logToSheet_('Gemini Chunked Analysis Error: ' + e.message + '\n' + e.stack);
    return null;
  }
}

/**
 * Gemini API 呼び出し用の内部関数 (Vertex AI API 互換)
 */
function callGeminiApi_(prompt) {
  const url = `https://generativelanguage.googleapis.com/v1/models/${GEMINI_CONFIG.MODEL_NAME}:generateContent?key=${GEMINI_CONFIG.API_KEY}`;
  const maxRetries = 5;
  let retryCount = 0;
  let backoffMs = 15000;

  const payload = {
    contents: [{
      parts: [{ text: prompt }]
    }],
    generationConfig: {
      temperature: 0.1,
      topP: 0.95,
      maxOutputTokens: 16384
    },
    safetySettings: [
      { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" },
    ]
  };

  const options = {
    method: 'post',
    contentType: 'application/json',
    payload: JSON.stringify(payload),
    muteHttpExceptions: true
  };

  while (retryCount < maxRetries) {
    const response = UrlFetchApp.fetch(url, options);
    const resCode = response.getResponseCode();
    const resText = response.getContentText();

    if (resCode === 200) {
      if (!resText) {
        logToSheet_("Gemini API Error: Empty response text");
        return null;
      }
      const resJson = JSON.parse(resText);
      if (!resJson.candidates || !resJson.candidates[0].content || !resJson.candidates[0].content.parts) {
        logToSheet_("Gemini API Error: Unexpected response structure : " + resText);
        return null;
      }
      
      // トークン使用量の記録
      if (resJson.usageMetadata && resJson.usageMetadata.totalTokenCount) {
        updateApiUsage_('Gemini', resJson.usageMetadata.totalTokenCount);
      } else {
        updateApiUsage_('Gemini', 0); // Count request even if tokens missing
      }
      
      return resJson.candidates[0].content.parts[0].text;
    }

    if (resCode === 429 || resCode === 500 || resCode === 503 || resCode === 504) {
      const msg = `API混雑または一時的なエラー (Code: ${resCode}, Retry ${retryCount + 1}/${maxRetries}): ${backoffMs / 1000}秒待機します...`;
      SpreadsheetApp.getActiveSpreadsheet().toast(msg, 'Gemini AI', 10);
      logToSheet_(`Gemini API ${resCode} (Retry ${retryCount + 1}/${maxRetries}): Waiting ${backoffMs}ms... Error: ${resText.slice(0, 200)}`);
      Utilities.sleep(backoffMs);
      retryCount++;
      backoffMs *= 2;
      if (backoffMs > 60000) backoffMs = 60000; // Cap backoff at 60s
      continue;
    }

    logToSheet_(`Gemini API Error (${resCode}) at ${url.split('?')[0]}: ${resText}`);
    return null; // Non-retryable error
  }

  logToSheet_("Gemini API Error: Max retries reached for 429.");
  return null;
}

/**
 * AI設定の状態を確認し、ログに出力する。
 */
function checkAiConfiguration() {
  const key = PropertiesService.getScriptProperties().getProperty('GEMINI_API_KEY');
  if (!key) {
    Logger.log('❌ GEMINI_API_KEY が設定されていません。Project Settings > Script Properties に追加してください。');
  } else {
    Logger.log('✅ GEMINI_API_KEY は設定されています (末尾: ...' + key.slice(-4) + ')');
    testListModels(); // 通信テスト
  }
}

/**
 * 利用可能なモデル一覧をログに出力し、APIキーの有効性をテスト。
 */
function testListModels() {
  // モデル一覧取得は v1beta のみサポート
  const url = `https://generativelanguage.googleapis.com/v1/models?key=${GEMINI_CONFIG.API_KEY}`;
  try {
    const response = UrlFetchApp.fetch(url, { muteHttpExceptions: true });
    const code = response.getResponseCode();
    const content = response.getContentText();
    if (code === 200) {
      const json = JSON.parse(content);
      const names = json.models.map(m => m.name.replace('models/', ''));
      Logger.log('【診断】利用可能なモデル一覧: ' + names.join(', '));
      Logger.log('【アドバイス】もし gemini-1.5-flash が無い場合は、上記リストにあるモデル名を PickSongs.gs の GEMINI_CONFIG.MODEL_NAME に設定してください。');
    } else {
      Logger.log(`❌ モデル一覧の取得に失敗 (Code: ${code}): ${content}`);
    }
  } catch (e) {
    Logger.log(`❌ 通信エラー: ${e.message}`);
  }
}

function runTestGen() { logToSheet_("testGen: " + callGeminiApi_("Translate Hello to Japanese.")); }

function debugTop5HeatScore() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const shSnap = ss.getSheetByName(CFG.SHEET_SNAPSHOT);
  const snap = shSnap.getDataRange().getValues();
  if (snap.length < 2) return;

  const tz = Session.getScriptTimeZone();
  const toDateKey = (v) => toDateKey_(v, tz);

  const dateSet = new Set();
  for (let i = 1; i < snap.length; i++) {
    const dk = toDateKey(snap[i][0]);
    if (dk) dateSet.add(dk);
  }
  const dates = Array.from(dateSet).sort();
  if (dates.length < 2) return;
  const latestDate = dates[dates.length - 1];

  let baseDate = dates[dates.length - 2]; // For daily

  const LMap = new Map();
  const BMap = new Map();

  for (let i = 1; i < snap.length; i++) {
    const dt = toDateKey(snap[i][0]);
    const id = String(snap[i][1]).trim();
    const v = Number(snap[i][2]) || 0;
    const l = Number(snap[i][3]) || 0;
    const c = Number(snap[i][4]) || 0;

    if (dt === latestDate) LMap.set(id, { v, l, c });
    if (dt === baseDate) BMap.set(id, { v, l, c });
  }

  let shRank = ss.getSheetByName('TEST_RANKING');
  if (!shRank) {
    shRank = ss.getSheetByName('DailyRanking');
  }
  if (!shRank) {
    logToSheet_("ERROR: Neither TEST_RANKING nor DailyRanking sheet found.");
    return;
  }
  const rankData = shRank.getDataRange().getValues();
  const topIds = [];
  for (let i = 1; i <= 5; i++) {
    if (rankData[i] && rankData[i][22]) {
      topIds.push(rankData[i][22].trim()); // videoId is in col 23 (index 22)
    }
  }

  logToSheet_("=== HEAT SCORE MATH DEGUG ===");
  topIds.forEach((id, idx) => {
    const L = LMap.get(id);
    let B = BMap.get(id);

    // If no baseline from snap, assume 0 for exact fresh track scenario
    if (!B) B = { v: 0, l: 0, c: 0 };

    const dvRaw = L.v - B.v;
    const dlRaw = L.l - B.l;
    const dcRaw = L.c - B.c;

    const dv = Math.max(0, dvRaw);
    const dl = Math.max(0, dlRaw);
    const dc = Math.max(0, dcRaw);

    const scale = 1 + (Math.log10(L.v + 1) / 10);

    const heat_dv = 5 * Math.log(dv + 1) * scale;
    const heat_dl = 3 * Math.log(dl + 1);
    const heat_dc = 5 * Math.log(dc + 1);

    const heat = heat_dv + heat_dl + heat_dc;

    logToSheet_(`Rank ${idx + 1}: [${id}]`);
    logToSheet_(`- L.v/l/c = ${L.v}/${L.l}/${L.c} | B.v/l/c = ${B.v}/${B.l}/${B.c}`);
    logToSheet_(`- dv/dl/dc = ${dv}/${dl}/${dc}`);
    logToSheet_(`- scale(log(L.v+1)) = ${scale.toFixed(4)}`);
    logToSheet_(`- heat_dv = ${heat_dv.toFixed(4)} | heat_dl = ${heat_dl.toFixed(4)} | heat_dc = ${heat_dc.toFixed(4)}`);
    logToSheet_(`- Total Heat = ${heat.toFixed(4)}`);
  });
}

/**
 * 動画のコメントを最大100件取得してテキストとして返す
 * @param {string} videoId 
 * @returns {string} 各コメントを改行で繋いだテキスト
 */
function fetchComments_(videoId) {
  let comments = [];
  let nextPageToken = null;

  try {
    // 1ページ最大50件 × 1回 = 50件取得 (実行時間短縮のため100件から50件に制限)
    for (let i = 0; i < 1; i++) {
      const options = {
        videoId: videoId,
        maxResults: 50,
        order: 'relevance'
      };
      if (nextPageToken) options.pageToken = nextPageToken;

      const res = YouTube.CommentThreads.list('snippet', options);
      updateApiUsage_('YouTube', 1); // 1 unit
      if (!res || !res.items || res.items.length === 0) break;

      res.items.forEach(it => {
        comments.push(it.snippet.topLevelComment.snippet.textDisplay);
      });

      nextPageToken = res.nextPageToken;
      if (!nextPageToken) break;
    }

    if (comments.length === 0) return "";

    // AIへの送信データを5000文字程度に拡大し、より多くのサンプルで判定を安定させる
    return comments
      .join("\n")
      .slice(0, 5000);
  } catch (e) {
    Logger.log(`Comment Fetch Error [${videoId}]: ${e.message}`);
    return "";
  }
}

// System Initialization Log
logToSheet_('SYSTEM: Notification log recording pushed and active from ' + new Date().toLocaleString());
/**
 * デイリーランキングの空いているAIインサイト部分のみを補完（修復）する
 */
function repairDailyAiInsights() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const shRank = ss.getSheetByName(CFG.SHEET_RANKING_DAILY);
  if (!shRank) return;

  const data = shRank.getDataRange().getValues();
  if (data.length < 2) return;

  const logs = [];
  const toRepair = [];
  
  // A:日付, B:順位, C:Prev, D:Artist, E:Title, F:Pub, G:Spark, H:AIScore(8), I:Insight(9), J:Short(10), K:Genre(11), L:Visual(12)... W:videoId(23)
  for (let i = 1; i < data.length; i++) {
    const aiInsight = String(data[i][8]).trim(); // AIScore が '-' か空なら対象
    if (aiInsight === '-' || aiInsight === '') {
      toRepair.push({
        row: i + 1,
        id: data[i][23],
        artist: data[i][3],
        title: data[i][4],
        rank: data[i][1],
        prevRank: data[i][2] === '-' ? 100 : parseInt(data[i][2]),
        views: data[i][17] // dv
      });
    }
  }

  if (toRepair.length === 0) {
    SpreadsheetApp.getUi().alert('修復が必要な箇所（AI空欄）は見つかりませんでした。');
    return;
  }

  logToSheet_(`AI修復を開始します: ${toRepair.length}件`);
  SpreadsheetApp.getActiveSpreadsheet().toast(`${toRepair.length}件のAI分析を修復中...`, 'AI Repair');

  // AI分析用にコンテキストを整形
  const candidatesForAi = toRepair.map(r => ({
    id: r.id,
    rank: r.rank,
    prevRank: r.prevRank,
    artist: r.artist,
    title: r.title,
    views: r.views,
    heat: 100, // Dummy
    growth: 0.1 // Dummy
  }));

  const aiResults = analyzeRankingWithAi(candidatesForAi, 'Daily (Repair)');
  if (!aiResults) {
    SpreadsheetApp.getUi().alert('AI分析（修復）に失敗しました。時間をおいて再度お試しください。');
    return;
  }

  let successCount = 0;
  toRepair.forEach(item => {
    const aiData = aiResults.get(String(item.id)) || aiResults.get(`${item.artist} - ${item.title}`);
    if (aiData) {
      // H:AIScore(8), I:Insight(9), J:Short(10), K:Genre(11), L:Visual(12)
      const values = [
        [
          aiData.aiScore || aiData.aiscore || 50,
          aiData.insight || aiData.aiInsight || '-',
          aiData.shortInsight || aiData.shortinsight || '-',
          aiData.genre || '-',
          aiData.visualConcept || '-'
        ]
      ];
      shRank.getRange(item.row, 8, 1, 5).setValues(values);
      successCount++;
    }
  });

  logToSheet_(`AI修復完了: ${successCount}/${toRepair.length}件`);
  SpreadsheetApp.getUi().alert(`✅ AI修復が完了しました！\n\n正常に補完: ${successCount}件\n失敗: ${toRepair.length - successCount}件`);
}
