/***************
 * PickSongs.gs
 * 役割:
 *  - updateSongs(): Artists から各チャンネルの直近60日動画を探索 → 条件合格のみ SONGS に追加
 *  - generateRanking(): SNAPSHOT の差分でランキングを出力（汎用化）
 *  - autoGenerateDailyRanking(): 1日差分で RANKING_DAILY を生成
 *  - autoGenerateWeeklyRanking(): 7日差分で RANKING_WEEKLY を生成
 *
 * 前提:
 *  - Advanced Google services: YouTube Data API を ON
 ***************/

const CFG = {
  SHEET_ARTISTS: 'Artists',
  SHEET_SONGS: 'SONGS',
  SHEET_SNAPSHOT: 'SNAPSHOT',
  SHEET_RANKING_DAILY: 'RANKING_DAILY',
  SHEET_RANKING_WEEKLY: 'RANKING_WEEKLY',
  SHEET_RANKING_LONG: 'RANKING_LONG',
  SHEET_RANKING_AI_TEST: 'RANKING_AI_TEST',
  SHEET_SONGS_LONG: 'SONGS_LONG',
  SHEET_RANK_HISTORY_LIST: 'RANK_HISTORY_LIST', 

  // SONGS列: A videoId / B artist / C title / D publishedAt
  SONGS_COLS: { videoId: 0, artist: 1, title: 2, publishedAt: 3 },

  // Artists列（あなたのシートに合わせる）
  // A:Artist Name / B:YouTube URL / C:Channel ID / D:Subscribers / E:Facebook / F:Role (P for Production)
  ART_COLS: { name: 0, youtubeUrl: 1, channelId: 2, subscribers: 3, facebook: 4, role: 5, lastSync: 6, deepSearch: 7 },

  LOOKBACK_DAYS_SONGS: 60,   // 新曲収集の対象期間
  LOOKBACK_DAYS_RANK: 7,     // ランキング差分期間
  MIN_VIEWS: 0,              // 再生数制限を解除（新着を即座に拾う）
  MIN_AGE_DAYS: 0,           // 公開直後から対象
  MIN_DURATION_SEC: 61,      // Shorts除外（<=60秒を除外）

  // タイトル除外（必要なら追加）
  NG_WORDS: [
    'teaser', 'trailer', 'preview', 'behind', 'making',
    'version', 'ver.', 'live', 'performance',
    'dance practice', 'karaoke', 'remix'
  ],

  // 取得上限（チャンネル1つあたり）
  MAX_SEARCH_RESULTS_PER_CHANNEL: 25, // 直近から最大25本チェック（十分）
};

/**
 * アーティスト全員の新曲探索（超高速・クォータ最適化版）
 * 120名以上のアーティストを数分ではなく数十秒で処理します。
 */
function updateSongs() {
  logToSheet_('【実行】updateSongs 開始 (超高速バッチ版)');
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const shA = ss.getSheetByName(CFG.SHEET_ARTISTS);
  const shS = ss.getSheetByName(CFG.SHEET_SONGS);
  if (!shA || !shS) throw new Error('Required sheets not found');

  ensureSongsHeader_(shS);
  const initialRowCount = shS.getLastRow();

  // 1. 既存 videoId セットの構築
  const songData = shS.getDataRange().getValues();
  const shSongsLong = ss.getSheetByName(CFG.SHEET_SONGS_LONG);
  const songsLongData = shSongsLong ? shSongsLong.getDataRange().getValues() : [];
  
  const existing = new Set();
  for (let i = 1; i < songData.length; i++) {
    const id = String(songData[i][CFG.SONGS_COLS.videoId] || '').trim();
    if (id) existing.add(id);
  }
  for (let i = 1; i < songsLongData.length; i++) {
    const id = String(songsLongData[i][0] || '').trim();
    if (id) existing.add(id);
  }

  // 2. アーティストリストの読み込み
  const artists = shA.getDataRange().getValues();
  const targets = [];
  for (let i = 1; i < artists.length; i++) {
    const name = String(artists[i][CFG.ART_COLS.name] || '').trim();
    const channelId = String(artists[i][CFG.ART_COLS.channelId] || '').trim();
    const isDeepSearch = String(artists[i][CFG.ART_COLS.deepSearch] || '').toUpperCase() === 'TRUE';
    if (name && channelId) {
      targets.push({ name, channelId, rowIndex: i, isDeepSearch });
    }
  }

  const plTargets = targets.filter(t => !t.isDeepSearch);
  const dsTargets = targets.filter(t => t.isDeepSearch);

  Logger.log(`Processing ${targets.length} artists (${dsTargets.length} Deep Search, ${plTargets.length} Playlist).`);
  const allVideoIdsToFetch = new Map(); // videoId -> artistInfo

  // 3. 【最適化】Channel ID から Uploads Playlist ID と登録者数を一括取得 (50件ずつ)
  const channelToPlaylist = new Map();
  const targetIds = targets.map(t => t.channelId);
  const channelIdToRowIndex = new Map();
  targets.forEach(t => channelIdToRowIndex.set(t.channelId, t.rowIndex));
  
  for (const chunk of chunk_(targetIds, 50)) {
    try {
      const res = YouTube.Channels.list('contentDetails,statistics', { id: chunk.join(',') });
      updateApiUsage_('YouTube', 1);
      if (res && res.items) {
        res.items.forEach(item => {
          // Playlist ID
          if (item.contentDetails && item.contentDetails.relatedPlaylists) {
            const pid = item.contentDetails.relatedPlaylists.uploads;
            if (pid) channelToPlaylist.set(item.id, pid);
          }
          // Subscriber Count Update
          if (item.statistics && item.statistics.subscriberCount) {
            const rIdx = channelIdToRowIndex.get(item.id);
            if (rIdx !== undefined && artists[rIdx]) {
              artists[rIdx][CFG.ART_COLS.subscribers] = parseInt(item.statistics.subscriberCount, 10);
            }
          }
        });
      }
    } catch (e) {
      Logger.log(`Batch Channels.list error: ${e.message}`);
    }
  }

  // 4. 各アーティストの最新動画 ID を収集
  const failures = [];
  let successCount = 0;

  // 4-1. Playlist targets
  for (const t of plTargets) {
    const playlistId = channelToPlaylist.get(t.channelId);
    let playlistVideoIds = [];

    if (playlistId) {
      try {
        const plist = YouTube.PlaylistItems.list('contentDetails', {
          playlistId: playlistId,
          maxResults: 20 // 最新20件で十分
        });
        updateApiUsage_('YouTube', 1);
        if (plist && plist.items) {
          plist.items.forEach(it => playlistVideoIds.push(it.contentDetails.videoId));
        }
        successCount++;
        // 同期成功時刻を記録
        if (artists[t.rowIndex]) {
          artists[t.rowIndex][CFG.ART_COLS.lastSync] = new Date();
        }
      } catch (e) {
        Logger.log(`Playlist error for ${t.name}: ${e.message}`);
        failures.push(`${t.name} (Playlist Error)`);
      }
    } else {
       failures.push(`${t.name} (No Uploads Playlist)`);
    }

    // 重複を弾いて「詳細取得待ち」に送る
    playlistVideoIds.forEach(vid => {
      if (!existing.has(vid)) {
        allVideoIdsToFetch.set(vid, { name: t.name, channelId: t.channelId });
      }
    });
  }

  // 4-2. Deep Search targets
  for (const t of dsTargets) {
    try {
      const searchRes = YouTube.Search.list('snippet', {
        channelId: t.channelId,
        maxResults: 15,
        order: 'date',
        type: 'video'
      });
      updateApiUsage_('YouTube', 100);
      
      let searchVideoIds = [];
      if (searchRes && searchRes.items) {
          searchRes.items.forEach(it => searchVideoIds.push(it.id.videoId));
      }
      successCount++;
      // 同期成功時刻を記録
      if (artists[t.rowIndex]) {
        artists[t.rowIndex][CFG.ART_COLS.lastSync] = new Date();
      }
      
      // 重複を弾いて「詳細取得待ち」に送る
      searchVideoIds.forEach(vid => {
        if (!existing.has(vid)) {
          allVideoIdsToFetch.set(vid, { name: t.name, channelId: t.channelId });
        }
      });
    } catch(e) {
      Logger.log(`Search error for ${t.name}: ${e.message}`);
      failures.push(`${t.name} (Search Error)`);
    }
  }

  // 5. 【最適化】全アーティストの未登録動画の詳細を一括取得 (50件ずつ)
  const masterToAppend = [];
  const videoIdsArray = Array.from(allVideoIdsToFetch.keys());
  Logger.log(`Fetching details for ${videoIdsArray.length} potential new songs...`);

  for (const chunk of chunk_(videoIdsArray, 50)) {
    try {
      const vids = YouTube.Videos.list('snippet,contentDetails,statistics', {
        id: chunk.join(','),
        maxResults: chunk.length
      });
      updateApiUsage_('YouTube', 1);

      if (vids && vids.items) {
        vids.items.forEach(v => {
          const artistInfo = allVideoIdsToFetch.get(v.id);
          const row = validateAndCreateSongRow_(v, artistInfo);
          if (row) {
            masterToAppend.push(row);
            existing.add(v.id); // 即座に既存セットに加えて同一実行内重複を防止
          }
        });
      }
    } catch (e) {
      Logger.log(`Batch Videos.list error: ${e.message}`);
    }
  }

  // 6. 新曲を一括書き込み
  if (masterToAppend.length > 0) {
    shS.getRange(shS.getLastRow() + 1, 1, masterToAppend.length, 4).setValues(masterToAppend);
  }

  // 7. 期限切れ削除処理
  const deletedCount = pruneSongs60d_(shS, CFG.LOOKBACK_DAYS_SONGS);

  // 8. 最終集計と通知
  const addedCount = masterToAppend.length;
  let msg = `【報告】YouTubeデータ更新完了 (高速版)\n\n`;
  msg += `新規追加: ${addedCount} 曲\n`;
  msg += `期限切れ削除: ${deletedCount} 曲\n\n`;
  msg += `対象: ${targets.length} 名中 ${successCount} 名成功\n`;
  if (failures.length > 0) msg += `失敗: ${failures.length} 名 (詳細はログを確認)\n`;

  logToSheet_(`SYNC: Update cycle completed. Added: ${addedCount}, Deleted: ${deletedCount}`);
  sendTelegramNotification_(msg);

  // 9. 使用状況の反映とソート、およびアーティストシートの更新（同期時刻）
  flushApiUsage_();
  sortSongsSheet_(shS);

  // ヘッダーがなければ追加
  if (artists[0] && artists[0].length <= CFG.ART_COLS.lastSync) {
    artists[0][CFG.ART_COLS.lastSync] = "Last Sync";
  } else if (artists[0] && !artists[0][CFG.ART_COLS.lastSync]) {
    artists[0][CFG.ART_COLS.lastSync] = "Last Sync";
  }
  if (artists[0] && artists[0].length <= CFG.ART_COLS.deepSearch) {
    artists[0][CFG.ART_COLS.deepSearch] = "Deep Search";
  } else if (artists[0] && !artists[0][CFG.ART_COLS.deepSearch]) {
    artists[0][CFG.ART_COLS.deepSearch] = "Deep Search";
  }
  
  // 最大列数を確認して必要なら拡張
  const maxCols = Math.max(...artists.map(row => row.length));
  shA.getRange(1, 1, artists.length, maxCols).setValues(artists.map(row => {
    while(row.length < maxCols) row.push("");
    return row;
  }));
  
  Logger.log(`Finished. Added: ${addedCount}, Success: ${successCount}/${targets.length}`);
}

/**
 * デバッグ用: Artistsシートの一番上の行（VannDa想定）のみを対象に、
 * Search API を使って詳細ログを出しながら動画取得を試みる
 */
function updateVannDaOnly() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const shA = ss.getSheetByName(CFG.SHEET_ARTISTS);
  const shS = ss.getSheetByName(CFG.SHEET_SONGS);

  // 1行目 (データとしてはrow 2) を取得
  const name = String(shA.getRange(2, 1).getValue() || '').trim();
  const channelId = String(shA.getRange(2, 3).getValue() || '').trim();

  if (!channelId) {
    throw new Error('C列（Channel ID）が空です。同期機能を先に実行してください。');
  }

  Logger.log(`--- VannDa Target Debug Trace ---`);
  Logger.log(`Target: ${name} (ID: ${channelId})`);

  // 1. まず Search API で検索（最新動画を直接叩く）
  try {
    Logger.log(`Applying Search API strategy...`);
    const searchRes = YouTube.Search.list('snippet', {
      channelId: channelId,
      maxResults: 10,
      order: 'date',
      type: 'video'
    });
    updateApiUsage_('YouTube', 100);

    const ids = (searchRes.items || []).map(it => it.id.videoId);
    Logger.log(`Search found ${ids.length} videos: ${ids.join(', ')}`);

    if (ids.length > 0) {
      // 1行目デバッグ時はフィルタを無視して取得を試みる (force=true)
      processVideoIds_(ids, { name, channelId }, shS, null, true);
    }
  } catch (e) {
    Logger.log(`Search API Error: ${e.message}`);
  }

  Logger.log(`--- End Trace ---`);

  // 自動ソート
  sortSongsSheet_(shS);

  SpreadsheetApp.getUi().alert('VannDaの再探査とソートが完了しました。ログ（表示 > 実行ログ）を確認し、SONGSシートの最上部に曲が追加されたか見てください。');
}

/**
 * プロダクションおよび個人トップ20名のDeep Search設定を自動適用する
 */
function autoConfigureDeepSearch() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const shA = ss.getSheetByName(CFG.SHEET_ARTISTS);
  const shS = ss.getSheetByName(CFG.SHEET_SONGS);
  
  const artists = shA.getDataRange().getValues();
  const songs = shS.getDataRange().getValues();
  
  // Count songs per artist in SONGS sheet (current catalog size)
  const songCounts = new Map();
  for (let i = 1; i < songs.length; i++) {
    const artist = String(songs[i][CFG.SONGS_COLS.artist] || '').trim();
    if (artist) {
      songCounts.set(artist, (songCounts.get(artist) || 0) + 1);
    }
  }
  
  // Add 'Deep Search' header if missing
  if (artists[0].length <= CFG.ART_COLS.deepSearch) {
    artists[0][CFG.ART_COLS.deepSearch] = "Deep Search";
  } else if (!artists[0][CFG.ART_COLS.deepSearch]) {
    artists[0][CFG.ART_COLS.deepSearch] = "Deep Search";
  }
  
  // separate artists
  const individualStats = [];
  
  for (let i = 1; i < artists.length; i++) {
    const role = String(artists[i][CFG.ART_COLS.role] || '').trim().toUpperCase();
    const name = String(artists[i][CFG.ART_COLS.name] || '').trim();
    if (!name) continue;
    
    // Reset to FALSE first
    artists[i][CFG.ART_COLS.deepSearch] = false;
    
    if (role === 'P' || role === 'PRODUCTION') {
      artists[i][CFG.ART_COLS.deepSearch] = true;
    } else {
      // Individual
      individualStats.push({
        rowIndex: i,
        name: name,
        hits: songCounts.get(name) || 0
      });
    }
  }
  
  // Sort individuals by hits
  individualStats.sort((a, b) => b.hits - a.hits);
  
  // Top 20 individuals
  const top20 = individualStats.slice(0, 20);
  top20.forEach(stat => {
    artists[stat.rowIndex][CFG.ART_COLS.deepSearch] = true;
  });
  
  const top20Names = top20.map(s => `${s.name} (${s.hits})`).join('\\n');
  
  // Write back
  const maxCols = Math.max(...artists.map(row => row.length));
  shA.getRange(1, 1, artists.length, maxCols).setValues(artists.map(row => {
    while(row.length < maxCols) row.push("");
    return row;
  }));
  
  SpreadsheetApp.getUi().alert(`Deep Search設定完了\\n\\n全プロダクションと、楽曲数の多い個人トップ20名に確実なSearch方式（TRUE）を設定しました。\\n\\n【個人トップ20名 (曲数)】\\n${top20Names}`);
}

/**
 * IDリストから詳細情報を取得し、条件に合えばSONGSに追加する（内部共通関数）
 */
function processVideoIds_(ids, artistInfo, shS, existingSet, forceIgnoreFilters = false) {
  const now = new Date();

  // [最適化] 引数に Set があればそれを使う。なければ取得（後方互換性）
  let existing = existingSet;
  if (!existing) {
    const songs = shS.getDataRange().getValues();
    existing = new Set();
    for (let i = 1; i < songs.length; i++) {
      const id = String(songs[i][CFG.SONGS_COLS.videoId] || '').trim();
      if (id) existing.add(id);
    }
  }

  const vids = YouTube.Videos.list('snippet,contentDetails,statistics', {
    id: ids.join(','),
    maxResults: ids.length
  });
  updateApiUsage_('YouTube', 1); // 1 unit

  const toAppend = [];
  const vitems = (vids && vids.items) ? vids.items : [];

  for (const v of vitems) {
    if (existing.has(v.id)) {
      Logger.log(`[${v.snippet.title}] Already exists in SONGS. Skip.`);
      continue;
    }

    const title = String(v.snippet.title || '').trim();
    const publishedAt = v.snippet.publishedAt || '';
    const categoryId = String(v.snippet.categoryId || '');
    const viewCount = Number(v.statistics.viewCount || 0);
    const durSec = iso8601DurationToSeconds_(v.contentDetails.duration || 'PT0S');

    if (!forceIgnoreFilters) {
      // フィルタリング（デバッグ用に詳細ログ出し）
      if (viewCount < CFG.MIN_VIEWS) {
        Logger.log(`Skipped [${title}]: Low views (${viewCount})`);
        continue;
      }

      if (categoryId !== '10' && categoryId !== '24' && categoryId !== '22') {
        Logger.log(`Skipped [${title}]: Category ${categoryId} (Not Music/Ent/Blog)`);
        continue;
      }

      if (durSec < CFG.MIN_DURATION_SEC) {
        Logger.log(`Skipped [${title}]: Is Short (${durSec}s)`);
        continue;
      }

      const pub = new Date(publishedAt);
      const ageDays = (now - pub) / (1000 * 60 * 60 * 24);
      if (ageDays > CFG.LOOKBACK_DAYS_SONGS) {
        Logger.log(`Skipped [${title}]: Too old (${ageDays.toFixed(1)} days)`);
        continue;
      }
    } else {
      Logger.log(`Force matching [${title}] (Debugging mode)`);
    }

    // 合格（原本データ保護のため、SONGSシートにはクリーンアップせずそのまま保存）
    // 曲名にYouTubeへのハイパーリンクを付与 (スプレッドシート上)
    const videoUrl = "https://www.youtube.com/watch?v=" + v.id;
    const linkedTitle = '=HYPERLINK("' + videoUrl + '", "' + title.replace(/"/g, '""') + '")';
    toAppend.push([v.id, artistInfo.name, linkedTitle, publishedAt]);
    Logger.log(`✅ MATCHED: [${title}]`);
  }

  if (toAppend.length) {
    shS.getRange(shS.getLastRow() + 1, 1, toAppend.length, 4).setValues(toAppend);

    // [重要] 1回の実行中に複数アーティストが同じ動画 ID を持っていた場合の重複を防ぐため
    // メモリ上の existing セットにも即座に追加
    if (existing) {
      toAppend.forEach(row => existing.add(row[0]));
    }

    Logger.log(`Added ${toAppend.length} songs to SONGS sheet (and updated memory set).`);
  }
}

/**
 * 毎日自動的に実行されるデイリーランキング生成 + Facebook投稿
 * ※ トリガー消失に備え、ランキング生成後に直接FB投稿も呼び出す設計。
 */
function autoGenerateDailyRanking() {
  const tz = Session.getScriptTimeZone();
  const todayKey = Utilities.formatDate(new Date(), tz, 'yyyy-MM-dd');
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sh = ss.getSheetByName(CFG.SHEET_RANKING_DAILY);
  
  // 今日すでに生成済みかチェック
  if (sh && sh.getLastRow() > 1) {
    const firstDate = sh.getRange(2, 1).getValue();
    const firstDateStr = (firstDate instanceof Date) ? Utilities.formatDate(firstDate, tz, 'yyyy-MM-dd') : String(firstDate).split(' ')[0];
    if (firstDateStr === todayKey) {
      logToSheet_('autoGenerateDailyRanking: スキップ - 本日分は既に生成済みです (' + todayKey + ')');
      return;
    }
  }

  sendTelegramNotification_('【実行】Dailyランキング作成開始');
  try {
    generateRanking(1, CFG.SHEET_RANKING_DAILY);
    logToSheet_('【完了】autoGenerateDailyRanking');
  } catch (e) {
    Logger.log('Error in autoGenerateDailyRanking: ' + e.message);
    if (typeof sendTelegramNotification_ === 'function') {
      sendTelegramNotification_('⚠️ 【エラー】デイリーランキング自動作成に失敗しました。\nエラー内容:\n' + e.toString());
    }
    return; // ランキング生成に失敗した場合はFB投稿もスキップ
  }

  // ロングヒットランキングも併せて生成
  try {
    generateRanking(1, CFG.SHEET_RANKING_LONG);
  } catch (e) {
    Logger.log('Error in generateRanking(LONG): ' + e.message);
  }

  // キャッシュを更新する
  if (typeof updateRankingCache === 'function') {
    updateRankingCache();
  }

  logToSheet_('SYSTEM: ランキング生成完了（Facebook投稿は20:30の定時トリガーで行われます）');
}

/**
 * デイリーランキングをFacebookに投稿するトリガー用関数
 * ※ autoGenerateDailyRanking 内でのフォールバック投稿が失敗した場合の
 *    バックアップとして機能します。本日すでに投稿済みの場合はスキップします。
 */
function autoPostDailyRankingToFacebook() {
  logToSheet_('【実行】autoPostDailyRankingToFacebook 開始');

  // 本日すでに投稿済みか確認、および今日のランキングが生成済みか確認
  try {
    const tz = Session.getScriptTimeZone();
    const todayStr = Utilities.formatDate(new Date(), tz, 'yyyy.MM.dd');
    const todayKey = Utilities.formatDate(new Date(), tz, 'yyyy-MM-dd'); 
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    
    // 1. 今日のランキングが生成されているか確認 (RANKING_DAILY)
    const rankingSheet = ss.getSheetByName(CFG.SHEET_RANKING_DAILY);
    let isTodayGenerated = false;
    
    if (rankingSheet && rankingSheet.getLastRow() > 1) {
      const firstDataDate = rankingSheet.getRange(2, 1).getValue(); 
      const firstDataDateStr = (firstDataDate instanceof Date) ? 
        Utilities.formatDate(firstDataDate, tz, 'yyyy-MM-dd') : String(firstDataDate).split(' ')[0];
      
      if (firstDataDateStr === todayKey) {
        isTodayGenerated = true;
      }
    }

    // 今日の分がなければ、強制的に生成を実行する
    if (!isTodayGenerated) {
      logToSheet_('autoPostDailyRankingToFacebook: 今日のランキングが未生成のため、強制生成を開始します...');
      sendTelegramNotification_('🕒 FB投稿前に今日のランキングを最新化しています (AI解析完了を待つため、投稿自体は15分後に延期予約されました)...');
      autoGenerateDailyRanking();
      
      logToSheet_('15分後のFB投稿(autoPostToFacebook)を予約して、現在のプロセスを終了します。');
      ScriptApp.newTrigger('autoPostToFacebook')
          .timeBased()
          .after(15 * 60 * 1000) // 15分後 (AI処理の余裕確保)
          .create();
      return; // この実行はここで終了し、投稿プロセスへは進まない
    }

    // 2. 二重投稿防止チェック
    const logSheet = ss.getSheetByName('DEBUG_LOG');
    if (logSheet) {
      const lastRow = logSheet.getLastRow();
      const checkRows = Math.min(50, lastRow - 1);
      if (checkRows > 0) {
        const recentLogs = logSheet.getRange(lastRow - checkRows + 1, 2, checkRows, 1).getValues();
        const alreadyPosted = recentLogs.some(row => 
          String(row[0]).includes('【成功】Facebook自動投稿完了') && String(row[0]).includes(todayStr)
        );
        if (alreadyPosted) {
          logToSheet_('autoPostDailyRankingToFacebook: 本日(' + todayStr + ')はすでに投稿済みのためスキップします。');
          return;
        }
      }
    }
  } catch (checkErr) {
    logToSheet_('事前チェックエラー (続行します): ' + checkErr.message);
  }

  try {
    if (typeof autoPostToFacebook === 'function') {
      autoPostToFacebook();
    } else {
      throw new Error('autoPostToFacebook function not found');
    }
  } catch (e) {
    logToSheet_('Error in autoPostDailyRankingToFacebook: ' + e.message);
    if (typeof sendTelegramNotification_ === 'function') {
      sendTelegramNotification_('⚠️ 【エラー】Facebook自動投稿プロセス中にエラーが発生しました。\nエラー内容:\n' + e.toString());
    }
  }
}

/**
 * 手動で本番のデイリーランキングを安全に更新する関数（Facebookへの自動投稿は行わない）
 */
function updateLiveRankingNoFb() {
  Logger.log('--- 手動更新スタート (Facebook投稿なし) ---');
  generateRanking(1, CFG.SHEET_RANKING_DAILY);
  Logger.log('--- 手動更新完了 ---');
}
/**
 * 毎週自動的に実行されるウィークリーランキング生成
 */
function autoGenerateWeeklyRanking() {
  logToSheet_('【実行】autoGenerateWeeklyRanking 開始');
  generateRanking(7, CFG.SHEET_RANKING_WEEKLY);
  // Weekly のタイミングでも LongRanking を更新（差分は1日分でOKな場合が多いが、整合性のため）
  generateRanking(1, CFG.SHEET_RANKING_LONG);

  // キャッシュを更新する
  if (typeof updateRankingCache === 'function') {
    updateRankingCache();
  }
}


/**
 * 【実験用】AIのみのロジックでランキングを生成し、別シートに出力する
 */
function generateAiTestRanking() {
  logToSheet_('【実行】AIランキング試作（実験）開始');
  try {
    generateRanking(1, CFG.SHEET_RANKING_AI_TEST);
    SpreadsheetApp.getUi().alert(`完了: ${CFG.SHEET_RANKING_AI_TEST} シートを更新しました。純粋な再生数とバズをベースにした実験ランキングの骨格が出力されました。`);
  } catch (e) {
    Logger.log('AI Test Ranking Error: ' + e);
  }
}

/**
 * 汎用ランキング生成エンジン
 * @param {number} lookbackDays 遡る日数 (1 = Daily, 7 = Weekly)
 * @param {string} targetSheetName 出力先シート名
 */
function generateRanking(lookbackDays, targetSheetName) {
  const TOP_N = 20;
  const LOOKBACK_DAYS = lookbackDays || CFG.LOOKBACK_DAYS_RANK;

  const ss = SpreadsheetApp.getActiveSpreadsheet();
  logToSheet_(`【開始】generateRanking (${targetSheetName}, lookback: ${LOOKBACK_DAYS}日)`);

  const shArtists = ss.getSheetByName(CFG.SHEET_ARTISTS);
  const shSongs = ss.getSheetByName(CFG.SHEET_SONGS);
  const shSongsLong = ss.getSheetByName(CFG.SHEET_SONGS_LONG) || ss.insertSheet(CFG.SHEET_SONGS_LONG);
  const shSnap = ss.getSheetByName(CFG.SHEET_SNAPSHOT);
  const shRank = ss.getSheetByName(targetSheetName) || ss.insertSheet(targetSheetName);

  // SONGS_LONG のヘッダー確認
  ensureSongsHeader_(shSongsLong);

  // 【視認性改善】列構造を強制更新
  const currentHeaders = shRank.getLastRow() > 0 ? shRank.getRange(1, 1, 1, Math.max(shRank.getLastColumn(), 1)).getValues()[0].map(h => String(h).trim()) : [];
  const hasGenre = currentHeaders.includes('Genre');
  const hasVisual = currentHeaders.includes('Visual Concept');
  const hasShortInsight = currentHeaders.includes('shortInsight');
  const hasLikes = currentHeaders.includes('今日いいね');
  const hasComments = currentHeaders.includes('今日コメ');

  // ヘッダーが最新かチェック (27列に増えたため、不足している場合は再構築)
  const isHeaderOld = !hasLikes || !hasComments || currentHeaders.length < 27 || !hasGenre || !hasVisual || !hasShortInsight;

  if (isHeaderOld) {
    logToSheet_('RANKING sheet header is outdated. Updating to 27-column format...');
    const colName = lookbackDays === 1 ? 'トレンド(1d)' : 'トレンド(7d)';
    const diffColName = lookbackDays === 1 ? '増加数(1d)' : '増加数(7d)';
    const prevColName = lookbackDays === 1 ? '1日前' : '7日前';

    const newHeaders = [
      '日付', '順位', 'PrevRank', 'アーティスト', '曲名', '公開日', colName,
      'AIスコア', 'AI理由', 'AIインサイト', 'shortInsight', 'Genre', 'Visual Concept',
      'Heatスコア', 'コメ品質', '成長率(%)', '反応率', diffColName, '今日いいね', '今日コメ', '現在再生数', prevColName,
      'YouTube', 'Facebook', '備考', 'videoId', 'historyRaw'
    ];
    shRank.getRange(1, 1, 1, newHeaders.length).setValues([newHeaders]);
    Logger.log(`RANKING sheet header updated safely.`);
  }

  const tz = Session.getScriptTimeZone();

  const toDateKey = (v) => toDateKey_(v, tz);
  const toId = (v) => String(v || '').trim();

  // Artists A:Name / D:Subscribers / E:Facebook URL / F:Role
  const artists = shArtists.getDataRange().getValues();
  const metaByArtist = new Map();
  for (let i = 1; i < artists.length; i++) {
    const name = String(artists[i][CFG.ART_COLS.name] || '').trim();
    const subs = parseInt(artists[i][CFG.ART_COLS.subscribers] || 0, 10);
    const fb = String(artists[i][CFG.ART_COLS.facebook] || '').trim();
    const role = String(artists[i][CFG.ART_COLS.role] || '').trim().toUpperCase();
    if (name) metaByArtist.set(name, { subs, fb, role });
  }

  // 【品質反映準備】既存のシートから前回の「コメ品質」を読み込む
  const prevRankData = shRank.getDataRange().getValues();
  const headers = prevRankData[0];
  const vidIdx = headers.indexOf('videoId');
  const qIdx = headers.indexOf('コメ品質');
  const qualityMap = new Map();
  if (vidIdx !== -1 && qIdx !== -1) {
    for (let i = 1; i < prevRankData.length; i++) {
      const vid = String(prevRankData[i][vidIdx] || '').trim();
      const qVal = String(prevRankData[i][qIdx] || '').replace('%', '');
      if (vid) qualityMap.set(vid, (parseFloat(qVal) || 100) / 100);
    }
  }

  // SONGS: videoId -> meta
  const songs = shSongs.getDataRange().getValues();
  const songById = new Map();
  for (let i = 1; i < songs.length; i++) {
    const videoId = toId(songs[i][CFG.SONGS_COLS.videoId]);
    if (!videoId) continue;
    songById.set(videoId, {
      artist: String(songs[i][CFG.SONGS_COLS.artist] || '').trim(),
      title: String(songs[i][CFG.SONGS_COLS.title] || '').trim(),
      publishedAt: songs[i][CFG.SONGS_COLS.publishedAt],
      isLongTerm: false,
      commUnique: qualityMap.get(videoId) || 1.0
    });
  }
  // SONGS_LONG も追加
  const songsLong = shSongsLong.getDataRange().getValues();
  for (let i = 1; i < songsLong.length; i++) {
    const videoId = toId(songsLong[i][CFG.SONGS_COLS.videoId]);
    if (!videoId) continue;
    songById.set(videoId, {
      artist: String(songsLong[i][CFG.SONGS_COLS.artist] || '').trim(),
      title: String(songsLong[i][CFG.SONGS_COLS.title] || '').trim(),
      publishedAt: songsLong[i][CFG.SONGS_COLS.publishedAt],
      isLongTerm: true,
      commUnique: qualityMap.get(videoId) || 1.0
    });
  }

  // SNAPSHOT日付集合
  const snap = shSnap.getDataRange().getValues();
  if (snap.length < 2) throw new Error('SNAPSHOT empty');

  const dateSet = new Set();
  for (let i = 1; i < snap.length; i++) {
    const dk = toDateKey(snap[i][0]);
    if (dk) dateSet.add(dk);
  }
  const dates = Array.from(dateSet).sort();
  if (dates.length < 2) throw new Error('Need at least 2 snapshot dates');

  const latestDate = dates[dates.length - 1];
  const latestObj = new Date(latestDate + 'T00:00:00');

  // 目標：latest - 7日
  const target = new Date(latestObj);
  target.setDate(target.getDate() - LOOKBACK_DAYS);
  const targetKey = Utilities.formatDate(target, tz, 'yyyy-MM-dd');

  // targetKey以下で最大（=7日前に最も近い過去日）
  let baseDate = '';
  for (let i = dates.length - 1; i >= 0; i--) {
    if (dates[i] <= targetKey) { baseDate = dates[i]; break; }
  }
  if (!baseDate) baseDate = dates[0];

  // 7日間の履歴（スパークライン用）と最新・ベースの取得
  const latest = new Map();
  const base = new Map();
  const history = new Map(); // videoId -> Map(dateKey -> views)

  const last14Dates = dates.slice(-14);
  const relevantDates = new Set([latestDate, baseDate, ...last14Dates]);

  logToSheet_(`SNAPSHOT読込開始: ${snap.length} 行中、関連 ${relevantDates.size} 日分を抽出します...`);

  // 高速化のための事前変換：Service Callをループ外に出す
  const formattedRelevantDates = new Set();
  relevantDates.forEach(d => formattedRelevantDates.add(String(d)));

  // Optimized scan of SNAPSHOT (Avoid calling toDateKey_ inside loop)
  for (let i = snap.length - 1; i >= 1; i--) {
    const rawDate = snap[i][0];
    if (!rawDate) continue;

    // Date objectを高速に文字列変換 (Utilities.formatDateを使わない)
    let d;
    if (rawDate instanceof Date) {
      const year = rawDate.getFullYear();
      const month = ('0' + (rawDate.getMonth() + 1)).slice(-2);
      const day = ('0' + rawDate.getDate()).slice(-2);
      d = `${year}-${month}-${day}`;
    } else {
      d = String(rawDate).split(' ')[0]; // String date handling
    }

    if (!formattedRelevantDates.has(d)) continue;

    const id = toId(snap[i][1]);
    if (!songById.has(id)) continue;

    const v = +snap[i][2] || 0;
    const l = +snap[i][3] || 0;
    const c = +snap[i][4] || 0;
    const row = { v, l, c };

    if (d === latestDate) latest.set(id, row);
    if (d === baseDate) base.set(id, row);

    // History for sparklines (By Date mapping)
    if (!history.has(id)) history.set(id, new Map());
    history.get(id).set(d, v);
  }

  logToSheet_(`データ抽出完了: latestDate=${latestDate}, baseDate=${baseDate}, latestCount=${latest.size}, baseCount=${base.size}`);

  const now = new Date();
  const list = [];
  const isLongTermTarget = (targetSheetName === CFG.SHEET_RANKING_LONG);

  for (const [id, L] of latest.entries()) {
    let B = base.get(id);
    const meta = songById.get(id);
    if (!meta) continue;

    // ターゲットシートに応じてフィルタリング
    if (isLongTermTarget) {
      if (!meta.isLongTerm) continue; // LONGシート生成時は SONGS_LONG の曲のみ
    } else {
      if (meta.isLongTerm) continue; // メインランキング（Daily/Weekly）からは除外
    }

    const pub = (meta.publishedAt && !isNaN(new Date(meta.publishedAt).getTime())) ? new Date(meta.publishedAt) : null;

    // 【変更】0日から表示させるためのロジック緩和
    if (!B) {
      const isVeryNew = pub && (now - pub) / (1000 * 60 * 60 * 24) <= 3;
      if (isVeryNew) {
        B = { v: 0, l: 0, c: 0 };
        Logger.log(`[${meta.title}] Day-0/New: Using 0-baseline`);
      } else {
        const baseObj = new Date(baseDate + 'T00:00:00');
        if (pub && pub >= baseObj) {
          B = { v: 0, l: 0, c: 0 };
          Logger.log(`[${meta.title}] Catching New release: Using 0-baseline`);
        } else {
          continue; // 古い曲なのにベースがない場合はスキップ
        }
      }
    }

    if (pub && !meta.isLongTerm) {
      const daysSince = (now - pub) / (1000 * 60 * 60 * 24);
      if (daysSince < CFG.MIN_AGE_DAYS) continue;
      if (daysSince > CFG.LOOKBACK_DAYS_SONGS) continue;
    }

    // diffs（7日差分）
    const dvRaw = L.v - B.v;
    const dlRaw = L.l - B.l;
    const dcRaw = L.c - B.c;

    const dv = Math.max(0, dvRaw);
    const dl = Math.max(0, dlRaw);
    const dc = Math.max(0, dcRaw);

    // 累計再生数(L.v)による実績ボーナス (最大1.6倍程度)
    const scale = 1 + (Math.log10(L.v + 1) / 10);
    const artistMeta = metaByArtist.get(meta.artist) || { fb: '', role: '', subs: 0 };
    let heat = 0;

    // 追加指標の計算
    // [修正] ベースが0の場合のゼロ除算回避
    const growthRate = (B.v > 0) ? (dvRaw / B.v) : (dvRaw > 0 ? 1.0 : 0);
    const engagement = L.v > 0 ? (L.l + L.c) / L.v : 0;

    if (targetSheetName === CFG.SHEET_RANKING_AI_TEST) {
      // 【実験用: AIテストランキング】デイリー再生数(dv)を最優先のベースとし、登録者数等で補正する「物理量＋バズ重視」
      // 1. Base Score: 対数圧縮を弱め、一定回数(1万回等)ごとの線形加算を組み合わせる
      const baseViewScore = (10 * Math.log(dv + 1)) + (dv / 5000); 
      // 2. Modifiers (Likes & Comments): 反応による熱量加点
      const reactionBonus = (3 * Math.log(dl + 1)) + (5 * Math.log(dc + 1));
      // 3. Subscriber Baseline Adjustment: チャンネルサイズに応じた期待値との比較
      const subs = artistMeta.subs || 1000;
      const expectedViews = Math.max(100, subs * 0.05); // 登録者の5%を1日の期待値と仮定
      const performanceRatio = dv / expectedViews;
      const viralBonus = (performanceRatio > 1.0) ? Math.min(20, Math.log(performanceRatio) * 5) : 0; 

      heat = (baseViewScore * scale) + reactionBonus + viralBonus;
    } else {
      // 【通常用: Daily/Weekly】日毎の実数(Daily Views)の重みを底上げしつつ、勢いをスパイスとして加味
      // 1. 日毎の再生数（実数）に線形成分を少し加算 (1万再生 = 1pt) してログ圧縮を補正
      const dailyViewCore = (5 * Math.log(dv + 1)) + (dv / 10000);
      const baseViewScore = dailyViewCore * scale;
      
      // 2. 反応スコア (いいね: 3倍, コメント: 5倍)
      // [品質反映] 前回の品質スコア（commUnique）があれば、コメントのログ指数に掛け合わせる
      const qFactor = Math.min(1.0, Math.max(0.1, Number(meta.commUnique || 1.0)));
      const reactionScore = (3 * Math.log(dl + 1)) + (5 * Math.log(dc + 1) * qFactor);

      // 3. 勢い・密度のボーナス (最大5pt程度の補助的な加点に抑制)
      const momentumBonus = Math.min(5, growthRate * 5) + Math.min(5, engagement * 100);

      heat = baseViewScore + reactionScore + momentumBonus;
    }

    // 履歴Mapから配列を作成
    const vMap = history.get(id) || new Map();
    const vHistory = last14Dates.map(d => vMap.get(d)).filter(v => v !== undefined);

    // 日次増加幅の解析 (Momentum Drop検知用)
    let peakDailyDelta = 0;
    let latestDailyDelta = 0;
    if (vHistory.length >= 2) {
      const dailyDeltas = [];
      for (let i = 1; i < vHistory.length; i++) {
        dailyDeltas.push(Math.max(0, vHistory[i] - vHistory[i - 1]));
      }
      peakDailyDelta = Math.max(...dailyDeltas);
      latestDailyDelta = dailyDeltas[dailyDeltas.length - 1];
    }

    // スパークライン用の式 (直近最大7点)
    let sparkArr = vHistory.slice(-14);
    if (sparkArr.length <= 1 && B.v !== L.v) {
      sparkArr = [B.v || 0, L.v];
    }
    const sparkValues = sparkArr.join(',');
    const sparkFormula = sparkArr.length > 1 ? `=SPARKLINE({${sparkValues}}, {"charttype","line";"linewidth",2;"color","#1a73e8"})` : '-';

    // ⚠ 異常数値の検知ロジック (数値ベースのみ)
    let alert = '';
    let reason = '';

    if (dvRaw < 0) {
      alert = '⚠';
      reason = 'Abnormal view drop (Audit)';
    } else {
      if (growthRate > 3.0 && dvRaw > 50000) {
        alert = '⚡';
        reason = 'Abnormal view surge';
      }
      if (peakDailyDelta > 20000 && latestDailyDelta < peakDailyDelta * 0.2) {
        alert = (alert === '⚡' ? '⚡📉' : '📉');
        reason = (reason ? reason + ', ' : '') + 'Growth momentum drop';
      }
      if (dvRaw > 10000 && (dlRaw + dcRaw) / dvRaw < 0.001) {
        alert = (alert.includes('⚠') ? alert : alert + '⚠');
        reason = (reason ? reason + ', ' : '') + 'Low engagement for growth';
      }
    }

    // 以前の取得結果（artistMeta）をそのまま活用
    const fbUrl = artistMeta.fb;

    list.push({
      id,
      artist: meta.artist, 
      title: meta.title,   
      role: artistMeta.role,
      heat,
      dv: dvRaw,
      dl: dlRaw,
      dc: dcRaw,
      totalV: L.v,
      totalL: L.l,
      totalC: L.c,
      growth: growthRate,
      eng: engagement,
      commUnique: 1.0, 
      spark: sparkFormula,
      alert,
      reason,
      fbUrl,
      publishedAt: meta.publishedAt,
      isLongTerm: meta.isLongTerm,
      history: vHistory
    });
  }

  logToSheet_(`候補リスト作成完了: ${list.length} 件`);

  // スコア順にソートしてTop Nを確定
  list.sort((a, b) => b.heat - a.heat);
  const TOP_AI = 30; // AI分析の対象曲数 (30位まで監査を維持)
  const candidatesForAi = list.slice(0, TOP_AI);

  // --- Gemini AIによる深層分析 ---
  const typeLabel = lookbackDays === 1 ? 'Daily' : 'Weekly';

  // 精度向上のため、上位20曲のメタデータ（概要欄・タグ・サムネイル）を個別に取得
  const topIds = candidatesForAi.map(c => c.id);
  try {
    const videoRes = YouTube.Videos.list('snippet', { id: topIds.join(',') });
    const videoMetaMap = new Map();
    if (videoRes && videoRes.items) {
      videoRes.items.forEach(v => {
        videoMetaMap.set(v.id, {
          description: v.snippet.description,
          tags: v.snippet.tags || [],
          thumbnail: v.snippet.thumbnails?.high?.url || v.snippet.thumbnails?.default?.url
        });
      });
    }

    // 候補に詳細メタデータを紐付け
    candidatesForAi.forEach(c => {
      const vMeta = videoMetaMap.get(c.id);
      if (vMeta) {
        c.description = vMeta.description;
        c.tags = vMeta.tags;
        c.thumbnail = vMeta.thumbnail;
      }
    });
  } catch (e) {
    logToSheet_('Extra Video Meta Fetch Error: ' + e.message);
  }

  // 前回の順位を記憶 (videoId -> rank) - AI分析のコンテキストとして使用するため先に取得
  // 前回の順位を記憶 (videoId -> rank)
  const prevRankMap = new Map();

  // 1. 直前の実行結果から取得 (Yesterday's rank)
  if (shRank.getLastRow() > 1) {
    const prevData = shRank.getDataRange().getValues();
    const headers = prevData[0].map(h => String(h || '').trim());
    const vIdIdx = headers.indexOf('videoId');
    const rankIdx = headers.indexOf('順位');
    const prevRankIdx = headers.indexOf('PrevRank');
    const dateIdx = headers.indexOf('日付');

    for (let i = 1; i < prevData.length; i++) {
      const vid = String(prevData[i][vIdIdx]).trim();
      const rowDate = toDateKey(prevData[i][dateIdx]);

      let historicalRank = NaN;
      if (rowDate === latestDate && prevRankIdx !== -1) {
        historicalRank = parseInt(prevData[i][prevRankIdx]);
      } else {
        historicalRank = parseInt(prevData[i][rankIdx]);
      }

      if (vid && !isNaN(historicalRank) && historicalRank !== 0) {
        prevRankMap.set(vid, historicalRank);
      }
    }
  }

  // 2. さらに過去の全履歴 (RANK_HISTORY) をチェック (EVER-RANKED判定用)
  const shHistory = ss.getSheetByName('RANK_HISTORY');
  const everRankMap = new Map();
  if (shHistory) {
    const historyData = shHistory.getDataRange().getValues();
    // 過去データから「その曲の最後に見られた順位」を拾う (上書き更新していくことで最新を保持)
    for (let i = 1; i < historyData.length; i++) {
      const vid = String(historyData[i][1]).trim();
      const r = parseInt(historyData[i][3]);
      if (vid && !isNaN(r)) everRankMap.set(vid, r);
    }
  }

  // 候補に前回順位を紐付け
  candidatesForAi.forEach(c => {
    // [改善] 前日になくても過去に一度でも入っていれば、その最後に見られた順位を PrevRank に採用する
    const yesterdayRank = prevRankMap.get(c.id);
    const historicalRank = everRankMap.get(c.id);
    c.prevRank = yesterdayRank || historicalRank || 100;
  });

  // 同期的なAI分析を廃止し、バックグラウンド処理（enrichAiInsights_）へ移行
  logToSheet_('同期的AI分析をスキップし、骨格ランキングを作成します...');

  // 最終的なランキングTop 40を確定
  const top = candidatesForAi.slice(0, 40);

  // 決定したTop Nを書き込み（ヘッダーは冒頭で作成済みのためクリアせず追加）
  // 以前のデータ行のみを削除して書き込み

  if (top.length > 0) {
    // 過去のランキングデータをクリア（書き込み直前に行う）
    if (shRank.getLastRow() > 1) {
      shRank.getRange(2, 1, shRank.getLastRow() - 1, shRank.getLastColumn()).clearContent();
    }
  } else {
    logToSheet_(`WARNING: Ranking generation produced 0 items. Keeping previous data to avoid empty sheet.`);
    return; // 0件なら何もしない（前日のデータを守る）
  }

  const out = top.map((x, i) => [
    latestDate,
    i + 1,
    (x.prevRank && x.prevRank !== 100) ? x.prevRank : '-', 
    x.artist,
    x.title,
    (() => {
      try {
        if (!x.publishedAt) return '';
        const d = new Date(x.publishedAt);
        if (isNaN(d.getTime())) return '';
        return d.toISOString();
      } catch (e) { return ''; }
    })(),
    x.spark,
    (x.aiScore !== undefined && x.aiScore !== null) ? x.aiScore : '-',
    x.aiReason || '-',
    x.aiInsight || '-',
    x.shortInsight || '-', 
    x.genre || '-',
    x.visualConcept || '-',
    Math.round(x.heat * 100) / 100,                                     // 13: Heatスコア
    Math.round(Math.min(1.0, x.commUnique || 1.0) * 100) + '%',         // 14: コメ品質
    Math.round(x.growth * 10000) / 100 + '%',                          // 15: 成長率(%)
    Math.round(Math.min(1.0, x.eng) * 10000) / 100 + '%',              // 16: 反応率
    x.dv,                                                               // 17: 増加数(1d) (diffColName)
    x.dl,                                                               // 18: 今日いいね
    x.dc,                                                               // 19: 今日コメ
    x.totalV,                                                           // 20: 現在再生数
    x.baseV,                                                            // 21: prevColName
    `https://youtu.be/${x.id}`,                                        // 22: YouTube
    x.fbUrl ? `=HYPERLINK("${x.fbUrl}","Facebook")` : '',              // 23: Facebook
    x.alert + x.reason,                                                 // 24: 備考
    x.id,                                                               // 25: videoId
    "'" + x.history.slice(-14).join(';'),                               // 26: historyRaw
    x.isLongTerm ? 'TRUE' : ''                                          // 27: LongTermFlag (Internal)
  ]);

  logToSheet_(`シート書込開始: ${out.length} 行...`);
  if (out.length) {
    const range = shRank.getRange(2, 1, out.length, out[0].length);
    range.setValues(out);
    shRank.getRange(2, 2, out.length, 1).setNumberFormat('0');
  }

  // --- 公式順位履歴の記録 ---
  recordRankHistory_(top, targetSheetName);
  // -------------------------

  logToSheet_(`【完了】generateRanking (${targetSheetName}) 全工程終了`);

  // デイリーランキングの場合のみ、非同期のAI解析トリガーを発火
  if (targetSheetName === CFG.SHEET_RANKING_DAILY) {
      logToSheet_(`バックグラウンドのAIエンリッチメント(enrichAiInsights_)を10秒後に予約します...`);
      ScriptApp.newTrigger('enrichAiInsights_')
          .timeBased()
          .after(10000)
          .create();
  }
}

/**
 * ランキング履歴を保存する（グラフ表示用）
 */
function recordRankHistory_(top, typeLabel) {
  try {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    let sh = ss.getSheetByName('RANK_HISTORY');
    if (!sh) {
      sh = ss.insertSheet('RANK_HISTORY');
      sh.appendRow(['date', 'videoId', 'type', 'rank', 'heatScore']);
    }

    const tz = Session.getScriptTimeZone();
    const todayStr = Utilities.formatDate(new Date(), tz, 'yyyy-MM-dd');
    
    // 現在の履歴を読み込み（重複防止用）
    const lastRow = sh.getLastRow();
    const historyData = lastRow > 1 ? sh.getRange(2, 1, lastRow - 1, 3).getValues() : [];
    const existingKeys = new Set(historyData.map(row => `${toDateKey_(row[0], tz)}_${row[1]}_${row[2]}`));

    const rows = [];
    top.forEach((item, i) => {
      const key = `${todayStr}_${item.id}_${typeLabel}`;
      if (!existingKeys.has(key)) {
        rows.push([
          todayStr,
          item.id,
          typeLabel,
          i + 1,
          Math.round(item.heat * 100) / 100
        ]);
      }
    });

    if (rows.length > 0) {
      sh.getRange(sh.getLastRow() + 1, 1, rows.length, 5).setValues(rows);
      logToSheet_(`RANK_HISTORY: ${rows.length} 件の履歴を記録しました。`);
    }

    // 30日以上前の古い履歴を削除
    pruneRankHistory_(sh, 30);

  } catch (e) {
    logToSheet_('Error in recordRankHistory_: ' + e.message);
  }
}

/**
 * 古いランキング履歴を削除する
 */
function pruneRankHistory_(sh, keepDays) {
  try {
    const lastRow = sh.getLastRow();
    if (lastRow < 2) return;

    const data = sh.getRange(2, 1, lastRow - 1, 1).getValues();
    const now = new Date();
    const cutoff = new Date(now.getTime() - (keepDays * 24 * 60 * 60 * 1000));
    
    const rowsToDelete = [];
    for (let i = data.length - 1; i >= 0; i--) {
      const rowDate = new Date(data[i][0]);
      if (!isNaN(rowDate.getTime()) && rowDate < cutoff) {
        rowsToDelete.push(i + 2);
      }
    }

    // 連続する行をまとめて削除するなどの最適化はせず、後ろから1つずつ（または数個ずつ）
    // 大量にある場合はパフォーマンス注意だが、1日20件×30日=600件程度なら問題ない
    rowsToDelete.forEach(row => sh.deleteRow(row));
    if (rowsToDelete.length > 0) {
      logToSheet_(`RANK_HISTORY: ${rowsToDelete.length} 件の古い履歴を削除しました。`);
    }
  } catch (e) {
    logToSheet_('Error in pruneRankHistory_: ' + e.message);
  }
}

/* ---------------- helpers ---------------- */

function ensureSongsHeader_(sh) {
  if (sh.getLastRow() === 0) {
    sh.appendRow(['videoId', 'artist', 'title', 'publishedAt']);
    return;
  }
  const h = sh.getRange(1, 1, 1, 4).getValues()[0];
  if (String(h[0]) !== 'videoId') {
    sh.insertRowBefore(1);
    sh.getRange(1, 1, 1, 4).setValues([['videoId', 'artist', 'title', 'publishedAt']]);
  }
}

function pruneSongs60d_(shSongs, keepDays) {
  const now = new Date();
  const cutoff = new Date(now);
  cutoff.setDate(cutoff.getDate() - keepDays);

  const values = shSongs.getDataRange().getValues();
  if (values.length < 2) return 0;

  const keep = [values[0]]; // header
  const movedToLong = [];

  // 現在のランキングに入っている曲を取得 (videoId のリスト)
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const shRank = ss.getSheetByName(CFG.SHEET_RANKING_DAILY);
  const currentHitIds = new Set();
  if (shRank) {
    const rankData = shRank.getDataRange().getValues();
    if (rankData.length > 1) {
      // RANKING_DAILY の w:videoId (23列目、0-indexed: 23)
      for (let i = 1; i < rankData.length; i++) {
        const vid = String(rankData[i][23] || '').trim();
        if (vid) currentHitIds.add(vid);
      }
    }
  }

  for (let i = 1; i < values.length; i++) {
    const videoId = values[i][CFG.SONGS_COLS.videoId];
    const publishedAt = values[i][CFG.SONGS_COLS.publishedAt];
    const d = new Date(publishedAt || '');
    if (!d || isNaN(d.getTime())) continue;

    if (d >= cutoff) {
      keep.push(values[i]);
    } else if (currentHitIds.has(videoId)) {
      // 60日経過しているが、現在ランキング入りしている場合は SONGS_LONG へ
      movedToLong.push(values[i]);
      Logger.log(`Song [${videoId}] moved to SONGS_LONG (Hit survived > 60 days)`);
    }
  }

  // SONGS_LONG への書き込み
  if (movedToLong.length > 0) {
    const shLong = ss.getSheetByName(CFG.SHEET_SONGS_LONG) || ss.insertSheet(CFG.SHEET_SONGS_LONG);
    ensureSongsHeader_(shLong);
    
    // 重複チェック
    const longData = shLong.getDataRange().getValues();
    const existingLongIds = new Set(longData.map(r => String(r[0]).trim()));
    const finalToMove = movedToLong.filter(row => !existingLongIds.has(String(row[0]).trim()));
    
    if (finalToMove.length > 0) {
      shLong.getRange(shLong.getLastRow() + 1, 1, finalToMove.length, finalToMove[0].length).setValues(finalToMove);
    }
  }

  if (keep.length !== values.length) {
    const deleted = values.length - keep.length;
    // [安全対策] clear() してから setValues() だと、途中でエラー時に全ロスするリスクがあるため
    // 安全に「新しい内容で上書き」を行う
    if (shSongs.getLastRow() > 0) {
      shSongs.getRange(1, 1, shSongs.getLastRow(), values[0].length).clearContent();
    }
    shSongs.getRange(1, 1, keep.length, keep[0].length).setValues(keep);
    Logger.log(`SONGS pruned: ${values.length - 1} -> ${keep.length - 1} (Deleted: ${deleted})`);
    return deleted;
  }
  return 0;
}

/**
 * SONGSシートを公開日(D列)の新しい順にソートする
 */
function sortSongsSheet_(sh) {
  const lastRow = sh.getLastRow();
  if (lastRow < 2) return;

  // A:videoId, B:artist, C:title, D:publishedAt
  // D列(4列目)を降順(false)でソート
  sh.getRange(2, 1, lastRow - 1, 4).sort({ column: 4, ascending: false });
  Logger.log('SONGS sheet sorted by publishedAt (Descending).');
}

/**
 * メニューから手動でSONGSシートのソートを実行する
 */
function manualSortSongs() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sh = ss.getSheetByName(CFG.SHEET_SONGS);
  if (!sh) {
    SpreadsheetApp.getUi().alert('SONGSシートが見つかりません。');
    return;
  }
  sortSongsSheet_(sh);
  SpreadsheetApp.getUi().alert('SONGSシートを公開日の新しい順にソートしました。');
}

/**
 * SONGSシートの重複（videoId重複）を掃除する管理ツール
 */
function cleanupDuplicateSongs() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const shS = ss.getSheetByName(CFG.SHEET_SONGS);
  if (!shS) return;

  const data = shS.getDataRange().getValues();
  if (data.length < 2) return;

  const header = data[0];
  const uniqueRows = [header];
  const seen = new Set();
  let count = 0;

  for (let i = 1; i < data.length; i++) {
    const videoId = String(data[i][CFG.SONGS_COLS.videoId] || '').trim();
    if (!videoId) continue;

    if (seen.has(videoId)) {
      count++;
    } else {
      seen.add(videoId);
      uniqueRows.push(data[i]);
    }
  }

  if (count > 0) {
    shS.clear(); // シート全体（内容と書式）をクリア
    shS.getRange(1, 1, uniqueRows.length, uniqueRows[0].length).setValues(uniqueRows);
    SpreadsheetApp.getUi().alert(`清掃完了: ${count} 件の重複曲を削除しました。`);
  } else {
    SpreadsheetApp.getUi().alert('重複曲は見つかりませんでした。');
  }
}

/**
 * 汎用的な日付キーへの変換 (yyyy-MM-dd)
 */
function toDateKey_(v, tz) {
  if (!v) return '';
  if (Object.prototype.toString.call(v) === '[object Date]') {
    return Utilities.formatDate(v, tz || Session.getScriptTimeZone(), 'yyyy-MM-dd');
  }
  const s = String(v).trim();
  const d = new Date(s);
  if (!isNaN(d.getTime())) {
    return Utilities.formatDate(d, tz || Session.getScriptTimeZone(), 'yyyy-MM-dd');
  }
  return s;
}

/**
 * 動画が条件に合致するか判定し、SONGS用行データを生成する
 */
function validateAndCreateSongRow_(v, artistInfo) {
  const title = String(v.snippet.title || '').trim();
  const publishedAt = v.snippet.publishedAt || '';
  const categoryId = String(v.snippet.categoryId || '');
  const viewCount = Number(v.statistics.viewCount || 0);
  const durSec = iso8601DurationToSeconds_(v.contentDetails.duration || 'PT0S');
  const now = new Date();

  // 音楽・エンタメ・ブログ以外を除外
  if (categoryId !== '10' && categoryId !== '24' && categoryId !== '22') return null;
  // Shorts を除外
  if (durSec < CFG.MIN_DURATION_SEC) return null;
  // 古すぎる動画を除外
  const pub = new Date(publishedAt);
  const ageDays = (now - pub) / (1000 * 60 * 60 * 24);
  if (ageDays > CFG.LOOKBACK_DAYS_SONGS) return null;

  // リンク付きタイトル
  const videoUrl = "https://www.youtube.com/watch?v=" + v.id;
  const linkedTitle = '=HYPERLINK("' + videoUrl + '", "' + title.replace(/"/g, '""') + '")';
  
  return [v.id, artistInfo.name, linkedTitle, publishedAt];
}

/**
 * 配列を指定サイズごとに分割するヘルパー
 */
function chunk_(arr, size) {
  const out = [];
  if (!arr) return out;
  for (let i = 0; i < arr.length; i += size) {
    out.push(arr.slice(i, i + size));
  }
  return out;
}

/**
 * ISO 8601 形式の期間（PT1M30Sなど）を秒数に変換する
 */
function iso8601DurationToSeconds_(dur) {
  const m = String(dur || '').match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!m) return 0;
  const h = parseInt(m[1] || '0', 10);
  const min = parseInt(m[2] || '0', 10);
  const s = parseInt(m[3] || '0', 10);
  return h * 3600 + min * 60 + s;
}



/* -------------------------------------------------------------------------- */
/*                                Vertex AI Logic                               */
/* -------------------------------------------------------------------------- */

const GEMINI_CONFIG = {
  // スクリプトプロパティ 'GEMINI_API_KEY'
  API_KEY: PropertiesService.getScriptProperties().getProperty('GEMINI_API_KEY'),
  MODEL_NAME: 'gemini-2.5-flash',
};

/**
 * デバッグログをスプレッドシートに記録する
 * @param {string} msg 記録するメッセージ
 */
function logToSheet_(msg) {
  try {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    let sh = ss.getSheetByName('DEBUG_LOG');
    if (!sh) sh = ss.insertSheet('DEBUG_LOG');
    sh.appendRow([new Date(), String(msg)]);
  } catch (e) { }
}

/**
 * AIシステムが利用可能かチェックする
 * @returns {boolean} AIシステムが利用可能であればtrue
 */
function isAiSystemReady_() {
  if (!GEMINI_CONFIG.API_KEY) {
    logToSheet_('【システム通知】GEMINI_API_KEY がスクリプトプロパティに設定されていません。スプレッドシートの「設定」などを確認してください。');
    return false;
  }
  return true;
}

/**
 * Gemini（Vertex AI 互換）を通じてランキング分析を実行
 * @param {Array} contextData 現在の計算式で出された上位曲リスト
 * @param {string} typeLabel 'Daily' or 'Weekly'
 */
function analyzeRankingWithAi(contextData, typeLabel) {
  if (!isAiSystemReady_()) {
    logToSheet_('AI System is not ready or keys are missing. Skipping analysis.');
    return null;
  }

  try {
    const totalSongs = contextData.length;
    const chunkSize = 3; // 1回あたり3曲ずつ解析 (30曲を10回で処理) に縮小して安定化
    const allResultsMap = new Map();

    SpreadsheetApp.getActiveSpreadsheet().toast(`AI分析を開始します (全${totalSongs}曲 / ${chunkSize}曲ずつ分割実行)...`, 'Gemini AI', 5);
    logToSheet_(`Starting Chunked Gemini Analysis for ${typeLabel} (Total: ${totalSongs}, Chunk: ${chunkSize})`);

    for (let i = 0; i < totalSongs; i += chunkSize) {
      const chunkData = contextData.slice(i, i + chunkSize);
      const simplifiedData = chunkData.map(c => ({
        id: c.id,
        artist: c.artist,
        title: c.title,
        rank_change: c.rankChange || 'NEW',
        prev_rank: c.prevRank || 100,
        daily_views: c.dv,
        total_views: c.totalV,
        total_engagement: c.totalL + c.totalC,
        growth_rate: (c.growth * 100).toFixed(1) + '%',
        engagement: (c.eng * 100).toFixed(2) + '%',
        is_long_term: c.isLongTerm || false,
        days_since_launch: c.publishedAt ? Math.floor((new Date() - new Date(c.publishedAt)) / (1000 * 60 * 60 * 24)) : '-',
        tags: (c.tags || []).slice(0, 10).join(','),
        description: (c.description || '').slice(0, 300),
        comments_sample: fetchComments_(c.id).text
      }));

      const isWeekly = (typeLabel === 'Weekly');
      const prompt = `
# Role
Expert Music Industry Analyst and Digital Trend Researcher specializing in the Cambodian music market. 
You provide sophisticated, data-backed commentary for elite music rankings.

# Task
Analyze the following ${simplifiedData.length} songs. Your goal is to explain the "Reasoning for the Rank" using the provided data.
Ranking Type: ${typeLabel}

# Data
${JSON.stringify(simplifiedData)}

# Directives for 'insight' (English, 2-3 sentences):
- **Data-Backed Reasoning**: Explain the rank using specific ratios. (e.g., "Maintains #1 due to consistent 1M+ total views and an exceptional 5% engagement rate which suggests a loyal fan base.")
- **Trend Analysis**: Reference 'rank_change' and 'prev_rank'. (e.g., "Climbing 5 spots this week as growth momentum surged to 20%.")
- **Sentiment Alignment**: Use 'comments_sample' to corroborate the numbers. (e.g., "The high engagement is backed by an outpouring of appreciation for the lyrics in the comments.")
- **Comment Quality Audit**: Evaluate 'comments_sample' for "Meaningful Content" vs "Generic/Spam". 
  - Meaningful: Specific mention of melody, lyrics, artist's voice, or personal feelings.
  - Generic/Spam: Just emojis, "Nice", bot-like repetition.
- **Avoid Generic Praise**: Do NOT use phrases like "This is a great song" or "Strong debut". Focus on the "Why" of the rank.
- **ID Preservation**: DO NOT ALTER THE id. Return it exactly as provided.
- **Scoring Consistency**: Use the following internal weights for aiHeatScore:
  - 40%: Daily View Count (Volume)
  - 30%: Engagement Rate (Likes/Comments ratio)
  - 20%: Growth Momentum (Daily increase relative to total)
  - 10%: Cumulative Stature (Total views/History)
- **Deterministic**: Always provide the same score for the same input data.

# Requirements for each song:
1. ID Preservation: **DO NOT ALTER THE id**. Return it exactly as it was provided.
2. Naming Normalization: Show clean artist and title (Remove "Official", "Production", "MV" suffixes).
3. aiHeatScore (0-200): Calculate based on VIEW VOLUME + GROWTH MOMENTUM + ENGAGEMENT QUALITY. Over-weighting just one is a mistake.
4. aiReason (Japanese): Concise data-focused logic (60-80 chars). e.g., "再生数とエンゲージメント率のバランスがトップ。TikTokでのバズがコメント欄から確認できる。"
5. insight (English): A 2-3 sentence journalistic analysis.
   - DO NOT repeat phrases like "This track marks a strong debut". Be creative.
   - Cross-reference view growth with engagement.
   - **CRITICAL**: Use 'comments_sample' to mention WHY fans are listening.
6. shortInsight (English): A punchy summary (max 10 words).
7. commentQualityScore (0.0 to 1.0): **CRITICAL**. Analyze 'comments_sample'.
   - 0.8-1.0: Deep, specific, and passionate fans.
   - 0.5-0.7: Mixed content or generic appreciation.
   - 0.0-0.4: Dominated by spam, emojis, or one-word repetitive comments.
8. genre & visualConcept: Be analytical.

# Format (JSON Array only)
- Return a JSON array of objects.
- Ensure the 'id' field matches the input exactly.
[{ "id": "...", "artist": "...", "title": "...", "aiHeatScore": 150, "aiReason": "...", "insight": "...", "shortInsight": "...", "commentQualityScore": 0.9, "genre": "...", "visualConcept": "..." }]
`;

      logToSheet_(`Batch ${Math.floor(i / chunkSize) + 1} call...`);
      const response = callGeminiApi_(prompt);
      if (!response) {
        logToSheet_(`Batch ${Math.floor(i / chunkSize) + 1} returned null. Skipping.`);
        continue;
      }

      // JSON抽出 (より堅牢な方法)
      let jsonStr = response.trim();
      const jsonMatch = jsonStr.match(/\[[\s\S]*\]/); // 配列 [...] を探す
      if (jsonMatch) {
          jsonStr = jsonMatch[0];
      } else {
          // バックアップ: 既存のコードブロック除去
          if (jsonStr.startsWith('```json')) jsonStr = jsonStr.substring(7);
          else if (jsonStr.startsWith('```')) jsonStr = jsonStr.substring(3);
          if (jsonStr.endsWith('```')) jsonStr = jsonStr.substring(0, jsonStr.length - 3);
          jsonStr = jsonStr.trim();
      }

      try {
        const result = JSON.parse(jsonStr);
        const results = Array.isArray(result) ? result : (result.results || []);
        results.forEach(item => {
          if (item.id) allResultsMap.set(String(item.id), item);
          else allResultsMap.set(`${item.artist} - ${item.title}`, item);
        });
        logToSheet_(`Batch ${Math.floor(i / chunkSize) + 1} success: ${results.length} songs analyzed.`);
      } catch (parseError) {
        logToSheet_(`Batch ${Math.floor(i / chunkSize) + 1} JSON Parse Error: ${parseError.message}. Snippet: ${jsonStr.slice(0, 100)}...`);
        // エラーの詳細をログ出力 (デバッグ用)
        console.error(`Batch ${Math.floor(i / chunkSize) + 1} Raw Response:`, response);
      }
    }

    logToSheet_(`Total results collected: ${allResultsMap.size}`);
    return allResultsMap.size > 0 ? allResultsMap : null;

  } catch (e) {
    logToSheet_('Gemini Chunked Analysis Error: ' + e.message + '\n' + e.stack);
    return null;
  }
}

/**
 * 指定した動画のコメントを最新順に取得し、質の低い（無意味な）コメントを除外・判定する
 * @param {string} videoId 
 * @returns {object} { text: string, cleanRatio: number }
 */
function fetchComments_(videoId) {
  let rawComments = [];

  try {
    const options = {
      videoId: videoId,
      maxResults: 50,
      order: 'relevance'
    };

    const res = YouTube.CommentThreads.list('snippet', options);
    updateApiUsage_('YouTube', 1); // 1 unit
    
    if (res && res.items) {
      res.items.forEach(it => {
        rawComments.push(it.snippet.topLevelComment.snippet.textDisplay);
      });
    }

    if (rawComments.length === 0) return { text: "", cleanRatio: 1.0 };

    // --- 機械的フィルタリング (Regex) ---
    const meaningfulComments = rawComments.filter(text => {
      const clean = text.replace(/<[^>]*>/g, "").trim(); // HTMLタグ除去
      if (clean.length < 3) return false; // 短すぎる
      if (/^[\W_]+$/.test(clean.replace(/\s/g, ""))) return false; // 記号・絵文字のみ
      if (/(.)\1{4,}/.test(clean)) return false; // 同じ文字の5回以上の繰り返し
      return true;
    });

    const cleanRatio = meaningfulComments.length / rawComments.length;
    return {
      text: meaningfulComments.join("\n").slice(0, 5000),
      cleanRatio: Math.max(0.1, cleanRatio)
    };
  } catch (e) {
    Logger.log(`Comment Fetch Error [${videoId}]: ${e.message}`);
    return { text: "", cleanRatio: 1.0 };
  }
}

/**
 * Gemini API 呼び出し用の内部関数 (Vertex AI API 互換)
 */
function callGeminiApi_(prompt) {
  const url = `https://generativelanguage.googleapis.com/v1/models/${GEMINI_CONFIG.MODEL_NAME}:generateContent?key=${GEMINI_CONFIG.API_KEY}`;
  const maxRetries = 5;
  let retryCount = 0;
  let backoffMs = 15000;

  const payload = {
    contents: [{
      parts: [{ text: prompt }]
    }],
    generationConfig: {
      temperature: 0.0,
      topP: 0.95,
      topK: 40,
      maxOutputTokens: 16384
    },
    safetySettings: [
      { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" },
    ]
  };

  const options = {
    method: 'post',
    contentType: 'application/json',
    payload: JSON.stringify(payload),
    muteHttpExceptions: true
  };

  while (retryCount < maxRetries) {
    const response = UrlFetchApp.fetch(url, options);
    const resCode = response.getResponseCode();
    const resText = response.getContentText();

    if (resCode === 200) {
      if (!resText) {
        logToSheet_("Gemini API Error: Empty response text");
        return null;
      }
      const resJson = JSON.parse(resText);
      if (!resJson.candidates || !resJson.candidates[0].content || !resJson.candidates[0].content.parts) {
        logToSheet_("Gemini API Error: Unexpected response structure : " + resText);
        return null;
      }
      
      // トークン使用量の記録
      if (resJson.usageMetadata && resJson.usageMetadata.totalTokenCount) {
        updateApiUsage_('Gemini', resJson.usageMetadata.totalTokenCount);
      } else {
        updateApiUsage_('Gemini', 0); // Count request even if tokens missing
      }
      
      return resJson.candidates[0].content.parts[0].text;
    }

    if (resCode === 429 || resCode === 500 || resCode === 503 || resCode === 504) {
      const msg = `API混雑または一時的なエラー (Code: ${resCode}, Retry ${retryCount + 1}/${maxRetries}): ${backoffMs / 1000}秒待機します...`;
      SpreadsheetApp.getActiveSpreadsheet().toast(msg, 'Gemini AI', 10);
      logToSheet_(`Gemini API ${resCode} (Retry ${retryCount + 1}/${maxRetries}): Waiting ${backoffMs}ms... Error: ${resText.slice(0, 200)}`);
      Utilities.sleep(backoffMs);
      retryCount++;
      backoffMs *= 2;
      if (backoffMs > 60000) backoffMs = 60000; // Cap backoff at 60s
      continue;
    }

    logToSheet_(`Gemini API Error (${resCode}) at ${url.split('?')[0]}: ${resText}`);
    return null; // Non-retryable error
  }

  logToSheet_("Gemini API Error: Max retries reached for 429.");
  return null;
}

/**
 * AI設定の状態を確認し、ログに出力する。
 */
function checkAiConfiguration() {
  const key = PropertiesService.getScriptProperties().getProperty('GEMINI_API_KEY');
  if (!key) {
    Logger.log('❌ GEMINI_API_KEY が設定されていません。Project Settings > Script Properties に追加してください。');
  } else {
    Logger.log('✅ GEMINI_API_KEY は設定されています (末尾: ...' + key.slice(-4) + ')');
    testListModels(); // 通信テスト
  }
}

/**
 * 利用可能なモデル一覧をログに出力し、APIキーの有効性をテスト。
 */
function testListModels() {
  // モデル一覧取得は v1beta のみサポート
  const url = `https://generativelanguage.googleapis.com/v1/models?key=${GEMINI_CONFIG.API_KEY}`;
  try {
    const response = UrlFetchApp.fetch(url, { muteHttpExceptions: true });
    const code = response.getResponseCode();
    const content = response.getContentText();
    if (code === 200) {
      const json = JSON.parse(content);
      const names = json.models.map(m => m.name.replace('models/', ''));
      Logger.log('【診断】利用可能なモデル一覧: ' + names.join(', '));
      Logger.log('【アドバイス】もし gemini-1.5-flash が無い場合は、上記リストにあるモデル名を PickSongs.gs の GEMINI_CONFIG.MODEL_NAME に設定してください。');
    } else {
      Logger.log(`❌ モデル一覧の取得に失敗 (Code: ${code}): ${content}`);
    }
  } catch (e) {
    Logger.log(`❌ 通信エラー: ${e.message}`);
  }
}

function runTestGen() { logToSheet_("testGen: " + callGeminiApi_("Translate Hello to Japanese.")); }

function debugTop5HeatScore() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const shSnap = ss.getSheetByName(CFG.SHEET_SNAPSHOT);
  const snap = shSnap.getDataRange().getValues();
  if (snap.length < 2) return;

  const tz = Session.getScriptTimeZone();
  const toDateKey = (v) => toDateKey_(v, tz);

  const dateSet = new Set();
  for (let i = 1; i < snap.length; i++) {
    const dk = toDateKey(snap[i][0]);
    if (dk) dateSet.add(dk);
  }
  const dates = Array.from(dateSet).sort();
  if (dates.length < 2) return;
  const latestDate = dates[dates.length - 1];

  let baseDate = dates[dates.length - 2]; // For daily

  const LMap = new Map();
  const BMap = new Map();

  for (let i = 1; i < snap.length; i++) {
    const dt = toDateKey(snap[i][0]);
    const id = String(snap[i][1]).trim();
    const v = Number(snap[i][2]) || 0;
    const l = Number(snap[i][3]) || 0;
    const c = Number(snap[i][4]) || 0;

    if (dt === latestDate) LMap.set(id, { v, l, c });
    if (dt === baseDate) BMap.set(id, { v, l, c });
  }

  let shRank = ss.getSheetByName('TEST_RANKING');
  if (!shRank) {
    shRank = ss.getSheetByName('DailyRanking');
  }
  if (!shRank) {
    logToSheet_("ERROR: Neither TEST_RANKING nor DailyRanking sheet found.");
    return;
  }
  const rankData = shRank.getDataRange().getValues();
  const topIds = [];
  for (let i = 1; i <= 5; i++) {
    if (rankData[i] && rankData[i][22]) {
      topIds.push(rankData[i][22].trim()); // videoId is in col 23 (index 22)
    }
  }

  logToSheet_("=== HEAT SCORE MATH DEGUG ===");
  topIds.forEach((id, idx) => {
    const L = LMap.get(id);
    let B = BMap.get(id);

    // If no baseline from snap, assume 0 for exact fresh track scenario
    if (!B) B = { v: 0, l: 0, c: 0 };

    const dvRaw = L.v - B.v;
    const dlRaw = L.l - B.l;
    const dcRaw = L.c - B.c;

    const dv = Math.max(0, dvRaw);
    const dl = Math.max(0, dlRaw);
    const dc = Math.max(0, dcRaw);

    const scale = 1 + (Math.log10(L.v + 1) / 10);

    const heat_dv = 5 * Math.log(dv + 1) * scale;
    const heat_dl = 3 * Math.log(dl + 1);
    const heat_dc = 5 * Math.log(dc + 1);

    const heat = heat_dv + heat_dl + heat_dc;

    logToSheet_(`Rank ${idx + 1}: [${id}]`);
    logToSheet_(`- L.v/l/c = ${L.v}/${L.l}/${L.c} | B.v/l/c = ${B.v}/${B.l}/${B.c}`);
    logToSheet_(`- dv/dl/dc = ${dv}/${dl}/${dc}`);
    logToSheet_(`- scale(log(L.v+1)) = ${scale.toFixed(4)}`);
    logToSheet_(`- heat_dv = ${heat_dv.toFixed(4)} | heat_dl = ${heat_dl.toFixed(4)} | heat_dc = ${heat_dc.toFixed(4)}`);
    logToSheet_(`- Total Heat = ${heat.toFixed(4)}`);
  });
}

/**
 * 動画のコメントを最大100件取得してテキストとして返す
 * @param {string} videoId 
 * @returns {string} 各コメントを改行で繋いだテキスト
 */
function fetchComments_(videoId) {
  let comments = [];
  let nextPageToken = null;

  try {
    // 1ページ最大50件 × 1回 = 50件取得 (実行時間短縮のため100件から50件に制限)
    for (let i = 0; i < 1; i++) {
      const options = {
        videoId: videoId,
        maxResults: 50,
        order: 'relevance'
      };
      if (nextPageToken) options.pageToken = nextPageToken;

      const res = YouTube.CommentThreads.list('snippet', options);
      updateApiUsage_('YouTube', 1); // 1 unit
      if (!res || !res.items || res.items.length === 0) break;

      res.items.forEach(it => {
        comments.push(it.snippet.topLevelComment.snippet.textDisplay);
      });

      nextPageToken = res.nextPageToken;
      if (!nextPageToken) break;
    }

    if (comments.length === 0) return "";

    // AIへの送信データを5000文字程度に拡大し、より多くのサンプルで判定を安定させる
    return comments
      .join("\n")
      .slice(0, 5000);
  } catch (e) {
    Logger.log(`Comment Fetch Error [${videoId}]: ${e.message}`);
    return "";
  }
}

/**
 * バックグラウンドでAIインサイトを段階的に生成し、シートを更新する非同期パイプライン
 */
function enrichAiInsights_() {
  logToSheet_('SYSTEM: enrichAiInsights_ を開始します');
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const shRank = ss.getSheetByName(CFG.SHEET_RANKING_DAILY);
  if (!shRank) return;

  const data = shRank.getDataRange().getValues();
  if (data.length < 2) return;

  const toProcess = [];
  const chunkSize = 5; // 1回の起動で処理する曲数 (安全圏)

  for (let i = 1; i < data.length; i++) {
    const aiInsight = String(data[i][7]).trim(); // AIScore (H列, Index 7) で判定
    if (aiInsight === '-' || aiInsight === '') {
      toProcess.push({
        rowNum: i + 1,
        id: data[i][25],       // videoId: 26列目 (Index 25)
        rank: data[i][1],      // 順位: 2列目 (Index 1)
        prevRank: data[i][2] === '-' ? 100 : (parseInt(data[i][2]) || 100),
        artist: data[i][3],
        title: data[i][4],
        dv: data[i][17],       // dv: 18列目 (Index 17)
        totalL: data[i][18],   // l: 19列目
        totalC: data[i][19],   // c: 20列目
        totalV: data[i][20],   // totalV: 21列目
        growth: parseFloat(String(data[i][15]).replace('%', '')) || 0, // growth: 16列目
        eng: parseFloat(String(data[i][16]).replace('%', '')) || 0     // eng: 17列目
      });
      if (toProcess.length >= chunkSize) break;
    }
  }

  if (toProcess.length === 0) {
    logToSheet_('enrichAiInsights_: すべての曲のAI分析が完了しています。パイプラインを終了します。');
    // キャッシュを念のため更新
    if (typeof updateRankingCache === 'function') updateRankingCache();
    return;
  }

  logToSheet_(`enrichAiInsights_: ${toProcess.length}件のAI分析を開始します (Rank: ${toProcess.map(x=>x.rank).join(', ')})`);

  // YouTubeメタデータ（タグ、概要欄）の補完
  const topIds = toProcess.map(c => c.id);
  const videoMetaMap = new Map();
  try {
    const videoRes = YouTube.Videos.list('snippet', { id: topIds.join(',') });
    if (videoRes && videoRes.items) {
      videoRes.items.forEach(v => {
        videoMetaMap.set(v.id, {
          description: v.snippet.description,
          tags: v.snippet.tags || []
        });
      });
    }
  } catch (e) {
    logToSheet_('enrichAiInsights_ Video Meta Error: ' + e.message);
  }

  const simplifiedData = toProcess.map(c => {
    const vMeta = videoMetaMap.get(c.id) || {description: '', tags: []};
    const cData = fetchComments_(c.id);
    return {
      id: c.id,
      artist: c.artist,
      title: c.title,
      rank_change: c.prevRank === 100 ? 'NEW' : (c.prevRank - c.rank),
      prev_rank: c.prevRank,
      daily_views: c.dv,
      total_views: c.totalV,
      total_engagement: c.totalL + c.totalC,
      growth_rate: c.growth + '%',
      engagement: c.eng + '%',
      tags: vMeta.tags.slice(0, 10).join(','),
      description: vMeta.description.slice(0, 300),
      comments_sample: cData.text,
      clean_ratio: cData.cleanRatio
    };
  });

  // AI実行 (Chunkingは既に外側で制御しているため、このまま渡す)
  const aiResults = analyzeRankingWithAi(simplifiedData, 'Daily');

  if (aiResults) {
    const aiArray = Array.from(aiResults.values());
    let writeCount = 0;
    
    toProcess.forEach((c, index) => {
      let aiData = aiResults.get(String(c.id)) || aiResults.get(`${c.artist} - ${c.title}`);
      if (!aiData && aiArray.length >= toProcess.length) {
        aiData = aiArray[index];
      }

      if (aiData) {
        // AI結果の構造化
        // Geminiの品質スコアと、機械的なクリーン率を組み合わせる (AI 70% : 機械 30%)
        const geminiQ = Number(aiData.commentQualityScore || aiData.commentqualityscore || 1.0);
        const mechQ = Number(toProcess[index].clean_ratio || 1.0);
        const finalQ = (geminiQ * 0.7) + (mechQ * 0.3);
        
        let qScore = Math.max(0.1, Math.min(1.0, finalQ));

        const ais = [
          aiData.aiHeatScore || aiData.aiScore || Math.floor(c.dv / 1000) || 50, // H (7)
          aiData.aiReason || aiData.aireason || '-',                         // I (8)
          aiData.insight || aiData.aiInsight || aiData.aiinsight || '-',     // J (9)
          aiData.shortInsight || aiData.shortinsight || '-',                 // K (10)
          aiData.genre || aiData.Genre || '-',                               // L (11)
          aiData.visualConcept || aiData.VisualConcept || '-'                // M (12)
        ];

        // H列からM列の6列を一気に書き込み
        shRank.getRange(c.rowNum, 8, 1, 6).setValues([ais]);
        
        // O列 (Index 14 -> 1-based で 15列目) の CommentQuality を更新
        const commq = Math.round(Math.min(1.0, qScore) * 100) + '%';
        shRank.getRange(c.rowNum, 15).setValue(commq);
        
        writeCount++;
      }
    });

    logToSheet_(`enrichAiInsights_: ${writeCount}件の書き込みが成功しました。`);
    
    // まだ未処理の行が残っているかチェックし、あれば1分後に自身を再トリガー
    let remainCount = 0;
    const currentData = shRank.getDataRange().getValues();
    for (let i = 1; i < currentData.length; i++) {
      if (String(currentData[i][7]).trim() === '-') remainCount++;
    }
    
    if (remainCount > 0) {
      logToSheet_(`残りの未処理データが約 ${remainCount} 件あります。1分後に続行します。`);
      ScriptApp.newTrigger('enrichAiInsights_').timeBased().after(60000).create();
    } else {
      logToSheet_('すべてのAIエンリッチメントが完了しました！キャッシュを最終更新します。');
      if (typeof updateRankingCache === 'function') updateRankingCache();
    }
  } else {
    logToSheet_('⚠ enrichAiInsights_: AI処理に失敗しました。5分後にリトライします。');
    ScriptApp.newTrigger('enrichAiInsights_').timeBased().after(300000).create();
  }
}
